import type { SilhouetteDefinition } from "../types";

export const CHARACTER_SILHOUETTES: SilhouetteDefinition[] = [
  {
    id: "fantasy-warrior-male",
    name: "Fantasy Warrior (M)",
    category: "character",
    genres: ["fantasy", "gothic"],
    archetype: "warrior",
    gender: "male",
    tags: [
      "knight",
      "plate",
      "sword",
      "soldier",
      "guard",
      "fighter",
      "champion",
      "armor",
      "paladin",
      "blade",
    ],
    r2Path: "silhouettes/character/fantasy/warrior-male.svg",
  },
  {
    id: "fantasy-warrior-female",
    name: "Fantasy Warrior (F)",
    category: "character",
    genres: ["fantasy", "gothic"],
    archetype: "warrior",
    gender: "female",
    tags: [
      "shieldmaiden",
      "valkyrie",
      "knight",
      "mercenary",
      "sword",
      "warrior",
      "fighter",
      "heroine",
      "armor",
    ],
    r2Path: "silhouettes/character/fantasy/warrior-female.svg",
  },
  {
    id: "fantasy-caster-male",
    name: "Mage / Wizard (M)",
    category: "character",
    genres: ["fantasy"],
    archetype: "caster",
    gender: "male",
    tags: [
      "wizard",
      "mage",
      "staff",
      "robe",
      "archmage",
      "spellcaster",
      "magic",
      "sorcerer",
      "enchanter",
      "scholar",
    ],
    r2Path: "silhouettes/character/fantasy/caster-male.svg",
  },
  {
    id: "fantasy-caster-female",
    name: "Sorceress / Witch (F)",
    category: "character",
    genres: ["fantasy", "gothic"],
    archetype: "caster",
    gender: "female",
    tags: [
      "witch",
      "sorceress",
      "magic",
      "mystic",
      "spellcaster",
      "enchantress",
      "occult",
      "caster",
      "priestess",
    ],
    r2Path: "silhouettes/character/fantasy/caster-female.svg",
  },
  {
    id: "fantasy-rogue-male",
    name: "Rogue / Assassin (M)",
    category: "character",
    genres: ["fantasy", "gothic"],
    archetype: "rogue",
    gender: "male",
    tags: [
      "rogue",
      "thief",
      "dagger",
      "hooded",
      "assassin",
      "shadow",
      "stealth",
      "stalker",
      "ninja",
      "scoundrel",
    ],
    r2Path: "silhouettes/character/fantasy/rogue-male.svg",
  },
  {
    id: "fantasy-rogue-female",
    name: "Ranger / Duelist (F)",
    category: "character",
    genres: ["fantasy", "western"],
    archetype: "rogue",
    gender: "female",
    tags: [
      "scout",
      "ranger",
      "duelist",
      "archer",
      "huntress",
      "bow",
      "agile",
      "cloak",
      "blade",
    ],
    r2Path: "silhouettes/character/fantasy/rogue-female.svg",
  },
  {
    id: "fantasy-paladin",
    name: "Paladin / Templar",
    category: "character",
    genres: ["fantasy", "gothic"],
    archetype: "warrior",
    gender: "neutral",
    tags: [
      "paladin",
      "templar",
      "crusader",
      "holy",
      "divine",
      "warhammer",
      "sun",
      "cleric",
      "shield",
      "order",
    ],
    r2Path: "silhouettes/character/fantasy/paladin.svg",
  },
  {
    id: "gothic-vampire-male",
    name: "Vampire Lord (M)",
    category: "character",
    genres: ["gothic", "fantasy"],
    archetype: "noble",
    gender: "male",
    tags: [
      "vampire",
      "count",
      "fangs",
      "aristocrat",
      "blood",
      "lord",
      "gothic",
      "dracula",
      "cape",
      "undead",
    ],
    r2Path: "silhouettes/character/gothic/vampire-male.svg",
  },
  {
    id: "gothic-vampire-female",
    name: "Vampire Countess (F)",
    category: "character",
    genres: ["gothic", "fantasy"],
    archetype: "noble",
    gender: "female",
    tags: [
      "vampire",
      "countess",
      "vampireess",
      "gown",
      "gothic",
      "blood",
      "aristocrat",
      "undead",
      "lady",
      "corset",
    ],
    r2Path: "silhouettes/character/gothic/vampire-female.svg",
  },
  {
    id: "gothic-inquisitor",
    name: "Inquisitor / Witch Hunter",
    category: "character",
    genres: ["gothic", "fantasy", "western"],
    archetype: "inquisitor",
    gender: "neutral",
    tags: [
      "inquisitor",
      "witchhunter",
      "hunter",
      "hat",
      "coat",
      "stake",
      "zealot",
      "fanatic",
      "church",
      "purge",
    ],
    r2Path: "silhouettes/character/gothic/inquisitor.svg",
  },
  {
    id: "scifi-scientist-alien",
    name: "Alien Scientist",
    category: "character",
    genres: ["scifi", "cosmic-horror"],
    archetype: "scientist",
    gender: "neutral",
    tags: [
      "alien",
      "scientist",
      "researcher",
      "scholar",
      "tech",
      "lab",
      "extraterrestrial",
      "doctor",
      "intellect",
    ],
    r2Path: "silhouettes/character/scifi/scientist-alien.svg",
  },
  {
    id: "scifi-pilot-explorer",
    name: "Star Pilot / Astronaut",
    category: "character",
    genres: ["scifi"],
    archetype: "pilot",
    gender: "neutral",
    tags: [
      "pilot",
      "astronaut",
      "explorer",
      "helmet",
      "spacesuit",
      "starship",
      "navigator",
      "captain",
      "scout",
    ],
    r2Path: "silhouettes/character/scifi/pilot-explorer.svg",
  },
  {
    id: "cyberpunk-hacker-female",
    name: "Netrunner / Hacker (F)",
    category: "character",
    genres: ["cyberpunk", "scifi"],
    archetype: "hacker",
    gender: "female",
    tags: [
      "hacker",
      "netrunner",
      "cyber",
      "visor",
      "jacked-in",
      "neural",
      "deck",
      "technomancer",
      "punk",
    ],
    r2Path: "silhouettes/character/cyberpunk/hacker-female.svg",
  },
  {
    id: "cyberpunk-enforcer-male",
    name: "Cyber Enforcer / Merc",
    category: "character",
    genres: ["cyberpunk", "scifi"],
    archetype: "warrior",
    gender: "male",
    tags: [
      "enforcer",
      "cyborg",
      "merc",
      "gunner",
      "armored",
      "cyberware",
      "bionic",
      "street",
      "soldier",
    ],
    r2Path: "silhouettes/character/cyberpunk/enforcer-male.svg",
  },
  {
    id: "scifi-captain-commander",
    name: "Starship Captain / Commander",
    category: "character",
    genres: ["scifi"],
    archetype: "noble",
    gender: "neutral",
    tags: [
      "captain",
      "commander",
      "officer",
      "fleet",
      "admiral",
      "starship",
      "bridge",
      "naval",
      "command",
      "skipper",
    ],
    r2Path: "silhouettes/character/scifi/captain-commander.svg",
  },
  {
    id: "scifi-marine-soldier",
    name: "Heavy Armored Marine",
    category: "character",
    genres: ["scifi"],
    archetype: "warrior",
    gender: "neutral",
    tags: [
      "marine",
      "soldier",
      "trooper",
      "armor",
      "exo-suit",
      "infantry",
      "commando",
      "heavy",
      "combat",
      "rifle",
    ],
    r2Path: "silhouettes/character/scifi/marine-soldier.svg",
  },
  {
    id: "scifi-engineer-mechanic",
    name: "Starship Engineer / Mechanic",
    category: "character",
    genres: ["scifi", "cyberpunk"],
    archetype: "scientist",
    gender: "neutral",
    tags: [
      "engineer",
      "mechanic",
      "technician",
      "welder",
      "repair",
      "jumpsuit",
      "torch",
      "tools",
      "systems",
      "maintenance",
    ],
    r2Path: "silhouettes/character/scifi/engineer-mechanic.svg",
  },
  {
    id: "scifi-field-medic",
    name: "Cyber-Medic / Field Surgeon",
    category: "character",
    genres: ["scifi", "cyberpunk"],
    archetype: "scientist",
    gender: "neutral",
    tags: [
      "medic",
      "doctor",
      "surgeon",
      "healer",
      "triage",
      "scanner",
      "clinic",
      "cyber-doc",
      "medical",
      "physician",
    ],
    r2Path: "silhouettes/character/scifi/field-medic.svg",
  },
  {
    id: "scifi-android-synth",
    name: "Synthetic Android / AI Host",
    category: "character",
    genres: ["scifi", "cyberpunk"],
    archetype: "construct",
    gender: "neutral",
    tags: [
      "android",
      "synth",
      "synthetic",
      "robot",
      "cyborg",
      "automaton",
      "artificial",
      "chassis",
      "replica",
      "golem",
    ],
    r2Path: "silhouettes/character/scifi/android-synth.svg",
  },
  {
    id: "scifi-psionic-operative",
    name: "Psionic / Biotic Operative",
    category: "character",
    genres: ["scifi"],
    archetype: "caster",
    gender: "neutral",
    tags: [
      "psionic",
      "psychic",
      "esper",
      "biotic",
      "telekinetic",
      "telepath",
      "mind",
      "mystic",
      "mentalist",
      "aura",
    ],
    r2Path: "silhouettes/character/scifi/psionic-operative.svg",
  },
  {
    id: "scifi-trader-smuggler",
    name: "Space Trader / Privateer",
    category: "character",
    genres: ["scifi", "western"],
    archetype: "outlaw",
    gender: "neutral",
    tags: [
      "trader",
      "merchant",
      "smuggler",
      "scoundrel",
      "spacer",
      "privateer",
      "rogue",
      "freighter",
      "cargo",
      "pilot",
    ],
    r2Path: "silhouettes/character/scifi/trader-smuggler.svg",
  },
  {
    id: "western-gunslinger-male",
    name: "Gunslinger (M)",
    category: "character",
    genres: ["western"],
    archetype: "outlaw",
    gender: "male",
    tags: [
      "gunslinger",
      "cowboy",
      "sheriff",
      "revolver",
      "duster",
      "western",
      "bandit",
      "bounty-hunter",
      "stetson",
      "drifter",
    ],
    r2Path: "silhouettes/character/western/gunslinger-male.svg",
  },
  {
    id: "western-outlaw-female",
    name: "Outlaw / Bounty Hunter (F)",
    category: "character",
    genres: ["western"],
    archetype: "outlaw",
    gender: "female",
    tags: [
      "outlaw",
      "cowgirl",
      "hunter",
      "bounty",
      "western",
      "revolver",
      "duster",
      "sheriff",
      "rogue",
    ],
    r2Path: "silhouettes/character/western/outlaw-female.svg",
  },
  {
    id: "character-npc-innkeeper",
    name: "Innkeeper / Barkeep",
    category: "character",
    genres: ["fantasy"],
    archetype: "generic",
    gender: "male",
    tags: [
      "innkeeper",
      "barkeep",
      "tavernkeeper",
      "host",
      "pub",
      "tavern",
      "ale",
      "flagon",
    ],
    r2Path: "silhouettes/character/fantasy/npc-innkeeper.svg",
  },
  {
    id: "character-npc-barmaid",
    name: "Tavern Server / Barmaid",
    category: "character",
    genres: ["fantasy"],
    archetype: "generic",
    gender: "female",
    tags: [
      "barmaid",
      "server",
      "wench",
      "tavern",
      "waitress",
      "inn",
      "maid",
      "alehouse",
    ],
    r2Path: "silhouettes/character/fantasy/npc-barmaid.svg",
  },
  {
    id: "character-npc-bard",
    name: "Bard / Minstrel",
    category: "character",
    genres: ["fantasy"],
    archetype: "generic",
    gender: "neutral",
    tags: [
      "bard",
      "minstrel",
      "musician",
      "troubadour",
      "poet",
      "performer",
      "lute",
      "singer",
    ],
    r2Path: "silhouettes/character/fantasy/npc-bard.svg",
  },
  {
    id: "character-npc-noble-male",
    name: "Noble Lord / Magistrate",
    category: "character",
    genres: ["fantasy"],
    archetype: "noble",
    gender: "male",
    tags: [
      "noble",
      "lord",
      "magistrate",
      "baron",
      "duke",
      "aristocrat",
      "mayor",
      "chancellor",
    ],
    r2Path: "silhouettes/character/fantasy/npc-noble-male.svg",
  },
  {
    id: "character-npc-noble-female",
    name: "Noble Lady / Aristocrat",
    category: "character",
    genres: ["fantasy"],
    archetype: "noble",
    gender: "female",
    tags: [
      "noble",
      "lady",
      "countess",
      "duchess",
      "baroness",
      "aristocrat",
      "matron",
    ],
    r2Path: "silhouettes/character/fantasy/npc-noble-female.svg",
  },
  {
    id: "character-npc-guard",
    name: "Town Guard / Sentry",
    category: "character",
    genres: ["fantasy"],
    archetype: "warrior",
    gender: "neutral",
    tags: [
      "guard",
      "sentry",
      "watchman",
      "soldier",
      "constable",
      "patrol",
      "halberdier",
      "watch",
    ],
    r2Path: "silhouettes/character/fantasy/npc-guard.svg",
  },
  {
    id: "character-npc-blacksmith",
    name: "Blacksmith / Armorer",
    category: "character",
    genres: ["fantasy"],
    archetype: "generic",
    gender: "male",
    tags: [
      "blacksmith",
      "smith",
      "armorer",
      "weaponsmith",
      "forge",
      "anvil",
      "metalworker",
    ],
    r2Path: "silhouettes/character/fantasy/npc-blacksmith.svg",
  },
  {
    id: "character-npc-merchant",
    name: "Traveling Merchant",
    category: "character",
    genres: ["fantasy"],
    archetype: "generic",
    gender: "neutral",
    tags: [
      "merchant",
      "trader",
      "peddler",
      "shopkeeper",
      "caravan",
      "dealer",
      "vendor",
    ],
    r2Path: "silhouettes/character/fantasy/npc-merchant.svg",
  },
  {
    id: "character-npc-alchemist",
    name: "Alchemist / Apothecary",
    category: "character",
    genres: ["fantasy"],
    archetype: "scientist",
    gender: "neutral",
    tags: [
      "alchemist",
      "apothecary",
      "herbalist",
      "potionmaker",
      "chemist",
      "potions",
    ],
    r2Path: "silhouettes/character/fantasy/npc-alchemist.svg",
  },
  {
    id: "character-npc-priest",
    name: "Village Priest / Friar",
    category: "character",
    genres: ["fantasy"],
    archetype: "caster",
    gender: "male",
    tags: [
      "priest",
      "friar",
      "cleric",
      "monk",
      "curate",
      "pastor",
      "preacher",
      "holy",
    ],
    r2Path: "silhouettes/character/fantasy/npc-priest.svg",
  },
  {
    id: "character-npc-scholar",
    name: "Scholar / Scribe",
    category: "character",
    genres: ["fantasy"],
    archetype: "scientist",
    gender: "neutral",
    tags: [
      "scholar",
      "scribe",
      "librarian",
      "clerk",
      "chronicler",
      "sage",
      "historian",
    ],
    r2Path: "silhouettes/character/fantasy/npc-scholar.svg",
  },
  {
    id: "character-npc-farmer",
    name: "Peasant Farmer",
    category: "character",
    genres: ["fantasy"],
    archetype: "generic",
    gender: "neutral",
    tags: [
      "farmer",
      "peasant",
      "villager",
      "commoner",
      "rustic",
      "laborer",
      "crofter",
    ],
    r2Path: "silhouettes/character/fantasy/npc-farmer.svg",
  },
  {
    id: "character-npc-urchin",
    name: "Street Urchin / Pickpocket",
    category: "character",
    genres: ["fantasy"],
    archetype: "rogue",
    gender: "neutral",
    tags: [
      "urchin",
      "pickpocket",
      "thief",
      "beggar",
      "orphan",
      "scamp",
      "streetkid",
    ],
    r2Path: "silhouettes/character/fantasy/npc-urchin.svg",
  },
  {
    id: "character-npc-elder",
    name: "Village Elder",
    category: "character",
    genres: ["fantasy"],
    archetype: "generic",
    gender: "neutral",
    tags: [
      "elder",
      "matriarch",
      "patriarch",
      "village-elder",
      "ancestor",
      "chieftain",
    ],
    r2Path: "silhouettes/character/fantasy/npc-elder.svg",
  },
  {
    id: "scifi-navigator-astrogator",
    name: "Starship Astrogator / Surveyor",
    category: "character",
    genres: ["scifi"],
    archetype: "scientist",
    gender: "neutral",
    tags: [
      "navigator",
      "astrogator",
      "surveyor",
      "astronaut",
      "cartographer",
      "explorer",
      "spacesuit",
      "charts",
      "datapad",
      "pioneer",
    ],
    r2Path: "silhouettes/character/scifi/navigator-astrogator.svg",
  },
  {
    id: "scifi-character-alien-diplomat",
    name: "Alien Diplomat / Ambassador",
    category: "character",
    genres: ["scifi"],
    archetype: "noble",
    gender: "neutral",
    tags: [
      "alien",
      "diplomat",
      "ambassador",
      "envoy",
      "treaty",
      "delegate",
      "emissary",
      "consul",
    ],
    r2Path: "silhouettes/character/scifi/alien-diplomat.svg",
  },
  {
    id: "scifi-character-frontier-marshal",
    name: "Frontier Marshal / Peacekeeper",
    category: "character",
    genres: ["scifi", "western"],
    archetype: "warrior",
    gender: "neutral",
    tags: [
      "marshal",
      "peacekeeper",
      "lawman",
      "sheriff",
      "frontier",
      "constable",
      "badge",
      "security",
    ],
    r2Path: "silhouettes/character/scifi/frontier-marshal.svg",
  },
  {
    id: "scifi-character-salvage-diver",
    name: "Salvage Diver / Wreck Runner",
    category: "character",
    genres: ["scifi"],
    archetype: "rogue",
    gender: "neutral",
    tags: [
      "salvage",
      "diver",
      "scavenger",
      "recovery",
      "wreck",
      "eva",
      "tether",
      "scrapper",
    ],
    r2Path: "silhouettes/character/scifi/salvage-diver.svg",
  },
  {
    id: "generic-humanoid-unknown",
    name: "Mysterious Wanderer",
    category: "character",
    genres: ["fantasy", "gothic", "scifi", "western", "modern"],
    archetype: "generic",
    gender: "neutral",
    tags: [
      "person",
      "human",
      "wanderer",
      "stranger",
      "unknown",
      "traveler",
      "silhouette",
      "mysterious",
    ],
    r2Path: "silhouettes/character/generic/humanoid-unknown.svg",
  },
];
