import type { SilhouetteDefinition } from "../types";

export const CREATURE_SILHOUETTES: SilhouetteDefinition[] = [
  {
    id: "creature-beast-quadruped",
    name: "Dire Beast / Wolf",
    category: "creature",
    genres: ["fantasy", "gothic"],
    archetype: "beast",
    tags: [
      "wolf",
      "beast",
      "hound",
      "predator",
      "monster",
      "direwolf",
      "fang",
      "claw",
      "creature",
      "animal",
    ],
    r2Path: "silhouettes/creature/fantasy/beast-wolf.svg",
  },
  {
    id: "creature-dragon-winged",
    name: "Dragon / Wyvern",
    category: "creature",
    genres: ["fantasy"],
    archetype: "dragon",
    tags: [
      "dragon",
      "wyvern",
      "drake",
      "reptile",
      "fire",
      "wings",
      "serpent",
      "leviathan",
      "boss",
      "legendary",
    ],
    r2Path: "silhouettes/creature/fantasy/dragon-winged.svg",
  },
  {
    id: "creature-horror-aberrant",
    name: "Eldritch Aberration",
    category: "creature",
    genres: ["cosmic-horror", "gothic"],
    archetype: "horror",
    tags: [
      "aberration",
      "eldritch",
      "tentacle",
      "horror",
      "alien",
      "cthulhu",
      "void",
      "monster",
      "mutant",
    ],
    r2Path: "silhouettes/creature/cosmic-horror/aberration.svg",
  },
  {
    id: "creature-golem-construct",
    name: "Stone Golem / Construct",
    category: "creature",
    genres: ["fantasy", "scifi"],
    archetype: "construct",
    tags: [
      "golem",
      "construct",
      "automaton",
      "mech",
      "elemental",
      "stone",
      "iron",
      "robot",
      "colossus",
    ],
    r2Path: "silhouettes/creature/fantasy/golem-construct.svg",
  },
  {
    id: "fantasy-creature-griffin",
    name: "Sylvan Griffin / Gryphon",
    category: "creature",
    genres: ["fantasy"],
    archetype: "beast",
    tags: [
      "griffin",
      "gryphon",
      "beast",
      "eagle",
      "lion",
      "wings",
      "talons",
      "avian",
      "feather",
      "mount",
      "flying",
      "mythological",
    ],
    r2Path: "silhouettes/creature/fantasy/griffin.svg",
  },
  {
    id: "fantasy-creature-hydra",
    name: "Multi-Headed Swamp Hydra",
    category: "creature",
    genres: ["fantasy", "gothic"],
    archetype: "beast",
    tags: [
      "hydra",
      "serpent",
      "monster",
      "swamp",
      "multi-headed",
      "reptile",
      "venom",
      "fangs",
      "boss",
      "regeneration",
      "dragon",
    ],
    r2Path: "silhouettes/creature/fantasy/hydra.svg",
  },
  {
    id: "fantasy-creature-stone-colossus",
    name: "Stone Colossus / Megalith Titan",
    category: "creature",
    genres: ["fantasy"],
    archetype: "construct",
    tags: [
      "golem",
      "colossus",
      "titan",
      "megalith",
      "construct",
      "elemental",
      "earth",
      "boulder",
      "stone",
      "ancient",
      "guardian",
    ],
    r2Path: "silhouettes/creature/fantasy/stone-colossus.svg",
  },
  {
    id: "scifi-creature-xenomorph",
    name: "Xeno Stalker / Alien Predator",
    category: "creature",
    genres: ["scifi", "cosmic-horror"],
    archetype: "horror",
    gender: "neutral",
    tags: [
      "xenomorph",
      "alien",
      "predator",
      "stalker",
      "carapace",
      "biomechanical",
      "monster",
      "claws",
      "tail",
      "creature",
    ],
    r2Path: "silhouettes/creature/scifi/xenomorph-predator.svg",
  },
  {
    id: "scifi-creature-swarm",
    name: "Hive Drone / Swarm Insectoid",
    category: "creature",
    genres: ["scifi"],
    archetype: "beast",
    gender: "neutral",
    tags: [
      "swarm",
      "insectoid",
      "hive",
      "drone",
      "chitin",
      "bug",
      "mandibles",
      "scythe",
      "infestation",
      "beast",
    ],
    r2Path: "silhouettes/creature/scifi/swarm-insectoid.svg",
  },
  {
    id: "scifi-construct-drone",
    name: "Security Drone / Sentry Bot",
    category: "creature",
    genres: ["scifi", "cyberpunk"],
    archetype: "construct",
    gender: "neutral",
    tags: [
      "drone",
      "sentry",
      "security",
      "bot",
      "automaton",
      "repulsor",
      "floating",
      "scanner",
      "patrol",
      "construct",
    ],
    r2Path: "silhouettes/creature/scifi/security-drone.svg",
  },
];
