import type { SilhouetteDefinition } from "../types";

export const EVENT_SILHOUETTES: SilhouetteDefinition[] = [
  {
    id: "fantasy-event-battle-war",
    name: "Great Battle / Warfare",
    category: "event",
    genres: ["fantasy", "gothic"],
    archetype: "warrior",
    tags: [
      "event",
      "battle",
      "war",
      "conflict",
      "clash",
      "siege",
      "campaign",
      "skirmish",
      "knights",
      "combat",
      "army",
      "invasion",
    ],
    r2Path: "silhouettes/event/fantasy/battle-war.svg",
  },
  {
    id: "fantasy-event-arcane-ritual",
    name: "Arcane Ritual / Conjunction",
    category: "event",
    genres: ["fantasy", "gothic", "cosmic-horror"],
    archetype: "caster",
    tags: [
      "event",
      "ritual",
      "conjunction",
      "eclipse",
      "ceremony",
      "cataclysm",
      "spellcasting",
      "megalith",
      "celestial",
      "alignment",
      "summoning",
      "magic",
    ],
    r2Path: "silhouettes/event/fantasy/arcane-ritual.svg",
  },
  {
    id: "fantasy-event-coronation-treaty",
    name: "Royal Coronation / Summit",
    category: "event",
    genres: ["fantasy", "gothic"],
    archetype: "noble",
    tags: [
      "event",
      "coronation",
      "summit",
      "treaty",
      "council",
      "crowning",
      "alliance",
      "monarch",
      "king",
      "queen",
      "parley",
      "ceremony",
      "assembly",
    ],
    r2Path: "silhouettes/event/fantasy/coronation-treaty.svg",
  },
  {
    id: "fantasy-event-cataclysm-ruin",
    name: "Cataclysm / Falling Ruin",
    category: "event",
    genres: ["fantasy", "gothic", "cosmic-horror"],
    archetype: "structure",
    tags: [
      "event",
      "cataclysm",
      "disaster",
      "destruction",
      "ruin",
      "meteor",
      "comet",
      "collapse",
      "lightning",
      "earthquake",
      "apocalypse",
      "fall",
    ],
    r2Path: "silhouettes/event/fantasy/cataclysm-ruin.svg",
  },
  {
    id: "fantasy-event-festival-tournament",
    name: "Grand Festival / Tournament",
    category: "event",
    genres: ["fantasy"],
    archetype: "generic",
    tags: [
      "event",
      "festival",
      "tournament",
      "joust",
      "carnival",
      "celebration",
      "fair",
      "feast",
      "games",
      "melee",
      "parade",
      "solstice",
    ],
    r2Path: "silhouettes/event/fantasy/festival-tournament.svg",
  },
  {
    id: "scifi-event-hyperspace-arrival",
    name: "Hyperspace Arrival / Jump Transit",
    category: "event",
    genres: ["scifi"],
    archetype: "pilot",
    tags: [
      "hyperspace",
      "arrival",
      "jump",
      "transit",
      "warp",
      "starship",
      "emergence",
      "gate",
    ],
    r2Path: "silhouettes/event/scifi/hyperspace-arrival.svg",
  },
  {
    id: "scifi-event-solar-storm",
    name: "Solar Storm / Stellar Flare",
    category: "event",
    genres: ["scifi"],
    archetype: "generic",
    tags: [
      "solar",
      "storm",
      "flare",
      "sun",
      "radiation",
      "eclipse",
      "space-weather",
      "disaster",
    ],
    r2Path: "silhouettes/event/scifi/solar-storm.svg",
  },
  {
    id: "scifi-event-first-contact",
    name: "First Contact / Alien Summit",
    category: "event",
    genres: ["scifi"],
    archetype: "noble",
    tags: [
      "first-contact",
      "contact",
      "summit",
      "alien",
      "diplomacy",
      "meeting",
      "treaty",
      "encounter",
    ],
    r2Path: "silhouettes/event/scifi/first-contact.svg",
  },
];
