import type { SilhouetteDefinition } from "../types";

export const FACTION_SILHOUETTES: SilhouetteDefinition[] = [
  {
    id: "faction-insignia-crest",
    name: "Noble Crest / Guild",
    category: "faction",
    genres: ["fantasy", "gothic"],
    archetype: "insignia",
    tags: [
      "faction",
      "crest",
      "shield",
      "guild",
      "noble",
      "house",
      "order",
      "kingdom",
      "heraldry",
      "clan",
    ],
    r2Path: "silhouettes/faction/fantasy/heraldic-crest.svg",
  },
  {
    id: "faction-insignia-cyber",
    name: "Cyber Syndicate Hex",
    category: "faction",
    genres: ["cyberpunk", "scifi"],
    archetype: "insignia",
    tags: [
      "syndicate",
      "corp",
      "megacorp",
      "faction",
      "cyber",
      "emblem",
      "insignia",
      "tech",
      "network",
      "cyberpunk",
    ],
    r2Path: "silhouettes/faction/cyberpunk/cyber-hex.svg",
  },
  {
    id: "fantasy-faction-martial-order",
    name: "Martial Knight Order",
    category: "faction",
    genres: ["fantasy", "gothic"],
    archetype: "insignia",
    tags: [
      "faction",
      "order",
      "knight",
      "martial",
      "swords",
      "shield",
      "crusade",
      "brotherhood",
      "templar",
      "paladin",
      "militia",
      "army",
      "regiment",
      "crest",
      "heraldry",
    ],
    r2Path: "silhouettes/faction/fantasy/martial-order.svg",
  },
  {
    id: "fantasy-faction-arcane-circle",
    name: "Arcane Wizard Circle",
    category: "faction",
    genres: ["fantasy"],
    archetype: "insignia",
    tags: [
      "faction",
      "guild",
      "circle",
      "arcane",
      "wizard",
      "mage",
      "college",
      "academy",
      "conclave",
      "coven",
      "eye",
      "celestial",
      "runes",
      "astrology",
    ],
    r2Path: "silhouettes/faction/fantasy/arcane-circle.svg",
  },
  {
    id: "fantasy-faction-thieves-guild",
    name: "Shadow Thieves Guild",
    category: "faction",
    genres: ["fantasy", "gothic"],
    archetype: "insignia",
    tags: [
      "faction",
      "guild",
      "syndicate",
      "thieves",
      "rogue",
      "shadow",
      "underworld",
      "lockpick",
      "key",
      "raven",
      "skull",
      "assassin",
      "black-market",
    ],
    r2Path: "silhouettes/faction/fantasy/thieves-guild.svg",
  },
  {
    id: "fantasy-faction-merchant-league",
    name: "Merchant Trade League",
    category: "faction",
    genres: ["fantasy"],
    archetype: "insignia",
    tags: [
      "faction",
      "guild",
      "merchant",
      "trade",
      "league",
      "consortium",
      "scales",
      "coin",
      "gold",
      "commerce",
      "caravan",
      "galleon",
      "bank",
    ],
    r2Path: "silhouettes/faction/fantasy/merchant-league.svg",
  },
  {
    id: "fantasy-faction-holy-order",
    name: "Sacred Holy Order / Inquisition",
    category: "faction",
    genres: ["fantasy", "gothic"],
    archetype: "insignia",
    tags: [
      "faction",
      "order",
      "church",
      "temple",
      "holy",
      "inquisition",
      "sunburst",
      "chalice",
      "flaming-sword",
      "divine",
      "cleric",
      "faith",
      "crusade",
    ],
    r2Path: "silhouettes/faction/fantasy/holy-order.svg",
  },
  {
    id: "scifi-faction-stellar-republic",
    name: "Stellar Republic / Galactic Union",
    category: "faction",
    genres: ["scifi"],
    archetype: "insignia",
    tags: [
      "republic",
      "union",
      "federation",
      "senate",
      "civic",
      "galactic",
      "government",
      "stellar",
    ],
    r2Path: "silhouettes/faction/scifi/stellar-republic.svg",
  },
  {
    id: "scifi-faction-mining-consortium",
    name: "Mining Consortium / Asteroid Guild",
    category: "faction",
    genres: ["scifi", "cyberpunk"],
    archetype: "insignia",
    tags: [
      "mining",
      "consortium",
      "asteroid",
      "guild",
      "extractor",
      "industrial",
      "corporation",
      "drill",
    ],
    r2Path: "silhouettes/faction/scifi/mining-consortium.svg",
  },
  {
    id: "scifi-faction-alien-hive",
    name: "Alien Hive / Swarm Collective",
    category: "faction",
    genres: ["scifi", "cosmic-horror"],
    archetype: "insignia",
    tags: [
      "alien",
      "hive",
      "swarm",
      "collective",
      "brood",
      "xeno",
      "organism",
      "tendrils",
    ],
    r2Path: "silhouettes/faction/scifi/alien-hive.svg",
  },
];
