import type { SilhouetteDefinition } from "../types";

export const ITEM_SILHOUETTES: SilhouetteDefinition[] = [
  {
    id: "item-relic-blade",
    name: "Relic Blade / Sword",
    category: "item",
    genres: ["fantasy", "gothic"],
    archetype: "relic",
    tags: [
      "sword",
      "blade",
      "relic",
      "weapon",
      "artifact",
      "holy",
      "excalibur",
      "dagger",
      "magic-item",
    ],
    r2Path: "silhouettes/item/fantasy/relic-blade.svg",
  },
  {
    id: "item-arcane-tome",
    name: "Arcane Tome / Grimoire",
    category: "item",
    genres: ["fantasy", "gothic"],
    archetype: "relic",
    tags: [
      "book",
      "tome",
      "grimoire",
      "scroll",
      "spells",
      "magic",
      "arcane",
      "library",
      "lore",
      "journal",
    ],
    r2Path: "silhouettes/item/fantasy/arcane-tome.svg",
  },
  {
    id: "fantasy-item-heraldic-shield",
    name: "Heraldic Shield / Buckler",
    category: "item",
    genres: ["fantasy"],
    archetype: "relic",
    tags: [
      "shield",
      "buckler",
      "heraldry",
      "crest",
      "defence",
      "armor",
      "knight",
      "guardian",
    ],
    r2Path: "silhouettes/item/fantasy/heraldic-shield.svg",
  },
  {
    id: "fantasy-item-alchemist-potion",
    name: "Alchemist's Potion / Elixir",
    category: "item",
    genres: ["fantasy"],
    archetype: "relic",
    tags: [
      "potion",
      "elixir",
      "vial",
      "flask",
      "draught",
      "healing",
      "alchemy",
      "consumable",
    ],
    r2Path: "silhouettes/item/fantasy/alchemist-potion.svg",
  },
  {
    id: "fantasy-item-royal-crown",
    name: "Royal Crown / Regalia",
    category: "item",
    genres: ["fantasy"],
    archetype: "relic",
    tags: [
      "crown",
      "regalia",
      "royal",
      "king",
      "queen",
      "coronation",
      "throne",
      "sovereign",
    ],
    r2Path: "silhouettes/item/fantasy/royal-crown.svg",
  },
  {
    id: "fantasy-item-ancient-key",
    name: "Ancient Key / Keyring",
    category: "item",
    genres: ["fantasy", "gothic"],
    archetype: "relic",
    tags: [
      "key",
      "keyring",
      "lock",
      "locked",
      "door",
      "vault",
      "ancient",
      "warded",
    ],
    r2Path: "silhouettes/item/fantasy/ancient-key.svg",
  },
  {
    id: "scifi-ship-fighter",
    name: "Starfighter / Interceptor",
    category: "item",
    genres: ["scifi"],
    archetype: "construct",
    gender: "neutral",
    tags: [
      "starfighter",
      "fighter",
      "interceptor",
      "cockpit",
      "spaceship",
      "pilot",
      "dogfight",
      "delta",
      "combat",
      "wing",
    ],
    r2Path: "silhouettes/item/scifi/ship-fighter.svg",
  },
  {
    id: "scifi-vehicle-mech",
    name: "Combat Mech / Battle Walker",
    category: "item",
    genres: ["scifi", "cyberpunk"],
    archetype: "construct",
    gender: "neutral",
    tags: [
      "mech",
      "mecha",
      "walker",
      "bipedal",
      "chassis",
      "robot",
      "exoskeleton",
      "warrior",
      "cannon",
      "armor",
    ],
    r2Path: "silhouettes/item/scifi/vehicle-mech.svg",
  },
  {
    id: "scifi-vehicle-rover",
    name: "Planetary Rover / Surface Buggy",
    category: "item",
    genres: ["scifi"],
    archetype: "construct",
    gender: "neutral",
    tags: [
      "rover",
      "buggy",
      "vehicle",
      "crawler",
      "all-terrain",
      "exploration",
      "planetary",
      "wheels",
      "surface",
      "expedition",
    ],
    r2Path: "silhouettes/item/scifi/vehicle-rover.svg",
  },
  {
    id: "scifi-item-energy-blade",
    name: "Plasma / Energy Blade",
    category: "item",
    genres: ["scifi", "cyberpunk"],
    archetype: "relic",
    gender: "neutral",
    tags: [
      "plasma",
      "energy-sword",
      "lightsaber",
      "blade",
      "sword",
      "weapon",
      "beam",
      "laser",
      "hilt",
      "emitter",
    ],
    r2Path: "silhouettes/item/scifi/energy-blade.svg",
  },
  {
    id: "scifi-item-plasma-cell",
    name: "Plasma Power Cell / Energy Canister",
    category: "item",
    genres: ["scifi", "cyberpunk"],
    archetype: "generic",
    tags: [
      "plasma",
      "power",
      "cell",
      "battery",
      "reactor",
      "fuel",
      "canister",
      "capacitor",
    ],
    r2Path: "silhouettes/item/scifi/plasma-cell.svg",
  },
  {
    id: "scifi-item-datapad",
    name: "Datapad / Holo Tablet",
    category: "item",
    genres: ["scifi", "cyberpunk"],
    archetype: "generic",
    tags: [
      "datapad",
      "tablet",
      "terminal",
      "console",
      "data",
      "log",
      "hologram",
      "device",
    ],
    r2Path: "silhouettes/item/scifi/datapad.svg",
  },
  {
    id: "scifi-item-explorer-helmet",
    name: "Explorer Helmet / EVA Suit",
    category: "item",
    genres: ["scifi"],
    archetype: "generic",
    tags: [
      "helmet",
      "spacesuit",
      "eva",
      "suit",
      "visor",
      "explorer",
      "pressure",
      "environmental",
    ],
    r2Path: "silhouettes/item/scifi/explorer-helmet.svg",
  },
  {
    id: "scifi-item-alien-relic",
    name: "Alien Relic / Precursor Artifact",
    category: "item",
    genres: ["scifi", "cosmic-horror"],
    archetype: "relic",
    tags: [
      "alien",
      "relic",
      "artifact",
      "precursor",
      "xeno",
      "ancient",
      "monolith",
      "anomalous",
    ],
    r2Path: "silhouettes/item/scifi/alien-relic.svg",
  },
];
