import type { SilhouetteDefinition } from "../types";

export const LOCATION_SILHOUETTES: SilhouetteDefinition[] = [
  {
    id: "location-citadel-castle",
    name: "Citadel / Castle",
    category: "location",
    genres: ["fantasy", "gothic"],
    archetype: "structure",
    tags: [
      "castle",
      "citadel",
      "fortress",
      "keep",
      "tower",
      "city",
      "palace",
      "stronghold",
      "kingdom",
    ],
    r2Path: "silhouettes/location/fantasy/citadel-castle.svg",
  },
  {
    id: "fantasy-location-kingdom",
    name: "Kingdom / Realm",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "kingdom",
      "realm",
      "domain",
      "empire",
      "monarchy",
      "crown-land",
      "principality",
      "territory",
      "throne",
    ],
    r2Path: "silhouettes/location/fantasy/kingdom.svg",
  },
  {
    id: "fantasy-location-province",
    name: "Province / Regional Domain",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "province",
      "region",
      "shire",
      "county",
      "fiefdom",
      "duchy",
      "barony",
      "district",
      "lands",
      "territory",
    ],
    r2Path: "silhouettes/location/fantasy/province.svg",
  },
  {
    id: "location-scifi-megacity",
    name: "Sci-Fi Megacity",
    category: "location",
    genres: ["scifi", "cyberpunk"],
    archetype: "structure",
    tags: [
      "city",
      "metropolis",
      "megacity",
      "cyberpunk",
      "spire",
      "skyline",
      "arcology",
      "station",
      "scifi",
    ],
    r2Path: "silhouettes/location/scifi/megacity-skyline.svg",
  },
  {
    id: "location-fantasy-village",
    name: "Fantasy Village",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "village",
      "hamlet",
      "cottage",
      "settlement",
      "rural",
      "countryside",
      "farm",
      "medieval",
    ],
    r2Path: "silhouettes/location/fantasy/village.svg",
  },
  {
    id: "location-fantasy-town",
    name: "Fortified Town",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "town",
      "borough",
      "city",
      "walled-town",
      "settlement",
      "capital",
      "medieval",
    ],
    r2Path: "silhouettes/location/fantasy/town.svg",
  },
  {
    id: "location-inn-tavern",
    name: "Inn & Tavern",
    category: "location",
    genres: ["fantasy", "western"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "inn",
      "tavern",
      "pub",
      "alehouse",
      "saloon",
      "bar",
      "drinking",
      "lodging",
      "medieval",
    ],
    r2Path: "silhouettes/location/fantasy/inn-tavern.svg",
  },
  {
    id: "location-wizard-tower",
    name: "Wizard Tower / Spire",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "tower",
      "spire",
      "observatory",
      "wizard-tower",
      "arcane-spire",
      "high-tower",
    ],
    r2Path: "silhouettes/location/fantasy/wizard-tower.svg",
  },
  {
    id: "location-dungeon-crypt",
    name: "Dungeon & Crypt",
    category: "location",
    genres: ["fantasy", "gothic", "cosmic-horror"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "dungeon",
      "crypt",
      "catacomb",
      "tomb",
      "underdark",
      "vault",
      "lair",
      "ruins",
      "horror",
    ],
    r2Path: "silhouettes/location/fantasy/dungeon-crypt.svg",
  },
  {
    id: "location-port-harbor",
    name: "Port & Harbor",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "port",
      "harbor",
      "dock",
      "docks",
      "pier",
      "quay",
      "wharf",
      "marina",
      "bay",
      "pirate",
      "nautical",
    ],
    r2Path: "silhouettes/location/fantasy/port-harbor.svg",
  },
  {
    id: "fantasy-location-sailing-ship",
    name: "Sailing Ship / Galleon",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "ship",
      "sailing-ship",
      "galleon",
      "caravel",
      "vessel",
      "flagship",
      "frigate",
      "boat",
      "brigantine",
      "warship",
      "naval",
    ],
    r2Path: "silhouettes/location/fantasy/sailing-ship.svg",
  },
  {
    id: "location-temple-shrine",
    name: "Temple & Shrine",
    category: "location",
    genres: ["fantasy", "gothic"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "temple",
      "shrine",
      "sanctuary",
      "cathedral",
      "monastery",
      "chapel",
      "altar",
      "mythology",
    ],
    r2Path: "silhouettes/location/fantasy/temple-shrine.svg",
  },
  {
    id: "location-market-square",
    name: "Market Square / Bazaar",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "market",
      "bazaar",
      "square",
      "stalls",
      "plaza",
      "marketplace",
      "commerce",
      "traders",
      "merchants",
      "fountain",
    ],
    r2Path: "silhouettes/location/fantasy/market-square.svg",
  },
  {
    id: "location-blacksmith-forge",
    name: "Blacksmith Forge & Armory",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "forge",
      "blacksmith",
      "armory",
      "smithy",
      "anvil",
      "weaponsmith",
      "furnace",
      "hearth",
      "metalwork",
    ],
    r2Path: "silhouettes/location/fantasy/blacksmith-forge.svg",
  },
  {
    id: "location-city-gate",
    name: "City Gate & Portcullis",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "gate",
      "city-gate",
      "portcullis",
      "drawbridge",
      "gatehouse",
      "ramparts",
      "walls",
      "entrance",
      "checkpoint",
      "fortified",
    ],
    r2Path: "silhouettes/location/fantasy/city-gate.svg",
  },
  {
    id: "location-guardhouse-jail",
    name: "Guardhouse & Jail",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "guardhouse",
      "jail",
      "prison",
      "dungeon",
      "watchpost",
      "barracks",
      "cells",
      "constabulary",
      "stocks",
      "pillory",
    ],
    r2Path: "silhouettes/location/fantasy/guardhouse-jail.svg",
  },
  {
    id: "location-town-hall",
    name: "Town Hall / Guildhall",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "townhall",
      "guildhall",
      "civic",
      "city-hall",
      "manor",
      "court",
      "council",
      "chancery",
      "assembly",
      "clocktower",
    ],
    r2Path: "silhouettes/location/fantasy/town-hall.svg",
  },
  {
    id: "location-slums-alley",
    name: "Thieves' Alley / Slums",
    category: "location",
    genres: ["fantasy", "gothic"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "alley",
      "slums",
      "thieves",
      "tenements",
      "gutters",
      "underworld",
      "shanties",
      "backstreet",
      "dark-alley",
    ],
    r2Path: "silhouettes/location/fantasy/slums-alley.svg",
  },
  {
    id: "location-river-bridge",
    name: "Stone River Bridge",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "bridge",
      "river",
      "crossing",
      "tollhouse",
      "stone-bridge",
      "waterway",
      "causeway",
      "aqueduct",
      "span",
    ],
    r2Path: "silhouettes/location/fantasy/river-bridge.svg",
  },
  {
    id: "location-windmill",
    name: "Windmill & Granary",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "windmill",
      "mill",
      "granary",
      "silo",
      "grindstone",
      "flour-mill",
      "farm",
      "countryside",
      "rural",
      "harvest",
    ],
    r2Path: "silhouettes/location/fantasy/windmill.svg",
  },
  {
    id: "location-apothecary-shop",
    name: "Apothecary & Herb Shop",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "apothecary",
      "alchemist-shop",
      "potions",
      "herbs",
      "healer",
      "pharmacy",
      "elixirs",
      "tinctures",
    ],
    r2Path: "silhouettes/location/fantasy/apothecary-shop.svg",
  },
  {
    id: "location-noble-manor",
    name: "Noble Manor & Estate",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "manor",
      "estate",
      "villa",
      "mansion",
      "palace",
      "chateau",
      "noble-house",
      "courtyard",
      "grounds",
    ],
    r2Path: "silhouettes/location/fantasy/noble-manor.svg",
  },
  {
    id: "location-fighting-arena",
    name: "Arena & Fighting Pit",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "arena",
      "colosseum",
      "amphitheater",
      "fighting-pit",
      "dueling-ground",
      "stands",
      "gladiator",
      "stadium",
    ],
    r2Path: "silhouettes/location/fantasy/fighting-arena.svg",
  },
  {
    id: "location-grand-library",
    name: "Grand Archives & Library",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "library",
      "archives",
      "scriptorium",
      "books",
      "scrolls",
      "tomes",
      "records",
      "athenaeum",
      "knowledge",
    ],
    r2Path: "silhouettes/location/fantasy/grand-library.svg",
  },
  {
    id: "location-bathhouse",
    name: "Bathhouse & Thermal Springs",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "bathhouse",
      "baths",
      "thermae",
      "spa",
      "steam",
      "pool",
      "hot-springs",
      "springs",
      "relaxation",
    ],
    r2Path: "silhouettes/location/fantasy/bathhouse.svg",
  },
  {
    id: "location-city-sewers",
    name: "City Sewers & Undercity",
    category: "location",
    genres: ["fantasy", "gothic"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "sewers",
      "undercity",
      "subterranean",
      "drains",
      "culvert",
      "tunnels",
      "sluice",
      "canals",
      "underground-city",
    ],
    r2Path: "silhouettes/location/fantasy/city-sewers.svg",
  },
  {
    id: "location-waterfront-docks",
    name: "Waterfront Docks",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "docks",
      "pier",
      "wharf",
      "quay",
      "waterfront",
      "fishery",
      "boardwalk",
      "shipyard",
      "marina",
    ],
    r2Path: "silhouettes/location/fantasy/waterfront-docks.svg",
  },
  {
    id: "location-churchyard-cemetery",
    name: "Churchyard & Parish Chapel",
    category: "location",
    genres: ["fantasy", "gothic"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "churchyard",
      "chapel",
      "parish",
      "cemetery",
      "graves",
      "church",
      "belfry",
      "sanctuary",
    ],
    r2Path: "silhouettes/location/fantasy/churchyard-cemetery.svg",
  },
  {
    id: "location-ancient-ruins",
    name: "Ancient Ruins & Fortress",
    category: "location",
    genres: ["fantasy", "gothic"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "ruins",
      "ancient-ruins",
      "fallen-kingdom",
      "monoliths",
      "crumbled-walls",
      "pillars",
      "relics",
      "forgotten",
    ],
    r2Path: "silhouettes/location/fantasy/ancient-ruins.svg",
  },
  {
    id: "location-enchanted-forest",
    name: "Enchanted Forest",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "forest",
      "woods",
      "enchanted-forest",
      "grove",
      "canopy",
      "ancient-trees",
      "mushrooms",
      "woodland",
      "sylvan",
    ],
    r2Path: "silhouettes/location/fantasy/enchanted-forest.svg",
  },
  {
    id: "location-cavern-cave",
    name: "Subterranean Cavern & Cave",
    category: "location",
    genres: ["fantasy", "cosmic-horror"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "cavern",
      "cave",
      "grotto",
      "subterranean",
      "stalactites",
      "stalagmites",
      "underdark",
      "chasm",
      "hollow",
    ],
    r2Path: "silhouettes/location/fantasy/cavern-cave.svg",
  },
  {
    id: "location-mountain-peak",
    name: "Mountain Peak & Eyrie",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "mountain",
      "peak",
      "cliffs",
      "crags",
      "precipice",
      "ridge",
      "highland",
      "summit",
      "eyrie",
      "pass",
    ],
    r2Path: "silhouettes/location/fantasy/mountain-peak.svg",
  },
  {
    id: "location-swamp-bog",
    name: "Murky Swamp & Bog",
    category: "location",
    genres: ["fantasy", "gothic"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "swamp",
      "bog",
      "marsh",
      "wetlands",
      "mire",
      "quagmire",
      "mangrove",
      "bayou",
      "fen",
    ],
    r2Path: "silhouettes/location/fantasy/swamp-bog.svg",
  },
  {
    id: "location-mage-academy",
    name: "Mage Academy & Observatory",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "academy",
      "university",
      "observatory",
      "astrology",
      "mage-tower",
      "arcane-college",
      "spires",
      "sanctum",
    ],
    r2Path: "silhouettes/location/fantasy/mage-academy.svg",
  },
  {
    id: "location-graveyard-necropolis",
    name: "Haunted Graveyard & Necropolis",
    category: "location",
    genres: ["gothic", "fantasy", "cosmic-horror"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "graveyard",
      "necropolis",
      "mausoleum",
      "tombs",
      "cemetery",
      "crypts",
      "headstones",
      "undead",
      "haunted",
    ],
    r2Path: "silhouettes/location/gothic/graveyard-necropolis.svg",
  },
  {
    id: "location-desert-oasis",
    name: "Desert Oasis & Ruins",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "oasis",
      "desert",
      "dunes",
      "palms",
      "spring",
      "pyramid",
      "sandstone",
      "wasteland",
      "caravan-stop",
    ],
    r2Path: "silhouettes/location/fantasy/desert-oasis.svg",
  },
  {
    id: "location-volcano-caldera",
    name: "Volcanic Caldera & Forge",
    category: "location",
    genres: ["fantasy"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "volcano",
      "caldera",
      "lava",
      "magma",
      "infernal",
      "crater",
      "basalt",
      "chasm",
      "forge",
    ],
    r2Path: "silhouettes/location/fantasy/volcano-caldera.svg",
  },
  {
    id: "location-frontier-outpost",
    name: "Frontier Outpost & Fort",
    category: "location",
    genres: ["fantasy", "western"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "outpost",
      "fort",
      "palisade",
      "watchtower",
      "stockade",
      "frontier",
      "border-post",
      "bastion",
      "stronghold",
    ],
    r2Path: "silhouettes/location/fantasy/frontier-outpost.svg",
  },
  {
    id: "scifi-ship-freighter",
    name: "Scout Ship / Light Freighter",
    category: "location",
    genres: ["scifi", "western"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "freighter",
      "starship",
      "ship",
      "cargo",
      "vessel",
      "transport",
      "smuggler",
      "trader",
      "scout",
      "shuttle",
    ],
    r2Path: "silhouettes/location/scifi/ship-freighter.svg",
  },
  {
    id: "scifi-ship-dreadnought",
    name: "Fleet Dreadnought / Capital Warship",
    category: "location",
    genres: ["scifi"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "dreadnought",
      "battleship",
      "warship",
      "capital-ship",
      "cruiser",
      "fleet",
      "flagship",
      "destroyer",
      "carrier",
      "armored",
    ],
    r2Path: "silhouettes/location/scifi/ship-dreadnought.svg",
  },
  {
    id: "scifi-ship-dropship",
    name: "Tactical Dropship / Shuttle",
    category: "location",
    genres: ["scifi"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "dropship",
      "shuttle",
      "transport",
      "landing-craft",
      "vtol",
      "troop-carrier",
      "evac",
      "flight",
      "deployment",
      "assault",
    ],
    r2Path: "silhouettes/location/scifi/ship-dropship.svg",
  },
  {
    id: "scifi-location-space-station",
    name: "Orbital Space Station",
    category: "location",
    genres: ["scifi", "cyberpunk"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "station",
      "space-station",
      "orbital",
      "outpost",
      "dock",
      "torus",
      "ring",
      "habitat",
      "satellite",
      "colony",
    ],
    r2Path: "silhouettes/location/scifi/space-station.svg",
  },
  {
    id: "scifi-location-asteroid-base",
    name: "Asteroid Mining Outpost",
    category: "location",
    genres: ["scifi"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "asteroid",
      "mining",
      "outpost",
      "quarry",
      "ore",
      "rock",
      "excavation",
      "refinery",
      "mineral",
      "belter",
    ],
    r2Path: "silhouettes/location/scifi/asteroid-base.svg",
  },
  {
    id: "scifi-location-colony-dome",
    name: "Planetary Colony Biodome",
    category: "location",
    genres: ["scifi"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "biodome",
      "dome",
      "colony",
      "settlement",
      "biosphere",
      "habitat",
      "greenhouse",
      "planetary",
      "arcology",
      "city",
    ],
    r2Path: "silhouettes/location/scifi/colony-dome.svg",
  },
  {
    id: "scifi-location-derelict-hulk",
    name: "Derelict Space Hulk / Starship Wreck",
    category: "location",
    genres: ["scifi", "cosmic-horror"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "derelict",
      "wreck",
      "wreckage",
      "hulk",
      "abandoned",
      "ghost-ship",
      "ruin",
      "debris",
      "salvage",
      "space-hulk",
    ],
    r2Path: "silhouettes/location/scifi/derelict-hulk.svg",
  },
  {
    id: "scifi-location-starport-bay",
    name: "Starport / Hangar Docking Bay",
    category: "location",
    genres: ["scifi", "cyberpunk"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "starport",
      "hangar",
      "docking-bay",
      "bay",
      "landing-bay",
      "airlock",
      "dock",
      "terminal",
      "runway",
      "gantry",
    ],
    r2Path: "silhouettes/location/scifi/starport-bay.svg",
  },
  {
    id: "scifi-location-stasis-chamber",
    name: "Cryo-Stasis Chamber / Pods",
    category: "location",
    genres: ["scifi", "cyberpunk", "cosmic-horror"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "stasis",
      "cryo",
      "cryo-pod",
      "hibernation",
      "sleep",
      "capsule",
      "chamber",
      "laboratory",
      "medical",
      "vault",
    ],
    r2Path: "silhouettes/location/scifi/stasis-chamber.svg",
  },
  {
    id: "scifi-location-reactor-core",
    name: "Fusion / Warp Reactor Core",
    category: "location",
    genres: ["scifi", "cyberpunk"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "reactor",
      "core",
      "fusion",
      "warp-core",
      "power-plant",
      "generator",
      "plasma",
      "engineering",
      "containment",
      "conduit",
    ],
    r2Path: "silhouettes/location/scifi/reactor-core.svg",
  },
  {
    id: "scifi-location-jump-gate",
    name: "Hyperspace Jump Gate",
    category: "location",
    genres: ["scifi"],
    archetype: "structure",
    gender: "neutral",
    tags: [
      "jumpgate",
      "gate",
      "portal",
      "hyperspace",
      "warp",
      "ring",
      "transit",
      "star-gate",
      "station",
      "accelerator",
    ],
    r2Path: "silhouettes/location/scifi/jump-gate.svg",
  },
  {
    id: "scifi-location-desert-colony",
    name: "Desert Colony / Dome Settlement",
    category: "location",
    genres: ["scifi"],
    archetype: "structure",
    tags: [
      "desert",
      "colony",
      "dome",
      "settlement",
      "outpost",
      "moon",
      "planet",
      "habitat",
    ],
    r2Path: "silhouettes/location/scifi/desert-colony.svg",
  },
  {
    id: "scifi-location-alien-ruins",
    name: "Alien Ruins / Portal Monoliths",
    category: "location",
    genres: ["scifi", "cosmic-horror"],
    archetype: "structure",
    tags: [
      "alien",
      "ruins",
      "portal",
      "monolith",
      "precursor",
      "temple",
      "ancient",
      "artifact",
    ],
    r2Path: "silhouettes/location/scifi/alien-ruins.svg",
  },
  {
    id: "scifi-location-terraforming-facility",
    name: "Terraforming Facility / Atmosphere Plant",
    category: "location",
    genres: ["scifi"],
    archetype: "structure",
    tags: [
      "terraforming",
      "facility",
      "atmosphere",
      "plant",
      "processing",
      "refinery",
      "climate",
      "industrial",
    ],
    r2Path: "silhouettes/location/scifi/terraforming-facility.svg",
  },
];
