import type { SilhouetteDefinition } from "../types";

export const NOTE_SILHOUETTES: SilhouetteDefinition[] = [
  {
    id: "fantasy-note-sealed-letter",
    name: "Sealed Letter / Decree",
    category: "note",
    genres: ["fantasy", "gothic"],
    archetype: "generic",
    tags: [
      "letter",
      "decree",
      "message",
      "correspondence",
      "sealed",
      "wax-seal",
      "dispatch",
      "invitation",
    ],
    r2Path: "silhouettes/note/fantasy/sealed-letter.svg",
  },
  {
    id: "fantasy-note-treasure-map",
    name: "Treasure Map / Chart",
    category: "note",
    genres: ["fantasy"],
    archetype: "generic",
    tags: [
      "map",
      "chart",
      "treasure",
      "route",
      "expedition",
      "navigation",
      "coordinates",
      "parchment",
    ],
    r2Path: "silhouettes/note/fantasy/treasure-map.svg",
  },
  {
    id: "fantasy-note-quest-notice",
    name: "Quest Notice / Bounty Board",
    category: "note",
    genres: ["fantasy", "western"],
    archetype: "generic",
    tags: [
      "quest",
      "notice",
      "bounty",
      "poster",
      "proclamation",
      "contract",
      "job",
      "bulletin",
    ],
    r2Path: "silhouettes/note/fantasy/quest-notice.svg",
  },
  {
    id: "scifi-note-star-chart",
    name: "Star Chart / Navigation Map",
    category: "note",
    genres: ["scifi"],
    archetype: "generic",
    tags: [
      "star",
      "chart",
      "navigation",
      "astrogation",
      "coordinates",
      "route",
      "survey",
      "stellar",
    ],
    r2Path: "silhouettes/note/scifi/star-chart.svg",
  },
  {
    id: "scifi-note-encrypted-transmission",
    name: "Encrypted Transmission / Signal",
    category: "note",
    genres: ["scifi", "cyberpunk"],
    archetype: "generic",
    tags: [
      "transmission",
      "encrypted",
      "message",
      "signal",
      "comms",
      "communication",
      "secure",
      "intercept",
    ],
    r2Path: "silhouettes/note/scifi/encrypted-transmission.svg",
  },
  {
    id: "scifi-note-mission-dossier",
    name: "Mission Dossier / Briefing",
    category: "note",
    genres: ["scifi"],
    archetype: "generic",
    tags: [
      "mission",
      "dossier",
      "briefing",
      "intel",
      "report",
      "orders",
      "assignment",
      "classified",
    ],
    r2Path: "silhouettes/note/scifi/mission-dossier.svg",
  },
];
