import { browser } from "$app/environment";
import { goto, afterNavigate } from "$app/navigation";
import { resolve } from "$app/paths";
import type { GeneratorOutput } from "$lib/services/seo/generator-engine";
import type { MarkdownSectionForCopy } from "$lib/components/seo/markdown-sections";
import {
  buildPlotTwistPremise,
  buildFactionRosterContext,
  buildRosterMemberContext,
} from "$lib/services/seo/generator-handoffs";
import { parseDevelopWorldHandoff } from "./generator-page-world-handoff";
import type { ValidSlug } from "./generator-page-meta";
import { page } from "$app/state";

export interface GeneratorHandoffState {
  questPremise: string;
  factionContext: string;
  npcContext: string;
  autoGeneratedForFactionContext: string | undefined;
}

export interface GeneratorHandoffHandlers {
  onPlotTwistFromQuest: (draft: GeneratorOutput) => void;
  onRosterFromFaction: (draft: GeneratorOutput) => void;
  onMemberAsCharacter: (
    section: MarkdownSectionForCopy,
    data: GeneratorOutput,
  ) => void;
  onApplyPendingDevelopWorld: () => void;
}

export function initializeHandoffState(
  slug: ValidSlug,
): Omit<GeneratorHandoffState, "autoGeneratedForFactionContext"> {
  const initialQuestPremise =
    browser && slug === "plot-twist-generator"
      ? (new URLSearchParams(window.location.search).get("questPremise") ?? "")
      : "";

  const initialFactionContext =
    browser && slug === "faction-roster"
      ? (new URLSearchParams(window.location.search).get("factionContext") ??
        "")
      : "";

  const initialNpcContext =
    browser && slug === "npc"
      ? (new URLSearchParams(window.location.search).get("npcContext") ?? "")
      : "";

  return {
    questPremise: initialQuestPremise,
    factionContext: initialFactionContext,
    npcContext: initialNpcContext,
  };
}

export function setupHandoffNavigation(
  getSlug: () => ValidSlug,
  state: GeneratorHandoffState,
  onStateChange: (updates: Partial<GeneratorHandoffState>) => void,
) {
  afterNavigate(({ to }) => {
    const slug = getSlug();
    const premise =
      slug === "plot-twist-generator"
        ? (to?.url.searchParams.get("questPremise") ?? "")
        : "";
    if (premise !== state.questPremise) {
      onStateChange({ questPremise: premise });
    }

    const factionContext =
      slug === "faction-roster"
        ? (to?.url.searchParams.get("factionContext") ?? "")
        : "";
    if (factionContext !== state.factionContext) {
      onStateChange({ factionContext });
    }

    const npcContext =
      slug === "npc" ? (to?.url.searchParams.get("npcContext") ?? "") : "";
    if (npcContext !== state.npcContext) {
      onStateChange({ npcContext });
    }
  });
}

export function openPlotTwistFromQuest(draft: GeneratorOutput): void {
  const params = new URLSearchParams({
    questPremise: buildPlotTwistPremise(draft),
  });
  void goto(resolve(`/generators/plot-twist-generator?${params}`));
}

export function openRosterFromFaction(draft: GeneratorOutput): void {
  const params = new URLSearchParams({
    factionContext: buildFactionRosterContext(draft),
  });
  void goto(resolve(`/generators/faction-roster?${params}`));
}

export function openMemberAsCharacter(
  section: MarkdownSectionForCopy,
  data: GeneratorOutput,
): void {
  const params = new URLSearchParams({
    npcContext: buildRosterMemberContext(section.markdown, data.title),
  });
  void goto(resolve(`/generators/npc?${params}`));
}

export function applyPendingDevelopWorld(): ReturnType<
  typeof parseDevelopWorldHandoff
> {
  const handoff = parseDevelopWorldHandoff(page.url.searchParams);
  if (!handoff) return null;

  const cleanUrl = new URL(page.url);
  for (const key of handoff.paramKeys) {
    cleanUrl.searchParams.delete(key);
  }
  goto(cleanUrl, { replaceState: true, noScroll: true, keepFocus: true });

  return handoff;
}
