<script lang="ts">
  import { onMount, untrack } from "svelte";
  import { browser } from "$app/environment";
  import { page } from "$app/state";
  import { hubContext } from "$lib/stores/hub-context.svelte";
  import { sessionHubStore } from "$lib/stores/session-hub.svelte";
  import { UI_STORAGE_KEYS, UIPersistence } from "$lib/stores/ui/persistence";
  import SEOGeneratorLayout from "./SEOGeneratorLayout.svelte";
  import GeneratorPageFormFields from "./GeneratorPageFormFields.svelte";
  import {
    npcConfig,
    npcThemeConfig,
    settlementConfig,
    magicItemConfig,
    minorMagicItemConfig,
    artifactConfig,
    factionConfig,
    factionRosterConfig,
    questConfig,
    personalityConfig,
    rumourConfig,
    encounterConfig,
    puzzleConfig,
    councilVoteConfig,
    heistConfig,
    secretSocietyConfig,
    socialHubConfig,
    kingdomConfig,
    nationConfig,
    vampireConfig,
    nomadClanConfig,
    darkFactionConfig,
    nameGeneratorConfig,
    pantheonConfig,
    shipConfig,
    languageConfig,
    newsSheetConfig,
    dungeonConfig,
    adventureConfig,
    plotTwistConfig,
    villainConfig,
    comicBookEventConfig,
    originConfig,
    villainSchemeConfig,
    worldConfig,
    starSystemConfig,
    constellationConfig,
    alienRaceConfig,
    creatureConfig,
    themeIdToLabel,
    themeToQuestGenre,
    type GeneratorOutput,
  } from "$lib/services/seo/generator-engine";
  import { loadGeneratorRemixDraft } from "./generator-page-remix";
  import {
    type SlugMetaEntry,
    type ValidSlug,
    slugMeta,
  } from "./generator-page-meta";
  import { slugDrafts } from "./generator-page-drafts";
  import {
    createGenerate,
    createGeneratorHandlers,
  } from "./generator-page-generation";
  import {
    initializeHandoffState,
    setupHandoffNavigation,
    openPlotTwistFromQuest,
    openRosterFromFaction,
    openMemberAsCharacter,
    applyPendingDevelopWorld as applyDevelopWorldHandoff,
    type GeneratorHandoffState,
  } from "./generator-page-handoffs";
  import {
    HUB_LABELS,
    SETTLEMENT_GENRE_FOR_HUB,
    SOCIAL_HUB_GENRE_TO_THEME,
    mapAlienRaceGenreToTheme,
    mapHubGenreToShipGenre,
    mapShipGenreToTheme,
    mapStarSystemGenreToTheme,
    mapWorldGenreToTheme,
    resolveHubGeneratorGenre,
    shouldSyncGeneratorTheme,
  } from "./generator-theme-maps";
  import { worldGenreForHub } from "./generator-page-world-handoff";
  import { syncGeneratorTheme } from "./generator-theme-sync";
  import { generatorShareService } from "$lib/services/sharing/GeneratorShareService";
  import {
    getHubMountPatch,
    resolveInitialActiveTheme,
    resolveSupportedHubGenre,
  } from "./generator-page-hub-state";
  import {
    createKnownGenreThemeChangeHandler,
    createMappedThemeChangeHandler,
  } from "./generator-page-form-theme";

  let {
    slug,
    urlHubTheme = undefined,
    metaOverrides = undefined,
    initialDraftOverride = undefined,
    persistence = new UIPersistence(),
  }: {
    slug: ValidSlug;
    urlHubTheme?: string;
    /**
     * Page copy that differs from the slug's own, for routes that present the
     * same generator under a different URL and pitch.
     *
     * The `/tools/*` pages each hand-wired their own state, generate call and
     * form bindings to say the same thing this component already says for
     * their slug. They now render this and pass their title, description,
     * FAQs, related links and canonical here, so the generator wiring exists
     * once while the pages keep their distinct content and URLs.
     */
    metaOverrides?: Partial<SlugMetaEntry>;
    /**
     * Replaces the slug's default initial draft (from slugDrafts) when provided.
     * Used by alternative routes that need a different default draft on first load.
     */
    initialDraftOverride?: GeneratorOutput;
    persistence?: UIPersistence;
  } = $props();

  // When arriving via a themed URL, seed hubContext immediately so derived
  // values (backHref, initialHubGenre) compute correctly on first render.
  const _initialSlug = untrack(() => slug);
  const _initialUrlHubTheme = untrack(() => urlHubTheme);
  if (_initialUrlHubTheme) {
    hubContext.set(_initialUrlHubTheme);
  }

  const backHref = $derived(
    hubContext.theme && HUB_LABELS[hubContext.theme]
      ? `/generators/${hubContext.theme}`
      : "/generators",
  );
  const backLabel = $derived(
    (hubContext.theme && HUB_LABELS[hubContext.theme]) ?? "All generators",
  );
  const initialHubGenre = resolveHubGeneratorGenre(hubContext.theme);

  const initialWorldGenre = worldGenreForHub(initialHubGenre);

  const meta = $derived({ ...slugMeta[slug], ...(metaOverrides ?? {}) });

  const _initialHandoff = initializeHandoffState(_initialSlug);
  let handoffState = $state<GeneratorHandoffState>({
    ..._initialHandoff,
    autoGeneratedForFactionContext: undefined,
  });

  let npc = $state({
    theme: factionConfig.themes[0],
    ancestry: npcThemeConfig.ancestries[factionConfig.themes[0]][0],
    role: npcThemeConfig.roles[factionConfig.themes[0]][0],
    alignment: npcThemeConfig.moralities[factionConfig.themes[0]][0].id,
    campaignContext: _initialHandoff.npcContext,
    mode: "table-card" as "dossier" | "table-card",
  });

  const settlementGenre =
    (initialHubGenre
      ? (SETTLEMENT_GENRE_FOR_HUB[initialHubGenre] ?? initialHubGenre)
      : null) ?? "Fantasy";
  const settlementSizes =
    settlementConfig.sizesByGenre[settlementGenre] ??
    settlementConfig.sizesByGenre["Fantasy"];
  let settlement = $state({
    genre: settlementGenre,
    size: settlementSizes[2].name,
    environment: (settlementConfig.environmentsByGenre[settlementGenre] ??
      settlementConfig.environmentsByGenre["Fantasy"])[0],
    primaryFunction: (settlementConfig.primaryFunctionsByGenre[
      settlementGenre
    ] ?? settlementConfig.primaryFunctionsByGenre["Fantasy"])[0],
    tone: (settlementConfig.tonesByGenre[settlementGenre] ??
      settlementConfig.tonesByGenre["Fantasy"])[0],
    mainTension: (settlementConfig.mainTensionsByGenre[settlementGenre] ??
      settlementConfig.mainTensionsByGenre["Fantasy"])[0],
    campaignContext: "",
  });

  let magicItem = $state({
    type: magicItemConfig.typesByTheme["Classic Fantasy"][0],
    rarity: magicItemConfig.rarities[1],
    campaignContext: "",
  });

  let minorMagicItem = $state({
    genre: factionConfig.themes[0],
    form: "",
    usageLimit: minorMagicItemConfig.usageLimits[0],
    utility: minorMagicItemConfig.utilities[0],
    activation: minorMagicItemConfig.activations[0],
    quirkSeverity: minorMagicItemConfig.quirkSeverities[0],
    campaignContext: "",
  });

  let artifact = $state({
    genre: factionConfig.themes[0],
    form: artifactConfig.forms[0],
    originEra: artifactConfig.originEras[0],
    powerTier: artifactConfig.powerTiers[0],
    currentStatus: artifactConfig.currentStatuses[0],
    curseCost: artifactConfig.curseCosts[0],
    campaignContext: "",
  });

  let faction = $state({
    theme: factionConfig.themes[0],
    type: factionConfig.typesByTheme["Classic Fantasy"][0],
    scope: factionConfig.scopesByTheme["Classic Fantasy"][1],
    alignment: factionConfig.alignments[0],
    campaignContext: "",
  });

  let factionRoster = $state({
    theme: factionConfig.themes[0],
    size: factionRosterConfig.sizes[1],
    structure: factionRosterConfig.structures[0],
    emphasis: factionRosterConfig.emphases[0],
    factionContext: _initialHandoff.factionContext,
    campaignContext: "",
  });

  let seoLayoutRef = $state<ReturnType<typeof SEOGeneratorLayout> | null>(null);
  let remixDraft = $state<GeneratorOutput | null>(null);

  // Drives the roster's auto-generation explicitly once handoff context
  // has actually settled, rather than have the child guess how long to wait
  // after a client-side navigation (SEOGeneratorLayout is reused across slug
  // navigations, so its own on-mount effects can fire before this page's
  // afterNavigate handler has set the handed-over context — see that
  // component's `triggerExplicitAutoGenerate` doc comment).
  $effect(() => {
    if (
      slug === "faction-roster" &&
      handoffState.factionContext &&
      handoffState.autoGeneratedForFactionContext !==
        handoffState.factionContext
    ) {
      handoffState.autoGeneratedForFactionContext = handoffState.factionContext;
      seoLayoutRef?.triggerExplicitAutoGenerate();
    }
  });

  let personality = $state({
    genre: personalityConfig.genres[0],
    roleHint: personalityConfig.roleHints[0],
    temperament: personalityConfig.temperaments[0],
    socialStyle: personalityConfig.socialStyles[0],
    moralOutlook: personalityConfig.moralOutlooks[0],
    emotionalOpenness: personalityConfig.emotionalOpenness[0],
    confidence: personalityConfig.confidenceLevels[0],
    optimism: personalityConfig.optimismSpectrum[0],
    expressiveness: personalityConfig.expressiveness[0],
    cooperationStyle: personalityConfig.cooperationStyles[0],
    ageOrLifeStage: "",
    relationshipContext: "",
    concept: "",
    campaignContext: "",
  });
  let quest = $state({
    genre: questConfig.genres[0],
    tone: questConfig.tones[0],
    scope: questConfig.scopes[0],
    locationType: questConfig.locationTypes[0],
    threat: questConfig.threats[0],
    twist: questConfig.twists[0],
    reward: questConfig.rewards[0],
    campaignContext: "",
  });
  let rumour = $state({
    genre: rumourConfig.genres[0],
    tone: rumourConfig.tones[0],
    dangerLevel: rumourConfig.dangerLevels[0],
    subjectFocus: rumourConfig.subjects[0],
    locationContext: "",
    campaignContext: "",
  });
  let encounter = $state({
    genre: factionConfig.themes[0],
    encounterType:
      encounterConfig.encounterTypes.find((t) => t !== "Random") ??
      encounterConfig.encounterTypes[0],
    environment: encounterConfig.environments[0],
    threat: encounterConfig.threats[0],
    tone: encounterConfig.tones[0],
    context: "",
  });
  let puzzle = $state({
    genre: puzzleConfig.genres[0],
    purpose: puzzleConfig.purposes[0],
    complexity: puzzleConfig.complexities[0],
    style: puzzleConfig.styles[0],
    partyLevel: "",
    playerCount: "",
    capabilities: "",
    participationStyle: puzzleConfig.participationStyles[0],
    failurePressure: puzzleConfig.failurePressures[0],
    system: puzzleConfig.systems[0],
    downstreamConsequence: "",
    campaignContext: "",
  });

  let councilVote = $state({
    genre: factionConfig.themes[0],
    proposal: "",
    governingBodyType: councilVoteConfig.bodyTypes[0],
    councilSize: councilVoteConfig.sizes[1],
    votingRule: councilVoteConfig.votingRules[0],
    deadline: "",
    scope: councilVoteConfig.scopes[0],
    tone: councilVoteConfig.tones[0],
    antagonistInfluence: councilVoteConfig.antagonistInfluences[0],
    campaignContext: "",
  });
  let heist = $state({
    genre: factionConfig.themes[0],
    heistType: heistConfig.heistTypes[0],
    targetScale: heistConfig.targetScales[1],
    targetType: heistConfig.targetTypesByTheme[factionConfig.themes[0]][0],
    prize: "",
    campaignContext: "",
  });
  let secretSociety = $state({
    theme: factionConfig.themes[0],
    tone: secretSocietyConfig.tones[0],
    scale: secretSocietyConfig.scales[0],
    publicFace: secretSocietyConfig.publicFaces[0],
    dangerLevel: secretSocietyConfig.dangers[0],
    truthRelationship: secretSocietyConfig.truths[0],
    campaignContext: "",
  });

  let tavern = $state({
    type: socialHubConfig.venueTypesByGenre["Fantasy"][0],
    atmosphere: socialHubConfig.atmospheres[0],
    settlementType: socialHubConfig.settlementTypes[1],
    wealthLevel: socialHubConfig.wealthLevels[2],
    clientele: socialHubConfig.clientelesByGenre["Fantasy"][4],
    campaignContext: "",
  });

  let kingdom = $state({
    polityType: kingdomConfig.polityTypes[0],
    governmentStyle: kingdomConfig.governmentStyles[0],
    geography: kingdomConfig.geographies[0],
    scale: kingdomConfig.scales[2],
    conflictLevel: kingdomConfig.conflictLevels[0],
    magicLevel: kingdomConfig.magicLevels[2],
    campaignContext: "",
  });

  const initialNationGenre = resolveSupportedHubGenre(
    initialHubGenre,
    nationConfig.genres,
    nationConfig.genres[0],
  );
  const initialNationPolityTypes =
    nationConfig.polityTypesByGenre[initialNationGenre] ??
    nationConfig.polityTypesByGenre[nationConfig.genres[0]];
  let nation = $state({
    genre: initialNationGenre,
    polityType: initialNationPolityTypes[0],
    governmentStyle: nationConfig.governmentStyles[0],
    scale: nationConfig.scales[2],
    conflictLevel: nationConfig.conflictLevels[0],
    campaignContext: "",
  });

  const initialSocialHubGenre = resolveSupportedHubGenre(
    initialHubGenre,
    socialHubConfig.genres,
    socialHubConfig.genres[0],
  );
  const initialSocialHubVenueTypes =
    socialHubConfig.venueTypesByGenre[initialSocialHubGenre] ??
    socialHubConfig.venueTypesByGenre[socialHubConfig.genres[0]];
  const initialSocialHubClienteles =
    socialHubConfig.clientelesByGenre[initialSocialHubGenre] ??
    socialHubConfig.clientelesByGenre[socialHubConfig.genres[0]];
  let socialHub = $state({
    genre: initialSocialHubGenre,
    venueType: initialSocialHubVenueTypes[0],
    atmosphere: socialHubConfig.atmospheres[0],
    wealthLevel: socialHubConfig.wealthLevels[2],
    clientele: initialSocialHubClienteles[0],
    campaignContext: "",
  });

  let vampireClan = $state({
    archetype: vampireConfig.archetypes[0],
    bloodline: vampireConfig.bloodlines[0],
    feedingHabit: vampireConfig.feedingHabits[0],
    weakness: vampireConfig.weaknesses[0],
    campaignContext: "",
  });

  let nomadClan = $state({
    role: nomadClanConfig.roles[0],
    tone: nomadClanConfig.tones[0],
    territory: nomadClanConfig.territories[0],
    conflict: nomadClanConfig.conflicts[0],
    campaignContext: "",
  });

  let darkFaction = $state({
    mode: darkFactionConfig.modes[0],
    factionType: darkFactionConfig.types[0],
    scope: darkFactionConfig.scopes[0],
    moralPosture: darkFactionConfig.moralPostures[0],
    campaignContext: "",
  });

  let names = $state({
    culture: nameGeneratorConfig.cultures[0],
    gender: nameGeneratorConfig.genders[0],
    nameType: nameGeneratorConfig.nameTypes[0],
    context: "",
  });

  let dndNpc = $state({
    race: npcConfig.races[0],
    role: npcConfig.roles[0],
    alignment: npcConfig.alignments[0],
    campaignContext: "",
    mode: "table-card" as "dossier" | "table-card",
  });

  let pantheon = $state({
    mode: (untrack(() => slug) === "pantheon-generator"
      ? "pantheon"
      : "single") as "single" | "pantheon",
    size: "small" as "small" | "medium" | "large",
    width: "balanced" as "balanced" | "focused" | "wide",
    genre: pantheonConfig.genres[0],
    divineType: pantheonConfig.divineTypes[0],
    domain: pantheonConfig.domains[0],
    tone: pantheonConfig.tones[0],
    worshippers: pantheonConfig.worshippers[0],
    conflictTheme: pantheonConfig.conflictThemes[0],
    campaignContext: "",
  });

  const _shipInitialGenre = initialHubGenre
    ? mapHubGenreToShipGenre(initialHubGenre)
    : "Sci-Fi";

  let ship = $state({
    genre: _shipInitialGenre,
    role: (shipConfig.rolesByGenre[_shipInitialGenre] ??
      shipConfig.rolesByGenre["Sci-Fi"])[0],
    scale: shipConfig.scales[2],
    condition: shipConfig.conditions[2],
    tone: shipConfig.tones[0],
    campaignContext: "",
  });

  let language = $state({
    genre: languageConfig.genres[0],
    tone: languageConfig.tones[0],
    role: languageConfig.roles[0],
    structure: languageConfig.structures[0],
    campaignContext: "",
  });

  const _newsSheetInitialGenre =
    initialHubGenre && newsSheetConfig.genres.includes(initialHubGenre)
      ? initialHubGenre
      : newsSheetConfig.genres[0];

  let newsSheet = $state({
    genre: _newsSheetInitialGenre,
    publicationType: (newsSheetConfig.publicationTypesByGenre[
      _newsSheetInitialGenre
    ] ?? newsSheetConfig.publicationTypesByGenre["Fantasy"])[0],
    tone: newsSheetConfig.tones[1],
    bias: newsSheetConfig.biases[0],
    censorLevel: newsSheetConfig.censorLevels[0],
    hookDensity: newsSheetConfig.hookDensities[1],
    placeName: "",
    headlineEvent: "",
    campaignContext: "",
  });

  let dungeon = $state({
    genre: factionConfig.themes[0],
    purpose: dungeonConfig.purposes[0],
    currentState: dungeonConfig.currentStates[0],
    scale: dungeonConfig.scales[1],
    campaignContext: "",
  });

  let adventure = $state({
    genre: factionConfig.themes[0],
    archetype: adventureConfig.archetypes[0],
    scale: adventureConfig.scales[1],
    tone: adventureConfig.tones[0],
    seed: "",
    campaignContext: "",
  });

  let plotTwist = $state({
    genre: factionConfig.themes[0],
    twistType: plotTwistConfig.twistTypes[0],
    impact: plotTwistConfig.impacts[1],
    timing: plotTwistConfig.timings[4],
    foreshadowing: plotTwistConfig.foreshadowing[0],
    premise: _initialHandoff.questPremise,
    constraints: "",
    campaignContext: "",
  });

  // Dynamic generator routes reuse this component during client navigation.
  // Read the URL only in the browser so static prerendering remains valid.
  setupHandoffNavigation(
    () => slug,
    handoffState,
    (updates) => {
      Object.assign(handoffState, updates);
      if (updates.questPremise !== undefined)
        plotTwist.premise = updates.questPremise;
      if (updates.factionContext !== undefined)
        factionRoster.factionContext = updates.factionContext;
      if (updates.npcContext !== undefined)
        npc.campaignContext = updates.npcContext;
    },
  );

  let villain = $state({
    genre: factionConfig.themes[0],
    tone: villainConfig.tones[0],
    threatScale: villainConfig.threatScales[0],
    archetype: villainConfig.archetypes[0],
    sympathy: villainConfig.sympathyLevels[0],
    worldRelation: villainConfig.worldRelations[0],
    campaignContext: "",
  });

  let comicBookEvent = $state({
    eventType: comicBookEventConfig.eventTypes[0],
    scale: comicBookEventConfig.scales[0],
    tone: comicBookEventConfig.tones[0],
    campaignContext: "",
  });

  // Superhero / Comic Book only, by design (#3111) — no genre field, no
  // theme-sync $effect branch below (Part C is deliberately not applicable).
  let origin = $state({
    originType: originConfig.originTypes[0],
    tone: originConfig.tones[0],
    campaignContext: "",
  });

  let villainScheme = $state({
    powerScale: villainSchemeConfig.powerScales[0],
    tone: villainSchemeConfig.tones[0],
    schemeType: villainSchemeConfig.schemeTypes[0],
    villainProfile: villainSchemeConfig.villainProfiles[0],
    campaignContext: "",
  });

  let world = $state({
    worldType: worldConfig.worldTypes[0],
    habitability: worldConfig.habitability[0],
    civilisation: worldConfig.civilisations[0],
    societalModel: worldConfig.societalModels[0],
    worldTagOne: worldConfig.defaultWorldTags[0],
    worldTagTwo: worldConfig.defaultWorldTags[1],
    genre: initialWorldGenre,
    lancerWorldFrame: worldConfig.lancerWorldFrames[0],
    campaignPressure:
      initialWorldGenre === "Lancer"
        ? worldConfig.lancerConflicts[0]
        : worldConfig.campaignPressures[0],
    dominantFeature: "",
    campaignContext: "",
  });

  let starSystem = $state<{
    systemType: string;
    genre: string;
    civilisationLevel: string;
    systemCharacter: string;
    scientificRealism: string;
    campaignContext: string;
  }>({
    systemType: starSystemConfig.systemTypes[0],
    genre: starSystemConfig.genres[0],
    civilisationLevel: starSystemConfig.civilisationLevels[0],
    systemCharacter: starSystemConfig.systemCharacters[0],
    scientificRealism: starSystemConfig.scientificRealism[0],
    campaignContext: "",
  });

  let constellation = $state<{
    mode: "single" | "night-sky";
    genre: string;
    visualImpression: string;
    practicalUse: string;
    culturalMeaning: string;
    campaignContext: string;
  }>({
    mode: "single",
    genre: constellationConfig.genres[0],
    visualImpression: constellationConfig.visualImpressions[0],
    practicalUse: constellationConfig.practicalUses[0],
    culturalMeaning: constellationConfig.culturalMeanings[0],
    campaignContext: "",
  });

  let alienRace = $state<{
    genre: string;
    generationMode: string;
    homeEnvironment: string;
    bodyPlan: string;
    psychology: string;
    socialOrganisation: string;
    technologyLevel: string;
    relationToOutsiders: string;
    campaignContext: string;
  }>({
    genre: alienRaceConfig.genres[0],
    generationMode: alienRaceConfig.generationModes[0],
    homeEnvironment: alienRaceConfig.homeEnvironments[0],
    bodyPlan: alienRaceConfig.bodyPlans[0],
    psychology: alienRaceConfig.psychologies[0],
    socialOrganisation: alienRaceConfig.socialOrganisations[0],
    technologyLevel: alienRaceConfig.technologyLevels[0],
    relationToOutsiders: alienRaceConfig.relationsToOutsiders[0],
    campaignContext: "",
  });

  let creature = $state<{
    genre: string;
    category: string;
    threatLevel: string;
    size: string;
    temperament: string;
    habitat: string;
    ecologicalRole: string;
    campaignContext: string;
  }>({
    genre: factionConfig.themes[0],
    category: creatureConfig.categories[0],
    threatLevel: creatureConfig.threatLevels[0],
    size: creatureConfig.sizes[0],
    temperament: creatureConfig.temperaments[0],
    habitat: creatureConfig.habitats[0],
    ecologicalRole: creatureConfig.ecologicalRoles[0],
    campaignContext: "",
  });

  let activeTheme = $state(
    resolveInitialActiveTheme({
      urlHubTheme: _initialUrlHubTheme,
      slug: _initialSlug,
      persistence,
      browser: Boolean(browser),
      fallbackTheme: factionConfig.themes[0],
    }),
  );
  let lastSlug = $state(_initialSlug);

  const setActiveTheme = (theme: string) => (activeTheme = theme);
  const handlePersonalityGenreChange = createKnownGenreThemeChangeHandler(
    setActiveTheme,
    personalityConfig.genres,
  );
  const handleRumourGenreChange = createKnownGenreThemeChangeHandler(
    setActiveTheme,
    rumourConfig.genres,
  );
  const handlePuzzleGenreChange = createKnownGenreThemeChangeHandler(
    setActiveTheme,
    puzzleConfig.genres,
  );
  const handleShipGenreChange = createMappedThemeChangeHandler(
    setActiveTheme,
    mapShipGenreToTheme,
  );
  const handleWorldGenreChange = createMappedThemeChangeHandler(
    setActiveTheme,
    mapWorldGenreToTheme,
  );
  const handleStarSystemGenreChange = createMappedThemeChangeHandler(
    setActiveTheme,
    mapStarSystemGenreToTheme,
  );
  const handleAlienRaceGenreChange = createMappedThemeChangeHandler(
    setActiveTheme,
    mapAlienRaceGenreToTheme,
  );
  const handleCreatureGenreChange = createMappedThemeChangeHandler(
    setActiveTheme,
    (genre) => genre,
  );

  $effect(() => {
    if (slug !== lastSlug) {
      lastSlug = slug;
      pantheon.mode = slug === "pantheon-generator" ? "pantheon" : "single";
    }
  });

  $effect(() => {
    syncGeneratorTheme({
      slug,
      activeTheme,
      setActiveTheme: (theme) => (activeTheme = theme),
      npc,
      faction,
      factionRoster,
      quest,
      personality,
      rumour,
      puzzle,
      encounter,
      councilVote,
      heist,
      secretSociety,
      socialHub,
      nation,
      pantheon,
      language,
      newsSheet,
      world,
      starSystem,
      constellation,
      alienRace,
      dungeon,
      adventure,
      plotTwist,
      villain,
      minorMagicItem,
      artifact,
      creature,
      themeToQuestGenre,
      mapSocialHubGenre: (genre) =>
        SOCIAL_HUB_GENRE_TO_THEME[genre] ?? "Classic Fantasy",
      mapWorldGenre: mapWorldGenreToTheme,
      mapStarSystemGenre: mapStarSystemGenreToTheme,
      mapAlienRaceGenre: mapAlienRaceGenreToTheme,
    });
  });

  // Consumes the "Develop this world" handoff from a generated star system
  // (#1935): a linked major body opens this page with its name, type, and
  // system context in the query string so the World Generator draft starts
  // pre-populated instead of blank. Cleans the URL after reading it.
  function applyPendingDevelopWorld(): void {
    const handoff = applyDevelopWorldHandoff();
    if (handoff) {
      world.dominantFeature = handoff.dominantFeature;
    }
  }

  onMount(() => {
    const patch = getHubMountPatch({
      slug,
      hubTheme: hubContext.theme,
      urlHubTheme,
      persistence,
      browser: Boolean(browser),
      currentState: {
        pantheonGenre: pantheon.genre,
        newsSheetGenre: newsSheet.genre,
        starSystemGenre: starSystem.genre,
        alienRaceGenre: alienRace.genre,
      },
    });

    if (patch) {
      if (patch.settlement) Object.assign(settlement, patch.settlement);
      if (patch.nation) Object.assign(nation, patch.nation);
      if (patch.socialHub) Object.assign(socialHub, patch.socialHub);
      if (patch.ship) Object.assign(ship, patch.ship);
      if (patch.world) Object.assign(world, patch.world);
      if (patch.starSystem) Object.assign(starSystem, patch.starSystem);
      if (patch.alienRace) Object.assign(alienRace, patch.alienRace);
      if (patch.newsSheet) Object.assign(newsSheet, patch.newsSheet);
      if (patch.language) Object.assign(language, patch.language);
      if (patch.activeTheme) activeTheme = patch.activeTheme;
      // World handoff is hub-patch plus query-param develop handoff.
      if (slug === "world") applyPendingDevelopWorld();
      // Language has no activeTheme change in patch when hub genre is
      // incompatible — fall back to stored theme handling below if needed.
      if (
        slug === "pantheon-generator" ||
        slug === "god-generator" ||
        slug === "vampire-clan" ||
        slug === "nomad-clan" ||
        slug === "dark-fantasy-faction" ||
        slug === "dnd-npc" ||
        slug === "fantasy-names" ||
        slug === "tavern" ||
        slug === "settlement" ||
        slug === "nation" ||
        slug === "social-hub" ||
        slug === "ship-generator" ||
        slug === "world" ||
        slug === "star-system" ||
        slug === "alien-race" ||
        slug === "news-sheet-generator"
      ) {
        return;
      }
    }

    if (slug === "language-generator" && patch?.language) {
      return;
    }

    // Flat URL without a specific hub patch: re-check stored theme for
    // quest/npc/faction style generators (urlHubTheme already seeded above).
    if (!urlHubTheme) {
      // patch already applied stored theme for generic slugs; for
      // language-generator without a valid hub mapping we still honour it.
      if (!patch?.activeTheme) {
        const stored = persistence.read(
          UI_STORAGE_KEYS.ACTIVE_THEME,
          (v) => v,
          null,
        );
        if (stored && themeIdToLabel[stored]) {
          activeTheme = themeIdToLabel[stored];
        }
      }
    }
  });

  let remixLoadVersion = 0;

  $effect(() => {
    const remixId = page.url.searchParams.get("remix");
    const targetPath = meta.canonicalPath;
    const loadVersion = ++remixLoadVersion;
    remixDraft = null;
    if (!browser || !remixId) return;
    void loadRemixDraft(remixId, targetPath, loadVersion);
  });

  async function loadRemixDraft(
    remixId: string,
    targetPath: string | undefined,
    loadVersion: number,
  ) {
    const result = await loadGeneratorRemixDraft({
      remixId,
      targetPath,
      loadVersion,
      getCurrentLoadVersion: () => remixLoadVersion,
      getShared: (id) => generatorShareService.get(id),
    });
    if (result) {
      remixDraft = result.draft;
      if (result.theme) activeTheme = result.theme;
      window.history.replaceState({}, "", window.location.pathname);
    }
  }

  const GENERATE_HANDLERS = createGeneratorHandlers({
    npc,
    settlement,
    magicItem,
    minorMagicItem,
    artifact,
    faction,
    factionRoster,
    quest,
    personality,
    rumour,
    encounter,
    puzzle,
    councilVote,
    heist,
    secretSociety,
    tavern,
    kingdom,
    nation,
    socialHub,
    vampireClan,
    nomadClan,
    darkFaction,
    names,
    dndNpc,
    pantheon,
    ship,
    language,
    newsSheet,
    dungeon,
    adventure,
    plotTwist,
    villain,
    comicBookEvent,
    origin,
    villainScheme,
    world,
    starSystem,
    constellation,
    alienRace,
    creature,
    getActiveTheme: () => activeTheme,
    getPlotTwistPremise: () => plotTwist.premise,
    getHandoffQuestPremise: () => handoffState.questPremise,
    getSessionEntities: () => sessionHubStore.entities,
  });

  const generate = createGenerate({
    getSlug: () => slug,
    getHandlers: () => GENERATE_HANDLERS,
  });

  const initialDraft = $derived(
    remixDraft ??
      ((handoffState.questPremise && slug === "plot-twist-generator") ||
      (handoffState.factionContext && slug === "faction-roster") ||
      (handoffState.npcContext && slug === "npc")
        ? null
        : (initialDraftOverride ?? slugDrafts[slug] ?? null)),
  );
</script>

<SEOGeneratorLayout
  bind:this={seoLayoutRef}
  pageTitle={meta.pageTitle}
  metaDescription={meta.metaDescription}
  introTitle={meta.introTitle}
  eyebrow={meta.eyebrow}
  introText={meta.introText}
  canonicalPath={meta.canonicalPath}
  ogImage={meta.ogImage}
  ogImageAlt={meta.ogImageAlt}
  keywords={meta.keywords ?? []}
  labels={meta.labels ?? []}
  faqs={meta.faqs ?? []}
  relatedLinks={meta.relatedLinks ?? []}
  bind:theme={activeTheme}
  isThemeCustomizable={shouldSyncGeneratorTheme(slug)}
  supportsStreaming={![
    "council-vote",
    "dungeon-generator",
    "adventure-generator",
    "adventure-idea-generator",
    "language-generator",
  ].includes(slug)}
  {generate}
  {initialDraft}
  initialDraftIsUserGenerated={Boolean(remixDraft)}
  {backHref}
  {backLabel}
  variant={slug === "names" || slug === "fantasy-names" ? "names" : "default"}
  onGeneratePlotTwist={slug === "quest" || slug === "villain-scheme-generator"
    ? openPlotTwistFromQuest
    : undefined}
  onGenerateRoster={slug === "faction" ? openRosterFromFaction : undefined}
  onOpenMemberAsCharacter={slug === "faction-roster"
    ? openMemberAsCharacter
    : undefined}
  autoGenerateExplicit={slug === "faction-roster"}
>
  {#snippet formFields(trigger)}
    <GeneratorPageFormFields
      {slug}
      bind:activeTheme
      {urlHubTheme}
      {trigger}
      bind:npc
      bind:settlement
      bind:magicItem
      bind:minorMagicItem
      bind:artifact
      bind:faction
      bind:factionRoster
      bind:quest
      bind:personality
      bind:rumour
      bind:encounter
      bind:puzzle
      bind:councilVote
      bind:heist
      bind:secretSociety
      bind:kingdom
      bind:nation
      bind:socialHub
      bind:tavern
      bind:vampireClan
      bind:nomadClan
      bind:darkFaction
      bind:names
      bind:dndNpc
      bind:pantheon
      bind:ship
      bind:language
      bind:newsSheet
      bind:dungeon
      bind:adventure
      bind:plotTwist
      bind:villain
      bind:comicBookEvent
      bind:origin
      bind:villainScheme
      bind:world
      bind:starSystem
      bind:constellation
      bind:alienRace
      bind:creature
      onPersonalityGenreChange={handlePersonalityGenreChange}
      onRumourGenreChange={handleRumourGenreChange}
      onPuzzleGenreChange={handlePuzzleGenreChange}
      onShipGenreChange={handleShipGenreChange}
      onWorldGenreChange={handleWorldGenreChange}
      onStarSystemGenreChange={handleStarSystemGenreChange}
      onAlienRaceGenreChange={handleAlienRaceGenreChange}
      onCreatureGenreChange={handleCreatureGenreChange}
    />
  {/snippet}
</SEOGeneratorLayout>
