import { describe, expect, it } from "vitest";
import {
  GenerationInputHistoryStore,
  summarizeResolvedInputs,
  formatRecentInputsNote,
} from "./generation-input-history";

function memoryStorage() {
  const map = new Map<string, string>();
  return {
    getItem: (key: string) => map.get(key) ?? null,
    setItem: (key: string, value: string) => {
      map.set(key, value);
    },
    removeItem: (key: string) => {
      map.delete(key);
    },
  };
}

describe("GenerationInputHistoryStore", () => {
  it("starts empty for any generator id", () => {
    const store = new GenerationInputHistoryStore(memoryStorage());
    expect(store.recent("npc")).toEqual([]);
  });

  it("records summaries most-recent-first, keyed per generator id", () => {
    const store = new GenerationInputHistoryStore(memoryStorage());
    store.record("npc", "genre: Cyberpunk, role: Fixer");
    store.record("npc", "genre: Classic Fantasy, role: Innkeeper");
    store.record("faction", "genre: Cosmic Horror");
    expect(store.recent("npc")).toEqual([
      "genre: Classic Fantasy, role: Innkeeper",
      "genre: Cyberpunk, role: Fixer",
    ]);
    expect(store.recent("faction")).toEqual(["genre: Cosmic Horror"]);
  });

  it("de-duplicates and moves a repeated summary to the front", () => {
    const store = new GenerationInputHistoryStore(memoryStorage());
    store.record("quest", "genre: Fantasy");
    store.record("quest", "genre: Sci-Fi");
    store.record("quest", "genre: Fantasy");
    expect(store.recent("quest")).toEqual(["genre: Fantasy", "genre: Sci-Fi"]);
  });

  it("caps history at 3 entries per generator", () => {
    const store = new GenerationInputHistoryStore(memoryStorage());
    for (const s of ["A", "B", "C", "D", "E"]) store.record("world", s);
    expect(store.recent("world")).toEqual(["E", "D", "C"]);
  });

  it("ignores blank or undefined summaries", () => {
    const store = new GenerationInputHistoryStore(memoryStorage());
    store.record("npc", undefined);
    store.record("npc", "   ");
    expect(store.recent("npc")).toEqual([]);
  });

  it("keeps generator ids independent", () => {
    const store = new GenerationInputHistoryStore(memoryStorage());
    store.record("npc", "genre: Fantasy");
    expect(store.recent("faction")).toEqual([]);
  });
});

describe("summarizeResolvedInputs", () => {
  it("joins short string fields as key: value pairs", () => {
    const summary = summarizeResolvedInputs({
      genre: "Cyberpunk / Corporate",
      tone: "Bleak",
      threatScale: "Global",
    });
    expect(summary).toBe(
      "genre: Cyberpunk / Corporate, tone: Bleak, threatScale: Global",
    );
  });

  it("excludes keys ending in name (case-insensitive)", () => {
    const summary = summarizeResolvedInputs({
      genre: "Fantasy",
      villainName: "Corvin Ashmere, the Quiet Hand",
      questName: "The Bell Beneath Blackwater",
    });
    expect(summary).toBe("genre: Fantasy");
  });

  it("excludes campaignContext and context fields", () => {
    const summary = summarizeResolvedInputs({
      genre: "Fantasy",
      campaignContext: "a coastal town hiding a drowned cult",
      context: "some freeform world context",
    });
    expect(summary).toBe("genre: Fantasy");
  });

  it("excludes non-string and overly long values", () => {
    const summary = summarizeResolvedInputs({
      genre: "Fantasy",
      count: 5,
      longField: "x".repeat(61),
    });
    expect(summary).toBe("genre: Fantasy");
  });

  it("returns an empty string when nothing qualifies", () => {
    expect(summarizeResolvedInputs({ villainName: "X" })).toBe("");
  });
});

describe("formatRecentInputsNote", () => {
  it("returns an empty string when there's no history", () => {
    expect(formatRecentInputsNote([])).toBe("");
  });

  it("formats a note listing recent summaries", () => {
    const note = formatRecentInputsNote(["genre: Fantasy", "genre: Sci-Fi"]);
    expect(note).toContain(
      "Recently generated by this tool this session, most recent first",
    );
    expect(note).toContain("genre: Fantasy | genre: Sci-Fi");
  });
});
