import {
  browserSessionStorage,
  type StorageLike,
} from "$lib/utils/runtime-deps";

const STORAGE_KEY = "GENERATION_INPUT_HISTORY";
const MAX_HISTORY_PER_GENERATOR = 3;

/**
 * Tracks the resolved input options (genre, tone, scope, etc.) of recent
 * generations per generator this browser session, so each generator's
 * prompt can be nudged to vary away from a recently-used combination instead
 * of only being asked for variety in the abstract (#2325 follow-up).
 */
export class GenerationInputHistoryStore {
  private storage: StorageLike;

  constructor(storage: StorageLike = browserSessionStorage) {
    this.storage = storage;
  }

  private loadAll(): Record<string, string[]> {
    try {
      const raw = this.storage.getItem(STORAGE_KEY);
      const parsed = raw ? JSON.parse(raw) : {};
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
        return {};
      }
      const result: Record<string, string[]> = {};
      for (const [key, value] of Object.entries(parsed)) {
        if (Array.isArray(value)) {
          result[key] = value.filter((v): v is string => typeof v === "string");
        }
      }
      return result;
    } catch {
      return {};
    }
  }

  /** Most recent summaries first, oldest last, for the given generator id. */
  recent(generatorId: string): string[] {
    return this.loadAll()[generatorId] ?? [];
  }

  record(generatorId: string, summary: string | undefined): void {
    const trimmed = summary?.trim();
    if (!trimmed) return;
    const all = this.loadAll();
    const existing = all[generatorId] ?? [];
    all[generatorId] = [
      trimmed,
      ...existing.filter((s) => s !== trimmed),
    ].slice(0, MAX_HISTORY_PER_GENERATOR);
    try {
      this.storage.setItem(STORAGE_KEY, JSON.stringify(all));
    } catch {
      // Best-effort — storage may be unavailable (private mode, quota).
    }
  }
}

export const generationInputHistoryStore = new GenerationInputHistoryStore();

/**
 * Builds a short "genre: X, tone: Y" style summary from any generator's
 * `resolved` options object. Excludes generated-name fields (keys ending in
 * "name", e.g. villainName/questName — identifiers, not input choices) and
 * freeform context fields (campaignContext/context — user-written prose, not
 * a choice worth nudging variety on).
 */
export function summarizeResolvedInputs(resolved: object): string {
  return Object.entries(resolved)
    .filter(
      ([key, value]) =>
        typeof value === "string" &&
        value.length > 0 &&
        value.length < 60 &&
        !/name$/i.test(key) &&
        key !== "campaignContext" &&
        key !== "context",
    )
    .map(([key, value]) => `${key}: ${value as string}`)
    .join(", ");
}

/**
 * Formats the "vary away from recent generations" prompt note. Returns an
 * empty string when there's no history yet, so callers can unconditionally
 * append it to a sessionContext string.
 */
export function formatRecentInputsNote(
  recentInputs: readonly string[],
): string {
  if (recentInputs.length === 0) return "";
  return `\nRecently generated by this tool this session, most recent first (vary your choices away from repeating the same combination unless the provided context specifically calls for it): ${recentInputs.join(" | ")}`;
}
