/**
 * GENERATED by scripts/sync-help-generators.ts from the generator registry.
 * Do not edit by hand: change a generator, then run the script.
 */
export const GENERATORS = [
  {
    id: "npc",
    label: "NPC",
    description: "Generate a non-player character for your campaign.",
  },
  {
    id: "faction",
    label: "Faction",
    description: "Generate a faction, guild, or organization.",
  },
  {
    id: "faction-roster",
    label: "Faction Roster",
    description: "Generate notable members of an existing faction.",
  },
  {
    id: "settlement",
    label: "Settlement",
    description: "Generate a settlement or location.",
  },
  {
    id: "magic-item",
    label: "Magic Item",
    description: "Generate a magic item or artifact.",
  },
  {
    id: "minor-magic-item",
    label: "Minor Magic Item / Trinket",
    description:
      "Generate a flavourful, low-impact, single-use, or consumable magic item or gadget.",
  },
  {
    id: "artifact",
    label: "Artifact / Relic",
    description:
      "Generate a unique, named, lore-heavy major artifact or ancient relic with tiered powers, consequential costs, and campaign hooks.",
  },
  {
    id: "event",
    label: "Event",
    description: "Generate a historical or unfolding event for your campaign.",
  },
  {
    id: "ship",
    label: "Ship",
    description:
      "Generate a ship for your campaign — location, faction asset, and adventure seed.",
  },
  {
    id: "language",
    label: "Language",
    description:
      "Generate a fictional language profile for your world, culture, or species.",
  },
  {
    id: "news-sheet",
    label: "News Sheet",
    description:
      "Generate an in-world news sheet (a cyberpunk-style screamsheet, fantasy broadsheet, or station newsfeed) — headlines, rumours, adverts, and hooks as a player handout.",
  },
  {
    id: "dungeon",
    label: "Dungeon / Delve",
    description:
      "Generate a multi-sector subterranean complex, ancient ruin, precursor vault, or monster lair with layout, factions, secret boss lore, hazards, and adventure hooks.",
  },
  {
    id: "adventure",
    label: "Adventure Idea",
    description:
      "Generate a campaign-ready adventure concept with dramatic ingredients, key actors, and multiple possible outcomes — a situation, not a plot.",
  },
  {
    id: "quest",
    label: "Quest Hook",
    description:
      "Generate a campaign-ready quest hook with a threat, complication, twist, and reward.",
  },
  {
    id: "rumour",
    label: "Rumour",
    description:
      "Generate a d6 table of 6 local rumours — lighter than a quest hook, each with a concrete lead the players can pursue.",
  },
  {
    id: "puzzle",
    label: "Puzzle",
    description:
      "Generate a flexible, table-ready encounter puzzle with layered clues and multiple viable solutions.",
  },
  {
    id: "plot-twist",
    label: "Plot Twist & Complication",
    description:
      "Reinterpret an established situation into a coherent twist, complication, and new player choices.",
  },
  {
    id: "villain",
    label: "BBEG / Campaign Villain",
    description:
      "Generate a campaign-scale antagonist — goal, methods, lieutenants, an escalating plan, and consequences — not just a biography.",
  },
  {
    id: "world",
    label: "World",
    description:
      "Generate a detailed sci-fi planet, moon, or artificial world with places, people, tensions, and adventure hooks.",
  },
  {
    id: "council-vote",
    label: "Council Vote",
    description:
      "Generate a political vote quest: a council of named voters, each with a distinct agenda, that the party must sway before a deadline decision.",
  },
  {
    id: "secret-society",
    label: "Secret Society",
    description:
      "Generate a cult, sect, conspiracy, or mystery order with a public face and a campaign-changing secret.",
  },
  {
    id: "star-system",
    label: "Star System",
    description:
      "Generate a coherent sci-fi star system: star(s), major bodies, factions, resources, hazards, and a system-wide conflict or mystery.",
  },
  {
    id: "constellation",
    label: "Constellation",
    description:
      "Generate a culturally meaningful constellation: a star pattern, an origin myth, seasonal visibility, practical use, cultural meaning, an omen, and an adventure hook.",
  },
  {
    id: "alien-race",
    label: "Alien Race",
    description:
      "Generate a coherent alien species where biology, environment, psychology, society and technology visibly shape one another.",
  },
  {
    id: "creature",
    label: "Creature",
    description:
      "Generate memorable beasts, monsters, alien fauna, constructs, spirits, or mounts with ecology, signs, tactics, and adventure hooks.",
  },
  {
    id: "random-table",
    label: "Random Roll Table",
    description:
      "Generate an atmospheric, world-grounded random roll table populated with your vault's lore and nested table references.",
  },
  {
    id: "encounter",
    label: "Encounter",
    description:
      "Generate a playable encounter — combat, social, exploration, environmental, or mixed — with participants, environment, goals, a complication, and outcomes.",
  },
  {
    id: "heist",
    label: "Heist",
    description:
      "Generate a playable score: a prize with a practical catch, three layered security rings, an escalating alarm track, and a getaway whose original plan has already failed.",
  },
  {
    id: "holiday",
    label: "Holiday & Festival",
    description:
      "Create a culturally grounded holiday, memorial, festival, or coherent calendar of observances.",
  },
] as const;

export type GeneratorId = (typeof GENERATORS)[number]["id"];

export const GENERATOR_IDS = GENERATORS.map(
  (g) => g.id,
) as unknown as readonly [GeneratorId, ...GeneratorId[]];
