/**
 * Closed catalogues of everything a guidance action may point at.
 *
 * Nothing outside these lists can be proposed, validated, or executed. Adding
 * an entry is a deliberate code change (and a review point), never something a
 * model, a retrieved document, or the browser can do at run time.
 */

import {
  GENERATOR_IDS,
  type GeneratorId,
} from "../registry/generators.generated";

/** The only action types that exist. None of them can change vault content. */
export const ACTION_TYPES = [
  "navigate",
  "openHelp",
  "openPanel",
  "highlight",
  "openGenerator",
] as const;
export type ActionType = (typeof ACTION_TYPES)[number];

/** Places `navigate` may go (mapped to real routes by the web app). */
export const DESTINATION_IDS = [
  "graph",
  "tables",
  "canvas",
  "map",
  "import",
  "timeline",
] as const;
export type DestinationId = (typeof DESTINATION_IDS)[number];

/**
 * VTT panels `openPanel` may open. Each one only changes what is showing (a
 * sidebar, a dialog); none of them touches the session, a token or the fog.
 */
export const VTT_PANEL_IDS = [
  "vtt-sidebar",
  "vtt-map-controls",
  "vtt-grid-settings",
  "vtt-encounters",
] as const;
export type VttPanelId = (typeof VTT_PANEL_IDS)[number];

/**
 * VTT controls `highlight` may point at. Pointing at one never operates it, so
 * a control that changes the session (advancing initiative, deleting an
 * encounter, starting a hosted session) can be shown but is never pressed.
 */
export const VTT_CONTROL_IDS = [
  "vtt-mode-toggle",
  "vtt-mode-switch",
  "vtt-add-token",
  "vtt-grid-button",
  "vtt-fog-toggle",
  "vtt-solo-fog-toggle",
  "vtt-travel-readout",
  "vtt-layer-control",
  "vtt-player-view-toggle",
  "vtt-ruler-toggle",
  "vtt-encounters-button",
  "vtt-tile-decks",
  "vtt-initiative-panel",
  "vtt-share-button",
] as const;

/** Everything the map can report as available, for the retry against an older Worker. */
export const VTT_ACTION_IDS: readonly string[] = [
  ...VTT_PANEL_IDS,
  ...VTT_CONTROL_IDS,
];

/**
 * Panels `openPanel` may open: entity detail tabs (matching the real tab IDs)
 * and Settings tabs, written `settings-<tab>`. Only the Settings tabs the
 * registry gives guidance for are listed; there is none for About or Help.
 */
export const PANEL_IDS = [
  "status-tab",
  "connections-tab",
  "stats-tab",
  "family-tab",
  "timeline-tab",
  "session-journal",
  "settings-vault",
  "settings-intelligence",
  "settings-schema",
  "settings-templates",
  "settings-theme",
  "settings-publishing",
  ...VTT_PANEL_IDS,
] as const;
export type PanelId = (typeof PANEL_IDS)[number];

const ENTITY_PANEL_TABS = {
  "status-tab": "status",
  "connections-tab": "connections",
  "stats-tab": "stats",
  "family-tab": "family",
  "timeline-tab": "timeline",
} as const;

/** Shared mapping so Worker validation and browser execution agree. */
export function entityTabForPanel(panel: PanelId) {
  return ENTITY_PANEL_TABS[panel as keyof typeof ENTITY_PANEL_TABS] ?? null;
}

/** The Settings panels, in the order the registry points at them. */
export const SETTINGS_PANEL_IDS = PANEL_IDS.filter((id) =>
  id.startsWith("settings-"),
);

/**
 * Generators `openGenerator` may open: every generator in the registry, from
 * the list generated by `scripts/sync-help-generators.ts`.
 */
export { GENERATOR_IDS, type GeneratorId };

/** Solo session controls: the Play page start, and the bar while a session runs. */
export const SOLO_CONTROL_IDS = [
  "play-start-solo-session",
  "solo-quick-roll",
  "solo-end-session",
  "solo-generate-menu",
  "solo-recent-results",
  "solo-pinned-tables",
  "solo-party-menu",
  "solo-scene-menu",
  "solo-oracle-menu",
  "solo-yes-no-menu",
  "solo-threads-menu",
] as const;

/** Controls `highlight` may point at (`data-help-target` values). */
export const CONTROL_IDS = [
  "add-connection-button",
  "generate-related-button",
  "status-tab",
  "connections-tab",
  ...VTT_CONTROL_IDS,
  ...SOLO_CONTROL_IDS,
] as const;
export type ControlId = (typeof CONTROL_IDS)[number];

/**
 * Panels that sit beside every screen. Their flag is present while the panel
 * is open, so it adds to the screen description instead of replacing the area.
 */
export const PANEL_FLAGS = ["explorer-open", "shelf-open"] as const;
export type PanelFlag = (typeof PANEL_FLAGS)[number];

/**
 * Facts about the map and VTT the user is looking at. Each is a yes/no about
 * the user's own state, never a name, ID or piece of content, and they are
 * only ever reported for the user's own view (a player's description never
 * mentions anything the GM is hiding from them).
 */
export const VTT_FLAGS = [
  "vtt-on",
  "vtt-combat",
  "vtt-guest",
  "vtt-player-view",
  "vtt-grid-square",
  "vtt-grid-hex",
  "vtt-fog-on",
  "vtt-solo-fog",
  "vtt-token-selected",
  "vtt-token-linked",
  "vtt-token-manageable",
  "vtt-layer-terrain",
  "vtt-layer-furniture",
  "vtt-layer-tokens",
  "vtt-has-initiative",
  "vtt-can-advance-turn",
  "vtt-hosting",
  "vtt-measuring",
] as const;
export type VttFlag = (typeof VTT_FLAGS)[number];

/** Material flags a screen description may carry. */
/** Set while a solo session is running in this vault. */
export const SESSION_FLAGS = ["solo-session"] as const;

export const HELP_FLAGS = [
  "generators",
  "connections-editable",
  ...PANEL_FLAGS,
  ...VTT_FLAGS,
  ...SESSION_FLAGS,
] as const;
export type HelpFlag = (typeof HELP_FLAGS)[number];

export interface ControlSpec {
  /**
   * Screen area the control lives in. `solo` controls appear on every screen
   * while a solo session runs, so they are not tied to one area.
   */
  area: "entity-detail" | "map" | "solo";
  /**
   * A flag the screen description must carry for the control to exist. The
   * Add button, for example, is absent in a read-only guest vault, so the
   * guide is not offered there.
   */
  requiresFlag?: HelpFlag;
  /** Some controls are host-only even if a malformed context lists them. */
  requiresNoFlag?: HelpFlag;
  /**
   * The panel that must be open for the control to be on screen. A control
   * with no panel is always on screen within its area.
   */
  panel?: PanelId;
}

export const CONTROL_CATALOGUE: Record<ControlId, ControlSpec> = {
  "add-connection-button": {
    area: "entity-detail",
    panel: "status-tab",
    requiresFlag: "connections-editable",
  },
  "generate-related-button": {
    area: "entity-detail",
    panel: "status-tab",
    requiresFlag: "generators",
  },
  "status-tab": { area: "entity-detail" },
  "connections-tab": { area: "entity-detail" },
  // Whether the user may use a VTT control is decided by the map, which only
  // lists the controls this user can reach; the flags say what must be on.
  "vtt-mode-toggle": { area: "map" },
  "vtt-mode-switch": { area: "map", requiresFlag: "vtt-on" },
  "vtt-add-token": { area: "map", requiresFlag: "vtt-on" },
  "vtt-grid-button": { area: "map" },
  "vtt-fog-toggle": { area: "map" },
  "vtt-solo-fog-toggle": { area: "map", requiresFlag: "vtt-fog-on" },
  "vtt-travel-readout": {
    area: "map",
    requiresFlag: "vtt-solo-fog",
    requiresNoFlag: "vtt-guest",
  },
  "vtt-layer-control": { area: "map" },
  "vtt-player-view-toggle": { area: "map" },
  "vtt-ruler-toggle": { area: "map", requiresFlag: "vtt-on" },
  "vtt-encounters-button": { area: "map", requiresFlag: "vtt-on" },
  "vtt-tile-decks": { area: "map", requiresFlag: "vtt-on" },
  "vtt-initiative-panel": { area: "map", requiresFlag: "vtt-combat" },
  "vtt-share-button": { area: "map", requiresFlag: "vtt-on" },
  "play-start-solo-session": { area: "solo" },
  "solo-quick-roll": { area: "solo", requiresFlag: "solo-session" },
  "solo-end-session": { area: "solo", requiresFlag: "solo-session" },
  "solo-generate-menu": { area: "solo", requiresFlag: "solo-session" },
  "solo-recent-results": { area: "solo", requiresFlag: "solo-session" },
  "solo-pinned-tables": { area: "solo", requiresFlag: "solo-session" },
  "solo-party-menu": { area: "solo", requiresFlag: "solo-session" },
  "solo-scene-menu": { area: "solo", requiresFlag: "solo-session" },
  "solo-oracle-menu": { area: "solo", requiresFlag: "solo-session" },
  "solo-yes-no-menu": { area: "solo", requiresFlag: "solo-session" },
  "solo-threads-menu": { area: "solo", requiresFlag: "solo-session" },
};

/**
 * The flag a screen description must carry for a generator guide to be
 * offered. It is true only where the generator workflow can really open (a
 * vault that is ready and not a guest vault), so one flag covers every generator.
 */
export const GENERATOR_REQUIRED_FLAG: HelpFlag = "generators";

/**
 * Every ID a screen description may list as currently available. The union of
 * the catalogues keeps the client from advertising anything the Worker would
 * not recognise.
 */
export const AVAILABLE_ACTION_IDS = Array.from(
  new Set<string>([
    ...CONTROL_IDS,
    ...PANEL_IDS,
    ...DESTINATION_IDS,
    ...GENERATOR_IDS,
  ]),
) as [string, ...string[]];
