import type { DiscoveryEntryInput } from "../schema";

/**
 * `/generators/*` — the live, no-login tools, plus the theme hubs that group
 * them.
 *
 * Every generator does the `create` job, so they are separated by *what* they
 * produce, not by phrasing. Several sit in a cluster with an `/answers` page on
 * the same subject; that pairing is deliberate and is the clearest example of
 * the rule this registry encodes — explain and create are different jobs.
 *
 * The theme hubs do `navigate`, not `create`: they exist to route a reader with
 * a genre in mind to the generators that suit it, and must not become
 * genre-flavoured copies of the generators themselves.
 */
export const generatorEntries: DiscoveryEntryInput[] = [
  {
    id: "generators-index",
    pageKind: "index",
    canonicalPath: "/generators",
    primaryIntent: "free rpg generators",
    intentAliases: ["tabletop generators hub", "random generators for rpgs"],
    userJob: "navigate",
    uniqueValue:
      "Directory of every live in-browser generator, grouped by genre, for a reader who does not yet know which one they need.",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-random",
    pageKind: "generator",
    canonicalPath: "/generators/random",
    primaryIntent: "random rpg idea generator",
    intentAliases: ["surprise me rpg generator"],
    userJob: "create",
    uniqueValue:
      "Draws from every generator at once, for a reader who wants a prompt rather than a specific artefact.",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-npc",
    pageKind: "generator",
    canonicalPath: "/generators/npc",
    primaryIntent: "rpg npc generator",
    intentAliases: ["random npc generator", "tabletop npc creator"],
    userJob: "create",
    uniqueValue:
      "Genre-agnostic NPC with ancestry, role, secret and a faction tie, generated in the browser with no account.",
    parentCluster: "npc-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-dnd-npc",
    pageKind: "generator",
    canonicalPath: "/generators/dnd-npc",
    primaryIntent: "dnd npc generator",
    intentAliases: ["d&d npc creator", "5e npc generator"],
    userJob: "create",
    uniqueValue:
      "D&D-shaped NPC output — ancestry and class vocabulary a 5e table expects — rather than the genre-agnostic version.",
    parentCluster: "npc-creation",
    indexable: true,
    status: "live",
    acknowledgedOverlap: [
      {
        with: "generator-npc",
        reason:
          "Genre-qualified variant: the D&D output uses ancestry and class vocabulary a 5e table expects, which the system-agnostic generator deliberately avoids.",
      },
    ],
  },
  {
    id: "generator-settlement",
    pageKind: "generator",
    canonicalPath: "/generators/settlement",
    primaryIntent: "settlement generator",
    intentAliases: ["town generator", "rpg city generator"],
    userJob: "create",
    uniqueValue:
      "Towns, districts, colonies and outposts with population, industry, threats and points of interest, across any genre.",
    parentCluster: "settlement-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-tavern",
    pageKind: "generator",
    canonicalPath: "/generators/tavern",
    primaryIntent: "tavern generator",
    intentAliases: ["inn generator", "rpg pub generator"],
    userJob: "create",
    uniqueValue:
      "A single enterable location in depth — owner, patrons, rumours and trouble — which the settlement generator only sketches.",
    parentCluster: "settlement-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-social-hub",
    pageKind: "generator",
    canonicalPath: "/generators/social-hub",
    primaryIntent: "social hub generator",
    intentAliases: ["rpg gathering place generator"],
    userJob: "create",
    uniqueValue:
      "The genre-agnostic equivalent of a tavern for settings with no taverns: nightclubs, mess halls, bathhouses, waystations.",
    parentCluster: "settlement-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-kingdom",
    pageKind: "generator",
    canonicalPath: "/generators/kingdom",
    primaryIntent: "kingdom generator",
    intentAliases: ["fantasy kingdom creator", "empire generator"],
    userJob: "create",
    uniqueValue:
      "A fantasy realm with ruler, court factions, geography and succession problems, at a scale above a settlement.",
    parentCluster: "polity-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-nation",
    pageKind: "generator",
    canonicalPath: "/generators/nation",
    primaryIntent: "nation generator",
    intentAliases: ["rpg country generator", "political entity generator"],
    userJob: "create",
    uniqueValue:
      "The cross-genre political entity — corporate state, republic, hegemony — for settings a fantasy kingdom does not fit.",
    parentCluster: "polity-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-faction",
    pageKind: "generator",
    canonicalPath: "/generators/faction",
    primaryIntent: "rpg faction generator",
    intentAliases: ["guild generator", "organisation generator for rpgs"],
    userJob: "create",
    uniqueValue:
      "A faction with agenda, leadership, resources, rivals and hooks, usable as a guild, cult, cartel or house.",
    parentCluster: "faction-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-secret-society",
    pageKind: "generator",
    canonicalPath: "/generators/secret-society",
    primaryIntent: "secret society generator",
    intentAliases: ["cult generator", "conspiracy group generator"],
    userJob: "create",
    uniqueValue:
      "Cells, oaths, recognition signs and cover stories — the structure a hidden organisation needs and an open faction does not.",
    parentCluster: "faction-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-council-vote",
    pageKind: "generator",
    canonicalPath: "/generators/council-vote",
    primaryIntent: "council vote generator",
    intentAliases: ["political vote scene generator"],
    userJob: "create",
    uniqueValue:
      "Turns a political decision into a playable scene: named voters with positions, leverage and what would change their mind.",
    parentCluster: "faction-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-bbeg-generator",
    pageKind: "generator",
    canonicalPath: "/generators/bbeg-generator",
    primaryIntent: "rpg villain generator",
    intentAliases: ["bbeg generator", "campaign antagonist generator"],
    userJob: "create",
    uniqueValue:
      "A campaign-scale villain with a concrete goal, methods, lieutenants and a timeline that runs whether or not the party interferes.",
    parentCluster: "antagonist-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-creature",
    pageKind: "generator",
    canonicalPath: "/generators/creature",
    primaryIntent: "rpg creature generator",
    intentAliases: ["monster generator", "fantasy beast generator"],
    userJob: "create",
    uniqueValue:
      "Original creatures with biology, behaviour and habitat rather than reskinned stat blocks.",
    parentCluster: "antagonist-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-alien-race",
    pageKind: "generator",
    canonicalPath: "/generators/alien-race",
    primaryIntent: "alien race generator",
    intentAliases: ["sci fi species generator"],
    userJob: "create",
    uniqueValue:
      "Coherent alien species — biology, homeworld, society — built so the parts imply each other.",
    parentCluster: "antagonist-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-encounter",
    pageKind: "generator",
    canonicalPath: "/generators/encounter",
    primaryIntent: "rpg encounter generator",
    intentAliases: ["random encounter generator"],
    userJob: "create",
    uniqueValue:
      "Playable encounters with an activity already in progress, across combat, social, exploration and environmental types.",
    parentCluster: "encounter-design",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-quest",
    pageKind: "generator",
    canonicalPath: "/generators/quest",
    primaryIntent: "rpg quest generator",
    intentAliases: ["adventure hook generator"],
    userJob: "create",
    uniqueValue:
      "Quest hooks with complications, twists and rewards attached, rather than a one-line premise.",
    parentCluster: "quest-design",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-rumour",
    pageKind: "generator",
    canonicalPath: "/generators/rumour",
    primaryIntent: "rpg rumour generator",
    intentAliases: ["tavern rumour generator", "random rumours for a town"],
    userJob: "create",
    uniqueValue:
      "A d6 table of local rumours, each with a concrete lead and a hidden GM-only truth, lighter than a full quest hook.",
    parentCluster: "quest-design",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-puzzle",
    pageKind: "generator",
    canonicalPath: "/generators/puzzle",
    primaryIntent: "rpg puzzle generator",
    intentAliases: ["dungeon puzzle generator"],
    userJob: "create",
    uniqueValue:
      "Puzzles built with layered clues and multiple solutions, which is the property that keeps a table moving.",
    parentCluster: "puzzle-design",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-dungeon-generator",
    pageKind: "generator",
    canonicalPath: "/generators/dungeon-generator",
    primaryIntent: "dungeon generator",
    intentAliases: ["delve generator", "ruin generator for rpgs"],
    userJob: "create",
    uniqueValue:
      "Multi-layered dungeons, ruins and vaults with a reason to exist and a structure to explore.",
    parentCluster: "adventure-mapping",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-adventure-generator",
    pageKind: "generator",
    canonicalPath: "/generators/adventure-generator",
    primaryIntent: "rpg adventure generator",
    intentAliases: ["adventure concept generator"],
    userJob: "create",
    uniqueValue:
      "Full adventure concepts — initial situation, stakes, opposition and resolution paths — for any genre.",
    parentCluster: "adventure-design",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-adventure-idea-generator",
    pageKind: "generator",
    canonicalPath: "/generators/adventure-idea-generator",
    primaryIntent: "adventure idea generator",
    intentAliases: ["one shot idea generator"],
    userJob: "create",
    uniqueValue:
      "Short adventure seeds for a reader who wants a premise rather than a structured scenario.",
    parentCluster: "adventure-design",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-plot-twist-generator",
    pageKind: "generator",
    canonicalPath: "/generators/plot-twist-generator",
    primaryIntent: "plot twist generator",
    intentAliases: ["rpg complication generator"],
    userJob: "create",
    uniqueValue:
      "Twists constrained to preserve established facts, so the output can be dropped into a running campaign.",
    parentCluster: "adventure-design",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-magic-item",
    pageKind: "generator",
    canonicalPath: "/generators/magic-item",
    primaryIntent: "magic item generator",
    intentAliases: ["fantasy magic item creator"],
    userJob: "create",
    uniqueValue:
      "Magic items with lore, abilities, quirks and campaign hooks attached.",
    parentCluster: "item-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-minor-magic-item",
    pageKind: "generator",
    canonicalPath: "/generators/minor-magic-item",
    primaryIntent: "minor magic item generator",
    intentAliases: ["trinket generator", "rpg consumable generator"],
    userJob: "create",
    uniqueValue:
      "Low-stakes trinkets, charms and consumables — the volume tier the main magic-item generator overshoots.",
    parentCluster: "item-creation",
    indexable: true,
    status: "live",
    acknowledgedOverlap: [
      {
        with: "generator-magic-item",
        reason:
          "Deliberate tier split: one produces campaign-relevant items, the other the volume of small trinkets a table burns through. Merging them would make the common case harder to reach.",
      },
    ],
  },
  {
    id: "generator-artifact-generator",
    pageKind: "generator",
    canonicalPath: "/generators/artifact-generator",
    primaryIntent: "rpg artifact generator",
    intentAliases: ["legendary relic generator"],
    userJob: "create",
    uniqueValue:
      "Campaign-shaping artifacts with history and consequence, at the tier above ordinary magic items.",
    parentCluster: "item-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-item",
    pageKind: "generator",
    canonicalPath: "/generators/item",
    primaryIntent: "rpg item generator",
    intentAliases: ["loot generator", "weapon generator for rpgs"],
    userJob: "create",
    uniqueValue:
      "General loot and equipment across genres, including non-magical gear.",
    parentCluster: "item-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-ship-generator",
    pageKind: "generator",
    canonicalPath: "/generators/ship-generator",
    primaryIntent: "rpg ship generator",
    intentAliases: ["starship generator", "sailing ship generator for rpgs"],
    userJob: "create",
    uniqueValue:
      "Vessels for any genre — starships, sailing ships, airships — with crew, quirks and history.",
    parentCluster: "vehicle-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-pantheon-generator",
    pageKind: "generator",
    canonicalPath: "/generators/pantheon-generator",
    primaryIntent: "rpg pantheon generator",
    intentAliases: ["fantasy pantheon creator", "god pantheon generator"],
    userJob: "create",
    uniqueValue:
      "A connected pantheon with alliances, rivalries and myths, rather than a list of gods with one domain each.",
    parentCluster: "gods-and-faith",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-god-generator",
    pageKind: "generator",
    canonicalPath: "/generators/god-generator",
    primaryIntent: "rpg god generator",
    intentAliases: ["deity generator", "fantasy god creator"],
    userJob: "create",
    uniqueValue:
      "A single deity in depth — domains, taboos, symbols and what worship demands — where the pantheon generator gives the roster.",
    parentCluster: "gods-and-faith",
    indexable: true,
    status: "live",
    acknowledgedOverlap: [
      {
        with: "generator-pantheon-generator",
        reason:
          "The pantheon generator produces the roster and its entanglements; this produces one deity in depth. A reader needs one or the other, rarely both at once.",
      },
    ],
  },
  {
    id: "generator-names",
    pageKind: "generator",
    canonicalPath: "/generators/names",
    primaryIntent: "rpg name generator",
    intentAliases: ["random name generator for rpgs"],
    userJob: "create",
    uniqueValue:
      "Names for characters, places, factions and items across any genre in one tool.",
    parentCluster: "naming",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-fantasy-names",
    pageKind: "generator",
    canonicalPath: "/generators/fantasy-names",
    primaryIntent: "fantasy name generator",
    intentAliases: ["fantasy character name generator"],
    userJob: "create",
    uniqueValue:
      "Fantasy-specific naming with cultural styles, for readers whose query is genre-qualified.",
    parentCluster: "naming",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-language-generator",
    pageKind: "generator",
    canonicalPath: "/generators/language-generator",
    primaryIntent: "fictional language generator",
    intentAliases: ["conlang generator for worldbuilding"],
    userJob: "create",
    uniqueValue:
      "A language profile — phonology, naming patterns, sample lexicon — used to keep invented names internally consistent.",
    parentCluster: "naming",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-world",
    pageKind: "generator",
    canonicalPath: "/generators/world",
    primaryIntent: "sci fi world generator",
    intentAliases: ["planet generator", "exoplanet generator for rpgs"],
    userJob: "create",
    uniqueValue:
      "Planets, moons and artificial worlds with environment, habitability and points of interest.",
    parentCluster: "cosmography",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-star-system",
    pageKind: "generator",
    canonicalPath: "/generators/star-system",
    primaryIntent: "star system generator",
    intentAliases: ["solar system generator for rpgs"],
    userJob: "create",
    uniqueValue:
      "A whole system — stars, major bodies and their relationships — at the scale above a single world.",
    parentCluster: "cosmography",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-news-sheet-generator",
    pageKind: "generator",
    canonicalPath: "/generators/news-sheet-generator",
    primaryIntent: "in world news sheet generator",
    intentAliases: ["rpg newspaper generator", "broadsheet generator"],
    userJob: "create",
    uniqueValue:
      "An in-world handout the party can read, which is a different artefact from GM-facing prep.",
    parentCluster: "player-handouts",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-vampire-clan",
    pageKind: "generator",
    canonicalPath: "/generators/vampire-clan",
    primaryIntent: "vampire clan generator",
    intentAliases: ["bloodline generator", "coven generator"],
    userJob: "create",
    uniqueValue:
      "Vampire clans and bloodlines with occult agendas, for gothic and World of Darkness-style games.",
    parentCluster: "faction-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-nomad-clan",
    pageKind: "generator",
    canonicalPath: "/generators/nomad-clan",
    primaryIntent: "cyberpunk nomad clan generator",
    intentAliases: ["nomad family generator"],
    userJob: "create",
    uniqueValue:
      "Cyberpunk nomad convoys — road codes, corporate entanglements and convoy culture.",
    parentCluster: "faction-creation",
    indexable: true,
    status: "live",
  },
  {
    id: "generator-dark-fantasy-faction",
    pageKind: "generator",
    canonicalPath: "/generators/dark-fantasy-faction",
    primaryIntent: "dark fantasy faction generator",
    intentAliases: [
      "grimdark faction generator",
      "witch hunter faction generator",
      "cursed kingdom faction generator",
    ],
    userJob: "create",
    uniqueValue:
      "Fallen orders, cursed noble houses, plague cults, witch-hunter lodges and corpse guilds — grimdark institutions doing something defensible in the worst possible way, distinct from the generic Classic Fantasy faction and from the gothic/World of Darkness vampire clan.",
    parentCluster: "faction-creation",
    relatedIntents: ["generator-faction", "generator-vampire-clan"],
    indexable: true,
    status: "live",
  },
  {
    id: "hub-fantasy",
    pageKind: "hub",
    canonicalPath: "/generators/fantasy",
    primaryIntent: "fantasy rpg generators",
    intentAliases: ["fantasy generator hub"],
    audience: "Fantasy game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Fantasy campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-pirate",
    pageKind: "hub",
    canonicalPath: "/generators/pirate",
    primaryIntent: "pirate rpg generators",
    intentAliases: ["pirate generator hub"],
    audience: "Pirate game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Pirate campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-cyberpunk",
    pageKind: "hub",
    canonicalPath: "/generators/cyberpunk",
    primaryIntent: "cyberpunk rpg generators",
    intentAliases: ["cyberpunk generator hub"],
    audience: "Cyberpunk game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Cyberpunk campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-sci-fi",
    pageKind: "hub",
    canonicalPath: "/generators/sci-fi",
    primaryIntent: "sci-fi rpg generators",
    intentAliases: ["sci-fi generator hub"],
    audience: "Sci-Fi game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Sci-Fi campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-post-apocalyptic",
    pageKind: "hub",
    canonicalPath: "/generators/post-apocalyptic",
    primaryIntent: "post-apocalyptic rpg generators",
    intentAliases: ["post-apocalyptic generator hub"],
    audience: "Post-Apocalyptic game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Post-Apocalyptic campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-modern",
    pageKind: "hub",
    canonicalPath: "/generators/modern",
    primaryIntent: "modern rpg generators",
    intentAliases: ["modern generator hub"],
    audience: "Modern game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Modern campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-vampire",
    pageKind: "hub",
    canonicalPath: "/generators/vampire",
    primaryIntent: "vampire rpg generators",
    intentAliases: ["vampire generator hub"],
    audience: "Vampire game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Vampire campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-cosmic-horror",
    pageKind: "hub",
    canonicalPath: "/generators/cosmic-horror",
    primaryIntent: "cosmic horror rpg generators",
    intentAliases: ["cosmic horror generator hub"],
    audience: "Cosmic Horror game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Cosmic Horror campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-western",
    pageKind: "hub",
    canonicalPath: "/generators/western",
    primaryIntent: "western rpg generators",
    intentAliases: ["western generator hub"],
    audience: "Western game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Western campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-steampunk",
    pageKind: "hub",
    canonicalPath: "/generators/steampunk",
    primaryIntent: "steampunk rpg generators",
    intentAliases: ["steampunk generator hub"],
    audience: "Steampunk game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Steampunk campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-lancer",
    pageKind: "hub",
    canonicalPath: "/generators/lancer",
    primaryIntent: "lancer rpg generators",
    intentAliases: ["lancer generator hub"],
    audience: "Lancer game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Lancer campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-space-opera-resistance",
    pageKind: "hub",
    canonicalPath: "/generators/space-opera-resistance",
    primaryIntent: "space opera resistance rpg generators",
    intentAliases: ["space opera resistance generator hub"],
    audience: "Space Opera Resistance game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Space Opera Resistance campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-optimistic-exploration-sci-fi",
    pageKind: "hub",
    canonicalPath: "/generators/optimistic-exploration-sci-fi",
    primaryIntent: "optimistic exploration sci-fi rpg generators",
    intentAliases: ["optimistic exploration sci-fi generator hub"],
    audience: "Optimistic Exploration Sci-Fi game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Optimistic Exploration Sci-Fi campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
  {
    id: "hub-space-western",
    pageKind: "hub",
    canonicalPath: "/generators/space-western",
    primaryIntent: "space western rpg generators",
    intentAliases: ["space western generator hub", "scoundrel rpg generators"],
    audience: "Space Western and Scoundrel game masters",
    userJob: "navigate",
    uniqueValue:
      "Routes a reader with a Space Western or Scoundrel campaign in mind to the generators that suit it, with genre-appropriate framing.",
    parentCluster: "theme-hubs",
    indexable: true,
    status: "live",
  },
];
