export const nameTable = {
  prefixes: [
    "Ael",
    "Bran",
    "Cael",
    "Dax",
    "El",
    "Fael",
    "Grom",
    "Had",
    "Ior",
    "Jor",
    "Kael",
    "Lyr",
    "Morg",
    "Nal",
    "Odh",
    "Py",
    "Quel",
    "Rhu",
    "Sari",
    "Thor",
    "Uth",
    "Vael",
    "Wulf",
    "Xan",
    "Ysv",
    "Zeph",
  ],
  suffixes: [
    "dar",
    "gorn",
    "thor",
    "ius",
    "eth",
    "wen",
    "dolf",
    "ric",
    "mar",
    "mon",
    "las",
    "vian",
    "dor",
    "morn",
    "ra",
    "thas",
    "val",
    "gar",
    "rin",
    "kis",
    "on",
    "ar",
    "en",
    "is",
    "a",
    "os",
  ],
  descriptors: [
    "The Brave",
    "The Silent",
    "The Swift",
    "The Bold",
    "The Seer",
    "The Wise",
    "The Shadow",
    "The Iron",
    "The Wild",
    "The Grim",
    "The Lost",
    "The Seeker",
    "The Wanderer",
    "The Exile",
    "The Fierce",
    "The Chronicler",
  ],
};

export const nameGeneratorConfig = {
  cultures: [
    "Generic Fantasy",
    "High Elf",
    "Dark Elf",
    "Dwarven",
    "Halfling",
    "Orcish",
    "Norse / Viking",
    "Roman / Latin",
    "Celtic / Gaelic",
    "Eastern / Asian-inspired",
  ],
  culturesByTheme: {
    "Classic Fantasy": [
      "Generic Fantasy",
      "High Elf",
      "Dark Elf",
      "Dwarven",
      "Halfling",
      "Orcish",
      "Norse / Viking",
      "Roman / Latin",
      "Celtic / Gaelic",
      "Eastern / Asian-inspired",
    ],
    "Cyberpunk / Corporate": [
      "Street Handle",
      "Corporate Professional",
      "Japanese-inspired",
      "Eastern European",
      "Latin American",
      "Synthetic / AI",
      "Gang / Crew",
      "Hacker Alias",
    ],
    "Vampire / Gothic Noir": [
      "Old European Aristocracy",
      "Victorian English",
      "French Gothic",
      "Romanian / Slavic",
      "Italian Renaissance",
      "Secret Society",
      "Occult / Latin",
    ],
    "Sci-Fi / Space Opera": [
      "Colonial Human",
      "Alien-sounding",
      "Station-born",
      "Military Call Sign",
      "Megacorp Branding",
      "Synthetic / Android",
      "Starship Names",
    ],
    "Modern Conspiracy": [
      "American",
      "British",
      "Cover Identity",
      "Codename",
      "Eastern European",
      "Agency Alias",
    ],
    "Post-Apocalyptic": [
      "Wasteland Moniker",
      "Scavver Nickname",
      "Pre-War Surname",
      "Tribal",
      "Raider Handle",
      "Vault-born",
    ],
  } as Record<string, string[]>,
  genders: ["Any", "Masculine", "Feminine", "Neutral / Ambiguous"],
  nameTypes: ["Person", "Place", "Faction", "Item"],
  culturePrefixes: {
    "Generic Fantasy": [
      "Ael",
      "Bran",
      "Cael",
      "Dax",
      "El",
      "Fael",
      "Kael",
      "Lyr",
      "Morg",
      "Nal",
      "Thor",
      "Vael",
    ],
    "High Elf": [
      "Aer",
      "Caer",
      "El",
      "Gal",
      "Ith",
      "Lae",
      "Mir",
      "Sil",
      "Thal",
      "Var",
      "Wyn",
      "Zin",
    ],
    "Dark Elf": [
      "Driz",
      "Mal",
      "Nath",
      "Riz",
      "Sol",
      "Szor",
      "Ul",
      "Vir",
      "Xan",
      "Zaer",
      "Zin",
      "Vy",
    ],
    Dwarven: [
      "Bal",
      "Dur",
      "Glor",
      "Grim",
      "Kat",
      "Kaz",
      "Mag",
      "Nar",
      "Thor",
      "Tor",
      "Ulf",
      "Vor",
    ],
    Halfling: [
      "Bil",
      "Cor",
      "Del",
      "Fil",
      "Gob",
      "Mer",
      "Pip",
      "Rose",
      "Sam",
      "Tom",
      "Wil",
      "Bun",
    ],
    Orcish: [
      "Druk",
      "Grak",
      "Grom",
      "Krag",
      "Mog",
      "Nar",
      "Rok",
      "Skul",
      "Thok",
      "Urg",
      "Vrak",
      "Zug",
    ],
    "Norse / Viking": [
      "Arn",
      "Bjor",
      "Dag",
      "Eil",
      "Gunn",
      "Hal",
      "Ing",
      "Leif",
      "Rag",
      "Sigr",
      "Thor",
      "Ulf",
    ],
    "Roman / Latin": [
      "Aem",
      "Aur",
      "Bru",
      "Cal",
      "Cas",
      "Cor",
      "Flav",
      "Jul",
      "Marc",
      "Octa",
      "Sext",
      "Val",
    ],
    "Celtic / Gaelic": [
      "Aed",
      "Bran",
      "Caill",
      "Conn",
      "Donn",
      "Eoch",
      "Fearg",
      "Niall",
      "Ruad",
      "Taig",
      "Uar",
      "Cunn",
    ],
    "Eastern / Asian-inspired": [
      "Akira",
      "Chen",
      "Hiro",
      "Jin",
      "Kai",
      "Li",
      "Ren",
      "Ryu",
      "Shen",
      "Tao",
      "Wei",
      "Zhen",
    ],
  } as Record<string, string[]>,
  cultureSuffixes: {
    "Generic Fantasy": [
      "dar",
      "eth",
      "gorn",
      "ius",
      "mar",
      "morn",
      "ra",
      "ric",
      "thas",
      "val",
      "wen",
      "thor",
    ],
    "High Elf": [
      "ael",
      "aith",
      "ara",
      "ath",
      "elan",
      "iath",
      "ien",
      "ira",
      "is",
      "ith",
      "on",
      "rial",
    ],
    "Dark Elf": [
      "ace",
      "arn",
      "bra",
      "dra",
      "fein",
      "ica",
      "inae",
      "ra",
      "rix",
      "ssa",
      "tra",
      "vra",
    ],
    Dwarven: [
      "ak",
      "ald",
      "ar",
      "ek",
      "im",
      "in",
      "kin",
      "nar",
      "rek",
      "rim",
      "rin",
      "uk",
    ],
    Halfling: [
      "ble",
      "boro",
      "buck",
      "fast",
      "foot",
      "fur",
      "good",
      "hill",
      "penny",
      "seed",
      "wise",
      "wool",
    ],
    Orcish: [
      "ash",
      "dar",
      "gash",
      "grak",
      "gruk",
      "kul",
      "lash",
      "mok",
      "rak",
      "skrag",
      "thak",
      "ugh",
    ],
    "Norse / Viking": [
      "ald",
      "bjorn",
      "dís",
      "eit",
      "gar",
      "helm",
      "nar",
      "rún",
      "stein",
      "ulf",
      "vald",
      "var",
    ],
    "Roman / Latin": [
      "anus",
      "ella",
      "ia",
      "ianus",
      "illa",
      "ina",
      "inus",
      "io",
      "ius",
      "lia",
      "ona",
      "us",
    ],
    "Celtic / Gaelic": [
      "ach",
      "all",
      "an",
      "ard",
      "as",
      "dha",
      "ech",
      "en",
      "inn",
      "on",
      "ua",
      "ugh",
    ],
    "Eastern / Asian-inspired": [
      "bo",
      "fa",
      "ji",
      "ko",
      "lan",
      "lei",
      "li",
      "mei",
      "na",
      "ro",
      "shi",
      "xia",
    ],
  } as Record<string, string[]>,
};

export interface GeneratorOutput {
  type:
    | "character"
    | "creature"
    | "location"
    | "item"
    | "event"
    | "faction"
    | "note";
  title: string;
  summary?: string;
  content: string;
  lore: string;
  labels: string[];
  status: "active" | "draft";
}

/**
 * Random source returning a float in [0, 1) — the same contract as
 * `Math.random`. Injected (as a trailing optional arg) so generators can be
 * driven by a seeded RNG in tests for stable snapshots; defaults to the global.
 */
export type Rng = () => number;
export const defaultRng: Rng = () => Math.random();

export function pickFrom<T>(arr: T[], rng: Rng = defaultRng): T {
  return arr[Math.floor(rng() * arr.length)];
}

export function getRandomItems<T>(
  arr: T[],
  count: number,
  rng: Rng = defaultRng,
): T[] {
  // Fisher-Yates shuffle — unbiased and deterministic for a fixed rng sequence
  // (a random `sort` comparator is non-transitive: biased and engine-dependent).
  const shuffled = [...arr];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, count);
}

export function generateName(rng: Rng = defaultRng): string {
  const prefix =
    nameTable.prefixes[Math.floor(rng() * nameTable.prefixes.length)];
  const suffix =
    nameTable.suffixes[Math.floor(rng() * nameTable.suffixes.length)];
  const useDescriptor = rng() > 0.6;
  let name = `${prefix}${suffix}`;
  if (useDescriptor) {
    const descriptor =
      nameTable.descriptors[Math.floor(rng() * nameTable.descriptors.length)];
    name = `${name} ${descriptor}`;
  }
  return name;
}
