import { AnswerConfigSchema, type AnswerConfig } from "../schema";
import { howDoIBalanceRpgCombatEncountersWithoutATpk } from "./how-do-i-balance-rpg-combat-encounters-without-a-tpk";
import { howDoIFindATabletopRpgGroupToPlayWith } from "./how-do-i-find-a-tabletop-rpg-group-to-play-with";
import { howDoIGetPlayersToEngageWithMyCampaignWorld } from "./how-do-i-get-players-to-engage-with-my-campaign-world";
import { howDoIRunASuccessfulSessionZero } from "./how-do-i-run-a-successful-session-0";
import { howDoYouCreateABelievableFictionalReligion } from "./how-do-you-create-a-believable-fictional-religion";
import { howDoYouCreateAFantasyFaction } from "./how-do-you-create-a-fantasy-faction";
import { howDoYouCreateAPantheon } from "./how-do-you-create-a-pantheon";
import { howDoYouDesignRpgPuzzlesThatDoNotStallTheGame } from "./how-do-you-design-rpg-puzzles-that-do-not-stall-the-game";
import { howDoYouMakeNpcsMemorableWithoutLotsOfPrep } from "./how-do-you-make-npcs-memorable-without-lots-of-prep";
import { howDoYouMakeTravelInterestingInATabletopRpg } from "./how-do-you-make-travel-interesting-in-a-tabletop-rpg";
import { howDoYouOrganiseNpcRelationships } from "./how-do-you-organise-npc-relationships";
import { howDoYouOrganiseRpgCampaignNotes } from "./how-do-you-organise-rpg-campaign-notes";
import { howDoYouPrepareASandboxRpgCampaign } from "./how-do-you-prepare-a-sandbox-rpg-campaign";
import { howDoYouRunAConspiracyCampaign } from "./how-do-you-run-a-conspiracy-campaign";
import { howMuchPrepDoYouNeedForAnRpgSession } from "./how-much-prep-do-you-need-for-an-rpg-session";
import { whatIsAPointCrawl } from "./what-is-a-point-crawl";
import { whatMakesAGoodRandomEncounter } from "./what-makes-a-good-random-encounter";
import { whatRpgSystemShouldWeTryInsteadOfDnd } from "./what-rpg-system-should-we-try-instead-of-dnd";
import { whatShouldAnRpgSettlementContain } from "./what-should-an-rpg-settlement-contain";
import { whatShouldILookForInAnRpgCampaignManager } from "./what-should-i-look-for-in-an-rpg-campaign-manager";
import { whereDoIStartIfIHaveNeverPlayedATabletopRpg } from "./where-do-i-start-if-i-have-never-played-a-tabletop-rpg";

/**
 * The published answer library.
 *
 * Auto-generated by scripts/sync-answers.ts. Do not edit directly.
 * To add a new answer, create a file in `pages/<slug>.ts` and run `bun sync:answers`.
 */
export const answers: Record<string, AnswerConfig> = Object.fromEntries(
  [
    howDoIBalanceRpgCombatEncountersWithoutATpk,
    howDoIFindATabletopRpgGroupToPlayWith,
    howDoIGetPlayersToEngageWithMyCampaignWorld,
    howDoIRunASuccessfulSessionZero,
    howDoYouCreateABelievableFictionalReligion,
    howDoYouCreateAFantasyFaction,
    howDoYouCreateAPantheon,
    howDoYouDesignRpgPuzzlesThatDoNotStallTheGame,
    howDoYouMakeNpcsMemorableWithoutLotsOfPrep,
    howDoYouMakeTravelInterestingInATabletopRpg,
    howDoYouOrganiseNpcRelationships,
    howDoYouOrganiseRpgCampaignNotes,
    howDoYouPrepareASandboxRpgCampaign,
    howDoYouRunAConspiracyCampaign,
    howMuchPrepDoYouNeedForAnRpgSession,
    whatIsAPointCrawl,
    whatMakesAGoodRandomEncounter,
    whatRpgSystemShouldWeTryInsteadOfDnd,
    whatShouldAnRpgSettlementContain,
    whatShouldILookForInAnRpgCampaignManager,
    whereDoIStartIfIHaveNeverPlayedATabletopRpg,
  ]
    .map((answer) => AnswerConfigSchema.parse(answer))
    .map((answer) => [answer.slug, answer]),
);
