import { AnswerConfigSchema, type AnswerConfig } from "../schema";
import { howDoIBalanceRpgCombatEncountersWithoutATpk } from "./how-do-i-balance-rpg-combat-encounters-without-a-tpk";
import { howDoIFindATabletopRpgGroupToPlayWith } from "./how-do-i-find-a-tabletop-rpg-group-to-play-with";
import { howDoIGetPlayersToEngageWithMyCampaignWorld } from "./how-do-i-get-players-to-engage-with-my-campaign-world";
import { howDoIRunASuccessfulSessionZero } from "./how-do-i-run-a-successful-session-0";
import { howDoYouBuildAPointCrawlForAnRpg } from "./how-do-you-build-a-point-crawl-for-an-rpg";
import { howDoYouCreateABelievableFictionalReligion } from "./how-do-you-create-a-believable-fictional-religion";
import { howDoYouCreateAFantasyFaction } from "./how-do-you-create-a-fantasy-faction";
import { howDoYouCreateAFictionalLanguageForAnRpg } from "./how-do-you-create-a-fictional-language-for-an-rpg";
import { howDoYouCreateAMagicSystem } from "./how-do-you-create-a-magic-system";
import { howDoYouCreateAPantheon } from "./how-do-you-create-a-pantheon";
import { howDoYouDesignRpgPuzzlesThatDoNotStallTheGame } from "./how-do-you-design-rpg-puzzles-that-do-not-stall-the-game";
import { howDoYouHandleCharacterDeathInATabletopRpg } from "./how-do-you-handle-character-death-in-a-tabletop-rpg";
import { howDoYouKeepTrackOfTimeInATabletopCampaign } from "./how-do-you-keep-track-of-time-in-a-tabletop-campaign";
import { howDoYouMakeNpcsMemorableWithoutLotsOfPrep } from "./how-do-you-make-npcs-memorable-without-lots-of-prep";
import { howDoYouMakeTravelInterestingInATabletopRpg } from "./how-do-you-make-travel-interesting-in-a-tabletop-rpg";
import { howDoYouOrganiseNpcRelationships } from "./how-do-you-organise-npc-relationships";
import { howDoYouOrganiseRpgCampaignNotes } from "./how-do-you-organise-rpg-campaign-notes";
import { howDoYouPrepAWeeklyRpgSessionQuickly } from "./how-do-you-prep-a-weekly-rpg-session-quickly";
import { howDoYouPrepareASandboxRpgCampaign } from "./how-do-you-prepare-a-sandbox-rpg-campaign";
import { howDoYouRunAConspiracyCampaign } from "./how-do-you-run-a-conspiracy-campaign";
import { howDoYouRunAHeistInATabletopRpg } from "./how-do-you-run-a-heist-in-a-tabletop-rpg";
import { howDoYouRunAMysteryWithoutRailroading } from "./how-do-you-run-a-mystery-without-railroading";
import { howDoYouStartWorldbuildingFromScratch } from "./how-do-you-start-worldbuilding-from-scratch";
import { howDoYouTrackUnresolvedPlotHooksInAnRpgCampaign } from "./how-do-you-track-unresolved-plot-hooks-in-an-rpg-campaign";
import { howDoYouWriteAOneShotAdventure } from "./how-do-you-write-a-one-shot-adventure";
import { howMuchPrepDoYouNeedForAnRpgSession } from "./how-much-prep-do-you-need-for-an-rpg-session";
import { howToWriteAnInWorldNewspaperForAnRpg } from "./how-to-write-an-in-world-newspaper-for-an-rpg";
import { whatIsAPointCrawl } from "./what-is-a-point-crawl";
import { whatMakesAGoodRandomEncounter } from "./what-makes-a-good-random-encounter";
import { whatRpgSystemShouldWeTryInsteadOfDnd } from "./what-rpg-system-should-we-try-instead-of-dnd";
import { whatShouldAnRpgSettlementContain } from "./what-should-an-rpg-settlement-contain";
import { whatShouldILookForInAnRpgCampaignManager } from "./what-should-i-look-for-in-an-rpg-campaign-manager";
import { whereDoIStartIfIHaveNeverPlayedATabletopRpg } from "./where-do-i-start-if-i-have-never-played-a-tabletop-rpg";

/**
 * The published answer library.
 *
 * Auto-generated by scripts/sync-answers.ts. Do not edit directly.
 * To add a new answer, create a file in `pages/<slug>.ts` and run `bun sync:answers`.
 */
export const answers: Record<string, AnswerConfig> = Object.fromEntries(
  [
    howDoIBalanceRpgCombatEncountersWithoutATpk,
    howDoIFindATabletopRpgGroupToPlayWith,
    howDoIGetPlayersToEngageWithMyCampaignWorld,
    howDoIRunASuccessfulSessionZero,
    howDoYouBuildAPointCrawlForAnRpg,
    howDoYouCreateABelievableFictionalReligion,
    howDoYouCreateAFantasyFaction,
    howDoYouCreateAFictionalLanguageForAnRpg,
    howDoYouCreateAMagicSystem,
    howDoYouCreateAPantheon,
    howDoYouDesignRpgPuzzlesThatDoNotStallTheGame,
    howDoYouHandleCharacterDeathInATabletopRpg,
    howDoYouKeepTrackOfTimeInATabletopCampaign,
    howDoYouMakeNpcsMemorableWithoutLotsOfPrep,
    howDoYouMakeTravelInterestingInATabletopRpg,
    howDoYouOrganiseNpcRelationships,
    howDoYouOrganiseRpgCampaignNotes,
    howDoYouPrepAWeeklyRpgSessionQuickly,
    howDoYouPrepareASandboxRpgCampaign,
    howDoYouRunAConspiracyCampaign,
    howDoYouRunAHeistInATabletopRpg,
    howDoYouRunAMysteryWithoutRailroading,
    howDoYouStartWorldbuildingFromScratch,
    howDoYouTrackUnresolvedPlotHooksInAnRpgCampaign,
    howDoYouWriteAOneShotAdventure,
    howMuchPrepDoYouNeedForAnRpgSession,
    howToWriteAnInWorldNewspaperForAnRpg,
    whatIsAPointCrawl,
    whatMakesAGoodRandomEncounter,
    whatRpgSystemShouldWeTryInsteadOfDnd,
    whatShouldAnRpgSettlementContain,
    whatShouldILookForInAnRpgCampaignManager,
    whereDoIStartIfIHaveNeverPlayedATabletopRpg,
  ]
    .map((answer) => AnswerConfigSchema.parse(answer))
    .map((answer) => [answer.slug, answer]),
);
