import type { AdventureGenreTables } from "../genre-types";

export const cosmicHorrorAdventureTables: AdventureGenreTables = {
  hint: "Focus on investigation, fragile certainty, and discoveries that make the world larger and less knowable. Use field reports, scientific institutions, remote communities, and physical evidence. Avoid treating this as vampire gothic or generic dark fantasy: the pressure should come from impossible patterns, compromised testimony, alien scale, and difficult containment.",
  archetypes: [
    "Investigation & Mystery",
    "Expedition & Discovery",
    "Ritual & Containment",
    "Rescue & Recovery",
    "Survival & Escape",
    "Research & Analysis",
  ],
  tones: [
    "Methodical & Unsettling",
    "Dreamlike & Disorienting",
    "Remote & Claustrophobic",
    "Awe-Struck & Fragile",
    "Paranoid & Evidence-Driven",
  ],
  sampleTitles: [
    "The Map That Drew Itself Overnight",
    "A Signal from the Survey Line",
    "What the Tides Remember",
    "The Missing Hour at Station Nine",
    "The Catalogue Has Added Our Names",
  ],
  incitingActors: [
    "a university field team that has stopped reporting in a familiar voice",
    "a harbour official receiving tomorrow's weather bulletins",
    "an antiquarian who found a family connection in a document older than the town",
    "a quarantine doctor who needs help without making a public report",
    "a fisherman who brought back a chart that does not match the coast",
    "a grieving survivor whose memories disagree with every photograph",
  ],
  objectiveTypes: [
    "Determine why several witnesses remember mutually exclusive events",
    "Recover an expedition before its final transmission becomes true",
    "Contain an anomaly without destroying the evidence needed to understand it",
    "Trace a recurring symbol through archives, maps, and recent disappearances",
    "Decide whether a discovery should be published, hidden, or used as bait",
    "Find the source of a signal that has begun appearing in ordinary broadcasts",
  ],
  locationTypes: [
    "a coastal town where every street map loses one block after sundown",
    "a university archive with a floor omitted from the building plans",
    "a weather station built above a newly exposed cave system",
    "a research vessel stranded where the sea should be shallow",
    "an observatory whose instruments have tracked the same object for centuries",
    "a boarding house used by every expedition into the nearby hills",
  ],
  npcRoles: [
    "the careful investigator who knows which fact cannot be written down",
    "the field researcher who has returned with a gap in their memory",
    "the local witness whose impossible account is nevertheless useful",
    "the administrator protecting an institution by suppressing its own records",
    "the survivor who understands the threat but fears being believed",
  ],
  threatTypes: [
    "an anomaly that changes its rules when accurately described",
    "a research society treating public safety as an inconvenience",
    "a pattern spreading through maps, dreams, and navigation records",
    "a remote community maintaining a bargain it no longer understands",
    "a signal that recruits listeners by answering their private questions",
    "a containment system that is beginning to classify people as part of the problem",
  ],
  discoveryTypes: [
    "a field notebook whose later pages are written in the reader's hand",
    "a tide chart predicting events inside a locked building",
    "a photograph in which the missing person is visible behind the camera",
    "an astronomical plate that records a star absent from the sky",
    "a shipping manifest for cargo that was never loaded but has been delivered",
    "a transcript of a conversation the party has not had yet",
  ],
  complicationTypes: [
    "the most reliable witness becomes unreliable after seeing the same evidence again",
    "the institution funding the investigation wants a result it can safely bury",
    "a containment measure protects the town while trapping someone innocent inside",
    "the clue that solves one contradiction creates two more",
    "the party learns that investigating has made them visible to the phenomenon",
  ],
  rewardTypes: [
    "a complete account of a mystery that can still save someone",
    "the trust of a survivor who can identify future warning signs",
    "a tool for detecting the anomaly before it changes the landscape",
    "access to a guarded archive and the obligation that comes with it",
    "one stabilising answer that makes a larger question impossible to ignore",
  ],
  outcomeTypes: [
    "The immediate danger is contained, but the evidence now points elsewhere",
    "The truth is made public; the community must decide what to do with it",
    "The missing people return, changed in a way that is not immediately hostile",
    "The anomaly is understood well enough to avoid, not to defeat",
    "The institution survives, but its official history cannot be trusted again",
  ],
  hooks: [
    "A courier delivers a sealed field report addressed to the party in a hand matching one member's writing.",
    "The town's radio station broadcasts a calm evacuation order that nobody else appears to hear.",
    "A local scholar hires the party to verify an artefact before a private collector removes it from the country.",
    "A rescue beacon begins transmitting from an expedition that disappeared years ago.",
  ],
};
