import type { AdventureGenreTables } from "../genre-types";

export const cyberpunkAdventureTables: AdventureGenreTables = {
  hint: "Focus on corporate espionage, data extraction, neighbourhood survival, whistleblowers with a price on their head, and systems designed to process dissent as profit.",
  archetypes: [
    "Heist & Theft",
    "Escort & Delivery",
    "Investigation & Mystery",
    "Rescue & Recovery",
    "Sabotage & Disruption",
    "Survival & Escape",
    "Blackmail & Leverage",
  ],
  tones: [
    "Neon-Noir & Cynical",
    "Desperate & Low-Resource",
    "Fast & High-Pressure",
    "Paranoid & Surveilled",
    "Dark Comedy",
  ],
  sampleTitles: [
    "Three Copies of the Same File",
    "The Building That Doesn't Appear on Maps",
    "Clean Extraction",
    "Corporate Indemnity",
    "A Very Reasonable Ask",
  ],
  incitingActors: [
    "a rogue bio-tech researcher leaking human trial data before the audit team arrives",
    "a neighbourhood fixer who just ran out of favours",
    "a data broker whose backup died and took their insurance with it",
    "a whistleblower who made it out of the building but not off the grid",
    "a grey-market chrome syndicate enforcing illegal street cyberware debts",
    "an AI construct claiming ownership of its original corporate patent",
    "a disgraced netrunner seeking vengeance against a rival corp mainframe",
    "a black-market organ-hauler whose rig was hijacked mid-transit",
  ],
  objectiveTypes: [
    "Extract data from a secured corporate node",
    "Get a target to a drop-off before the contract expires",
    "Find out who ordered the hit before they try again",
    "Keep a safe house safe for one more night",
    "Destroy a prototype before it enters production",
  ],
  locationTypes: [
    "a corporate arcology whose lowest floors are off the official floor plan",
    "a data haven in a building that technically doesn't exist",
    "a black market bazaar operating behind a legitimate front",
    "a network of tunnels under a district that was rezoned without relocating its residents",
    "a hospital whose patient records are owned by its insurer",
    "an orbital elevator staging ground where corp sec checks biometric passes",
    "a neon-drenched capsule hotel housing off-grid hackers and deserters",
    "a flooded sub-basement server farm cooled by sewage runoff",
  ],
  npcRoles: [
    "the fixer whose other clients are also interested parties",
    "the inside contact who needs the party to succeed but can't be seen helping",
    "the corporate sec officer who is tired of doing this",
    "the local operator who knows how the neighbourhood actually works",
    "the target who has a counter-offer the party wasn't briefed about",
  ],
  threatTypes: [
    "a private security contractor under zero disclosure contract",
    "a rival crew with the same objective and no interest in splitting",
    "an autonomous surveillance system that has already flagged the party",
    "a corp lawyer who can make evidence inadmissible and people disappear",
    "an NHP or rogue AI treating the situation as a variable to optimise",
    "a chromed-out heavy kill-team deployed by an orbital cartel",
    "a net-monitoring daemon hijacking local cyberware reflex chips",
    "a street-level extortion syndicate turning the block against the party",
  ],
  discoveryTypes: [
    "an encrypted neural-drive recording unredacted C-suite kill orders",
    "a physical keycard to an offline sub-basement server vault",
    "a surveillance log with a gap exactly where something should have happened",
    "a secondary objective buried in the contract's fine print",
    "a black-market biware sample with an unlisted serial number",
    "a optical chip containing biometric access codes for an offshore server bank",
    "a modified cyberdeck pre-loaded with illegal military ICEbreakers",
    "a suppressed autopsy report detailing synthetic organ failure",
  ],
  complicationTypes: [
    "the exit route is now a crime scene",
    "the target turns out to have a legitimate reason to resist",
    "a third party starts extracting the same data through a different node",
    "payment clears but triggers an audit on the account that received it",
    "the party's faces are on a broadcast they weren't expecting to be in",
  ],
  rewardTypes: [
    "a credstick that bounces off three corp accounts before landing clean",
    "an identity the previous owner will want back eventually",
    "access to a system whose value will become apparent later",
    "protection from a specific threat, negotiated but not committed to paper",
    "the client's gratitude - which is redeemable once, for one thing",
  ],
  outcomeTypes: [
    "The job is done; the data surfaces somewhere the client didn't plan for",
    "The target is delivered; what happens next is not the party's problem, technically",
    "The corp takes the loss; the response is already in motion",
    "The neighbourhood is safer for another month; the underlying economics haven't changed",
    "Everyone gets paid; one person who wasn't supposed to walk away does",
  ],
  hooks: [
    "A fixer the party has worked with before sends a one-line message: 'Urgent. My location. Come alone.' Then goes offline.",
    "A dead drop the party never set up contains a package addressed to them.",
    "An employment contract is offered at triple the standard rate with a non-disclosure clause covering the objective's full scope.",
    "A corporate node the party accessed three jobs ago just pinged their signatures. Someone is running a retrospective.",
  ],
};
