import type { AdventureGenreTables } from "../genre-types";

export const darkFantasyAdventureTables: AdventureGenreTables = {
  hint: "Focus on corruption, body horror, cursed bloodlines, hollow institutions, and the cost of survival in a world where hope is a liability.",
  archetypes: [
    "Investigation & Mystery",
    "Hunt & Pursuit",
    "Survival & Escape",
    "Rebellion & Uprising",
    "Ritual & Containment",
    "Sacrifice & Bargain",
  ],
  tones: [
    "Grim & Hopeless",
    "Paranoid & Claustrophobic",
    "Tragic & Morally Corrupting",
    "Bleak & Fatalistic",
    "Horrifying & Relentless",
  ],
  sampleTitles: [
    "Mercy of the Red Court",
    "The Last Thing Kindness Cost",
    "When the Wards Failed",
    "Blighted by Blood",
    "Before the Night Finishes Its Work",
  ],
  incitingActors: [
    "a witch-hunter with too much authority and too little restraint",
    "a plague doctor who stopped asking about cures",
    "a cult that has been operating inside the church for decades",
    "a noble house rotting from a curse they refused to acknowledge",
    "a survivor of something that should not have left survivors",
  ],
  objectiveTypes: [
    "Contain a corruption before it spreads to the next settlement",
    "Discover the source of a recurring disappearance",
    "Stop a ritual whose participants don't know they're involved",
    "Protect the last witness to a covered-up atrocity",
    "Recover a soul-bound artefact before its owner is consumed",
  ],
  locationTypes: [
    "a city that voted to seal its poorest district inside the walls",
    "a monastery that has not sent word in three months",
    "a village where the children have all gone quiet at the same time",
    "a courthouse whose judge has not left the building in a year",
    "a prison whose wardens answer to no visible authority",
  ],
  npcRoles: [
    "the inquisitor whose methods are the second problem",
    "the local priest who knows and has done nothing",
    "the condemned who is actually guilty of something worse",
    "the child with information no child should have",
    "the collaborator who thinks they negotiated fair terms",
  ],
  threatTypes: [
    "an entity that has spent years learning to sound human",
    "a despot whose enforcers are too afraid to disobey",
    "a bloodline curse passed down through genuine love",
    "a mob that has convinced itself it's delivering justice",
    "a bureaucratic system that processes atrocity without malice",
  ],
  discoveryTypes: [
    "a confession written in a hand that trembled",
    "evidence the victim knew the attacker and trusted them",
    "a list of names whose owners have all since died of 'illness'",
    "a room that has been cleaned too recently",
    "a map of exits that were sealed before the incident began",
  ],
  complicationTypes: [
    "the party's intervention makes the situation visible to the wrong people",
    "stopping the threat requires doing something that cannot be undone",
    "the person they were protecting turns out to be an active participant",
    "the institution they reported to was complicit",
    "the corruption is not the enemy — the attempt to cure it is",
  ],
  rewardTypes: [
    "survival without further debt",
    "the name of the next link in the chain",
    "a piece of proof too dangerous to use publicly",
    "the gratitude of someone who cannot afford to show it",
    "a cursed gift from something that genuinely wanted to help",
  ],
  outcomeTypes: [
    "The immediate threat is ended but the system that enabled it is intact",
    "The party stops the corruption but one of them carries it now",
    "The truth comes out — and the people who needed to hear it don't believe it",
    "The ritual is stopped; the thing it would have summoned will try again through someone else",
    "Everyone survives. Nobody is unaffected.",
  ],
  hooks: [
    "Livestock have been dying in a circle that has been moving inward toward the village for six nights.",
    "A local official has been asking questions about the party — specifically about how they handle 'difficult situations'.",
    "A body was found arranged in a way that matches a pattern from an event the party witnessed somewhere else.",
    "Someone left a sealed letter at the party's lodging. It contains names, dates, and a single instruction: stop them.",
  ],
};
