import type { AdventureGenreTables } from "../genre-types";

export const fantasyAdventureTables: AdventureGenreTables = {
  hint: "Focus on lost heirs, stolen relics, ancient curses, rival guilds, and the weight of prophecy in a world where magic is real but costly.",
  archetypes: [
    "Rescue & Recovery",
    "Investigation & Mystery",
    "Escort & Delivery",
    "Heist & Theft",
    "Rebellion & Uprising",
    "Hunt & Pursuit",
    "Diplomatic Mission",
    "Survival & Escape",
  ],
  tones: [
    "Heroic & High Stakes",
    "Gritty & Low Fantasy",
    "Dark & Morally Ambiguous",
    "Whimsical & Folkloric",
    "Political & Intrigue-Heavy",
  ],
  sampleTitles: [
    "The Heir Who Vanished",
    "Blood of the Broken Compact",
    "The Last Road to Ashenveil",
    "What the Ruins Remember",
    "A Price in Silver and Silence",
  ],
  incitingActors: [
    "a disgraced noble family",
    "an ancient order whose membership has dwindled to three",
    "a merchant guild hiding a second set of books",
    "a dying oracle with only one prophecy left",
    "a local warlord one misstep from igniting a war",
  ],
  objectiveTypes: [
    "Recover a stolen relic before it is used",
    "Expose a conspiracy before its architects escape",
    "Escort a witness to safety",
    "Break a siege or blockade",
    "Prevent a ritual from completing",
    "Find the truth behind a disappearance",
  ],
  locationTypes: [
    "a walled market city straining under occupation",
    "a border keep that controls the only mountain pass",
    "a drowned village whose bell still rings at low tide",
    "a forest shrine abandoned after its priest was murdered",
    "a traveller's inn sitting at a crossroads no one admits to",
  ],
  npcRoles: [
    "the reluctant informant who knows too much",
    "the contact who turns out to be a double agent",
    "the local lord whose neutrality is a lie",
    "the survivor who has been hiding in plain sight",
    "the rival party with the same objective and different methods",
  ],
  threatTypes: [
    "a sorcerer who believes the ends justify any means",
    "a cult whose members have infiltrated every institution",
    "mercenaries loyal to coin, not cause",
    "a monster awakened by careless excavation",
    "a noble house willing to start a war to protect a secret",
  ],
  discoveryTypes: [
    "a letter that proves the true heir is still alive",
    "a ledger recording payments to someone officially dead",
    "a map with a route that shouldn't exist",
    "a wound that couldn't have been made by any weapon sold locally",
    "a name erased from every official record — except one",
  ],
  complicationTypes: [
    "the person they were sent to rescue doesn't want to be found",
    "a faction the party thought was neutral picks a side",
    "the agreed-upon payment has already been spent",
    "the safe route is no longer safe",
    "a clock starts that nobody knew was running",
  ],
  rewardTypes: [
    "a deed to land the previous owner will want back",
    "political favour worth more than gold in the right city",
    "a relic that works, but not the way the party expects",
    "knowledge of a secret the wrong people would kill for",
    "a debt called in at the worst possible moment",
  ],
  outcomeTypes: [
    "The threat is removed but the power vacuum it leaves is just as dangerous",
    "The party achieves the objective but one NPC pays for it",
    "The conspiracy is exposed but the architect escapes",
    "The war is prevented but the underlying cause festers",
    "The relic is recovered — and immediately becomes a new problem",
  ],
  hooks: [
    "A childhood friend of one of the party members has gone missing in this city.",
    "The last three people to ask the same question the party is asking have not been seen since.",
    "A reward notice is posted — the listed sum is too high, which usually means the job is too dangerous to fill honestly.",
    "The party's contact was found dead this morning, with a note naming them as the next to die.",
  ],
};
