import type { AdventureGenreTables } from "../genre-types";

export const gothicHorrorAdventureTables: AdventureGenreTables = {
  hint: "Focus on old houses with memories, bloodlines that don't end cleanly, the clergy that has made arrangements with the wrong parties, and the slow realisation that the monster is also the victim.",
  archetypes: [
    "Investigation & Mystery",
    "Hunt & Pursuit",
    "Survival & Escape",
    "Ritual & Containment",
    "Rescue & Recovery",
    "Diplomatic Mission",
  ],
  tones: [
    "Atmospheric & Dread-Soaked",
    "Tragic & Sympathetic Horror",
    "Paranoid & Claustrophobic",
    "Gothic Romance",
    "Relentless & Escalating",
  ],
  sampleTitles: [
    "The House That Doesn't Let You Leave",
    "Three Generations of the Same Mistake",
    "What the Will Stipulates",
    "A Covenant Made Before the Party Was Born",
    "The Sound the Village Makes at Night",
  ],
  incitingActors: [
    "an ancient noble lineage whose curse has matured",
    "a church that has been managing the creature rather than eliminating it",
    "a solicitor with a letter to deliver and a very good reason not to",
    "a household whose loyalty to their employer has outlasted their employer",
    "a monster that has decided to stop hiding",
  ],
  objectiveTypes: [
    "Determine what the creature is and why it has started acting differently",
    "Find and seal the covenant that is keeping the horror anchored",
    "Recover someone from inside the estate before the estate is sealed",
    "Discover the truth behind a disappearance the authorities have filed and closed",
    "Survive until dawn under conditions that were not fully disclosed",
  ],
  locationTypes: [
    "an estate that has belonged to the same family for longer than the records go",
    "a village that prospers in ways that cannot be explained by its visible economy",
    "a sanitarium where one of the patients is the only person telling the truth",
    "a cathedral whose lower levels are not discussed in the official history",
    "a coach road where travellers arrive at both ends but not the middle",
  ],
  npcRoles: [
    "the heir who summoned help but cannot say what for without sounding mad",
    "the old servant who has seen everything and is choosing what to mention",
    "the local priest whose jurisdiction includes arrangements the bishop doesn't know about",
    "the doctor whose patient files have a category that doesn't appear in medical literature",
    "the creature, who has a perspective on events that the party has not considered",
  ],
  threatTypes: [
    "a predator that has learned to use the institutions around it as camouflage",
    "a lineage curse that transfers rather than ends",
    "a covenant that the current generation didn't sign but is bound by",
    "the community's collective decision not to know",
    "a monster that is also right about something",
  ],
  discoveryTypes: [
    "a portrait whose subject is not where the portrait says they should be",
    "a household account recording purchases that have no innocent explanation",
    "a letter from the previous investigator to whoever comes next",
    "a room that is not on the house plan and cannot be entered the same way twice",
    "a testimony that matches no other record — except one from seventy years ago",
  ],
  complicationTypes: [
    "the creature is not the only thing in the house that does not want them here",
    "the client's actual objective is not the one they described",
    "one of the party has been touched by the curse without noticing",
    "the only method of ending the threat requires something the party is not willing to do",
    "morning does not come at the expected time",
  ],
  rewardTypes: [
    "a bequest from the estate that will complicate their lives in interesting ways",
    "the specific knowledge of how to do this again, if necessary",
    "the creature's gratitude — conditional and temporary, but real",
    "evidence of wrongdoing that no court in this jurisdiction will accept",
    "one question answered, at the cost of three more",
  ],
  outcomeTypes: [
    "The creature is destroyed; the conditions that made it are still in place",
    "The covenant is broken; what it was holding back is no longer held back",
    "The lineage ends here; what it became does not necessarily end with it",
    "The party survives; the house decides this was interesting and waits",
    "The truth is known; nothing about knowing it makes the situation better",
  ],
  hooks: [
    "A solicitor arrives at the party's current lodging with a letter of engagement and the firm instruction not to ask who the client is.",
    "Three travellers set out from the village inn toward the estate on the hill. One returned. She is unwilling to say what happened to the others but is willing to pay.",
    "A childhood friend of one of the party members has sent a letter. The handwriting is theirs. The phrasing is not.",
    "The estate has been advertising for staff at wages that are extraordinary. The previous holders of the positions are not available for reference.",
  ],
};
