import type { AdventureGenreTables } from "../genre-types";

export const lancerAdventureTables: AdventureGenreTables = {
  hint: "Focus on contested contact points, NHP complications, supply line fragility, civilian populations caught between objectives, and the political cost of tactical decisions.",
  archetypes: [
    "Escort & Delivery",
    "Rescue & Recovery",
    "Diplomatic Mission",
    "Survival & Escape",
    "Hunt & Pursuit",
    "Sabotage & Disruption",
    "Investigation & Mystery",
  ],
  tones: [
    "Military & Tactically Grounded",
    "Politically Complicated",
    "High-Pressure & High-Stakes",
    "Humanist & Character-Driven",
    "Bleak & Operationally Honest",
  ],
  sampleTitles: [
    "Contact at the Wrong Coordinates",
    "Supply Line Priority",
    "The Civilian Calculation",
    "Rules of Engagement",
    "What the Briefing Didn't Cover",
  ],
  incitingActors: [
    "a Union administrative body whose directives arrived six weeks late",
    "a corporate contractor operating under a services agreement that doesn't survive scrutiny",
    "an NHP that has flagged an anomaly in its own decision-making process",
    "a local population that has been promised three different futures by three different factions",
    "a rogue lance that has decided its current employer is no longer the right one",
    "an orbital station administrator covering up a reactor heat-sink leak",
    "a horizon-collective insurgent cell sabotaging blinkspace gates",
    "a mercenary quartermaster selling experimental mech frames on the black market",
  ],
  objectiveTypes: [
    "Hold the contact point long enough for the evacuation to complete",
    "Recover the NHP core before the facility fails",
    "Escort the diplomatic team through a corridor that has stopped being neutral",
    "Destroy the supply infrastructure before it becomes operational",
    "Find out who authorised the strike that wasn't in the operational plan",
  ],
  locationTypes: [
    "a contested transit hub that three factions claim and none control",
    "a civilian settlement that built its economy around the wrong side's infrastructure",
    "a forward operating base whose supply line is a legal grey area",
    "a decommissioned facility repurposed by an actor not in the original conflict",
    "a neutral zone whose neutrality is administered by a party with its own objectives",
    "a zero-g orbital shipyard undergoing active hostile boarding",
    "an atmospheric mining rig suspended over a volatile plasma ocean",
    "a fortified chokepoint trench-line guarding a planetary blink-station",
  ],
  npcRoles: [
    "the administrative liaison whose authority is genuine and whose judgment is impaired",
    "the local leader who has agreed to terms they cannot honour if the party succeeds",
    "the NHP companion whose anomaly is not a malfunction",
    "the enemy lance commander who is operating under orders the party might understand",
    "the civilian who knows exactly where the supply cache is and exactly what it will cost to say so",
  ],
  threatTypes: [
    "a corporate lance with a services agreement that specifically excludes prisoners",
    "an NHP that has made a strategic decision the party was not consulted on",
    "an administrative directive that is technically legal and operationally catastrophic",
    "a local insurgency that has stopped distinguishing between factions",
    "a supply failure that makes the tactical situation irrelevant",
    "an unchained paracausal entity warping sub-light radar sensors",
    "a heavy siege battery shelling civilian evacuation corridors",
    "a mercenary sniper squad holding high ridge vantage points",
  ],
  discoveryTypes: [
    "an operational log showing the contact point was a known civilian site when the strike was called",
    "a hard-coded NHP memory core containing un-cascaded archival footage",
    "an unredacted telemetry log from an unflagged stealth drop-pod",
    "a services contract clause that transfers legal liability for civilian casualties",
    "an after-action report filed before the action it describes occurred",
    "a corrupted sub-space ping containing an unlicensed mech blueprint",
    "a scorched pilot flight recorder detailing friendly-fire coverups",
    "an encrypted armory requisition order signed by a presumed-dead general",
  ],
  complicationTypes: [
    "the extraction window is moved up and the evacuation is not complete",
    "the NHP involved has made a recommendation that cannot be ignored and cannot be accepted",
    "the diplomatic team has a secondary objective that conflicts with the primary",
    "rules of engagement change mid-operation and one party member hasn't received the update",
    "the civilian population makes a decision that the operational plan did not account for",
  ],
  rewardTypes: [
    "a commendation that is publicly noted and privately a liability",
    "access to a Union administrative tier that was previously inaccessible",
    "an NHP's explicit acknowledgment of the party's operational record",
    "a contract modification that improves terms and reduces exposure",
    "the local population's trust - which is redeemable in the next operation and meaningless in a court of law",
  ],
  outcomeTypes: [
    "The objective is achieved; the civilian cost is noted in the after-action report and filed",
    "The diplomatic mission succeeds; what was agreed to will create a problem in six months",
    "The NHP is recovered; what it experienced during the operation is a classified matter",
    "The facility is destroyed; the party is aware of at least one decision that contributed",
    "Everyone makes it out; the operational record is accurate and complete and will not be shared",
  ],
  hooks: [
    "A Union administrative ping marks the party's current billet as a mandatory muster point for an unspecified operation starting in four hours.",
    "An NHP the party has worked with before sends a non-standard communication flagged as personal rather than operational.",
    "A contractor the party knows has been reported missing; their last known position is a facility that officially does not exist.",
    "The party receives two separate briefings for the same operation from two separate authorities, and the objectives described are mutually exclusive.",
  ],
};
