import type { AdventureGenreTables } from "../genre-types";

export const modernConspiracyAdventureTables: AdventureGenreTables = {
  hint: "Focus on whistleblowers, surveillance overreach, institutions doing exactly what they were designed to do, and the personal cost of knowing something you were not supposed to find.",
  archetypes: [
    "Investigation & Mystery",
    "Survival & Escape",
    "Rescue & Recovery",
    "Heist & Theft",
    "Escort & Delivery",
    "Blackmail & Leverage",
    "Sabotage & Disruption",
  ],
  tones: [
    "Paranoid & Tense",
    "Noir & Cynical",
    "Thriller & Fast-Moving",
    "Bleak & Institutional",
    "Dark Comedy",
  ],
  sampleTitles: [
    "The Source That Went Quiet",
    "Documented and Denied",
    "What the Agency Lost Track Of",
    "Three Degrees of Separation",
    "An Informal Arrangement",
  ],
  incitingActors: [
    "a government agency running a programme it has not authorised in writing",
    "a corporation with a second set of financials and a legal team on retainer",
    "a whistleblower who has the documents but not the means to use them safely",
    "a journalist whose source just went dark",
    "an operative who was supposed to stay buried and has decided not to",
  ],
  objectiveTypes: [
    "Get the document to someone who can act on it before the window closes",
    "Find out what happened to the source",
    "Keep the evidence safe long enough for the story to run",
    "Identify who inside the institution is feeding information out",
    "Expose the programme without exposing the people who helped expose it",
  ],
  locationTypes: [
    "an office building with a floor that doesn't appear in the directory",
    "a data centre whose client list is redacted in its own internal records",
    "a safe house that is safe until it isn't",
    "an archive whose most useful section is in boxes marked for destruction",
    "a foreign city where the party has no jurisdiction and limited cover",
  ],
  npcRoles: [
    "the inside contact who can confirm but cannot be seen to",
    "the attorney whose advice is professional and whose interest is personal",
    "the field operative who wants out and thinks the party can get them there",
    "the agency handler whose official brief and actual objective are different documents",
    "the editor who will run the story if the sourcing is solid and is still alive to do so",
  ],
  threatTypes: [
    "a surveillance apparatus that has been activated and is looking specifically for the party",
    "a legal team that treats evidence as a liability to be managed",
    "an operative who was trained by the same people who trained the party's ally",
    "a third-party actor who wants the information buried for unrelated reasons",
    "the institution itself, which does not need to be malicious to be dangerous",
  ],
  discoveryTypes: [
    "a document that is legitimate and whose implications nobody has worked through yet",
    "a connection between two apparently unrelated programmes that share a budget line",
    "a person listed as deceased who signed something three months ago",
    "a surveillance record that proves the surveillance began before the investigation",
    "an internal communication that makes the official account impossible",
  ],
  complicationTypes: [
    "the party's secure channel is compromised",
    "the evidence is real but inadmissible under current legal framework",
    "a parallel investigation by a different agency intersects with the party's work",
    "the source recants, for reasons that are understandable and devastating",
    "publishing the information harms someone the party did not intend to harm",
  ],
  rewardTypes: [
    "immunity — negotiated, conditional, and currently holding",
    "the story runs; whether anything changes is a separate question",
    "a contact inside the institution who owes the party one",
    "classified access to a file that answers one question and opens five",
    "enough money to disappear for six months and decide what to do next",
  ],
  outcomeTypes: [
    "The information is public; the institution adjusts and continues",
    "The source is safe; the programme that targeted them is suspended pending review",
    "The story runs; two people responsible are promoted and one is charged",
    "The evidence is secured; the case is still open",
    "Everyone is alive; the party is now on a list they will not be told about",
  ],
  hooks: [
    "A journalist the party knows professionally sends a single encrypted message and goes offline.",
    "A public records request the party filed eight months ago is suddenly answered — in person, by someone who is not from the records office.",
    "The party's email contains a message from an address that does not exist, containing a file that does not have a name.",
    "A source reaches out to say they have been approached by someone asking specific questions about the party.",
  ],
};
