import type { AdventureGenreTables } from "../genre-types";

export const optimisticSciFiAdventureTables: AdventureGenreTables = {
  hint: "Focus on first contact challenges handled with good faith, expedition complications that test cooperation, discoveries that are genuinely wondrous, and the work of building something new.",
  archetypes: [
    "First Contact",
    "Rescue & Recovery",
    "Diplomatic Mission",
    "Investigation & Mystery",
    "Escort & Delivery",
    "Survival & Escape",
    "Exploration & Discovery",
  ],
  tones: [
    "Wonder & Discovery",
    "Humanist & Cooperative",
    "Hopeful & High-Stakes",
    "Intellectually Curious",
    "Warm & Character-Centred",
  ],
  sampleTitles: [
    "The Signal Worth Following",
    "A Language We Haven't Met Yet",
    "Third Contact Protocol",
    "What the Survey Didn't Anticipate",
    "The Crew That Stayed",
  ],
  incitingActors: [
    "a newly contacted civilisation whose communication framework is genuinely alien",
    "an expedition that made a discovery and has not yet worked out what it means",
    "a crew that has been in the field longer than their mission parameters covered",
    "a research team whose ethical framework is being stress-tested by what they found",
    "a contact species that has decided to initiate, on their own terms",
  ],
  objectiveTypes: [
    "Establish communication and basic trust with a species that is waiting to see whether to bother",
    "Reach the lost expedition before they adapt to conditions in a way that becomes permanent",
    "Bring back information about a discovery that has implications the institution needs to think through",
    "Mediate between two groups whose misunderstanding has become an incident",
    "Find a way through a situation that the original mission parameters did not cover",
  ],
  locationTypes: [
    "a world that is genuinely unlike anything in the catalogue, in specific interesting ways",
    "a station at the edge of mapped space that has been there longer than any record accounts for",
    "a contact zone where two civilisations have been exchanging signals for a generation without making progress",
    "an expedition base that was established under one set of assumptions and is operating under a different reality",
    "a vessel that has gone somewhere it was not designed to go and has not come back",
  ],
  npcRoles: [
    "the expedition linguist who is one breakthrough away from something and knows it",
    "the contact specialist whose professional experience is making their instincts reliable and their certainty dangerous",
    "the crew member who has been out here long enough to stop being the person they were briefed as",
    "the contact species representative who is taking a significant personal risk by engaging",
    "the mission commander whose authority is clear and whose confidence in the original plan is declining",
  ],
  threatTypes: [
    "a communication breakdown that neither side is equipped to recognise as solvable",
    "a discovery whose implications have created a genuine ethical impasse",
    "an environmental challenge that the mission equipment was not designed for",
    "an organisational misunderstanding that has been processed as a hostile act",
    "time — the window for this encounter, negotiation, or rescue has a hard edge",
  ],
  discoveryTypes: [
    "a signal that is clearly structured and clearly not produced by any known origin",
    "physical evidence that the expedition's model of what they found is wrong in an important way",
    "a contact attempt that predates the party's arrival by a timeframe that changes the context",
    "a crew record showing when the expedition's assumptions began to drift from their observations",
    "a translation breakthrough that reframes every previous exchange",
  ],
  complicationTypes: [
    "the discovery has implications that the mission parameters do not address and that cannot be deferred",
    "a communication attempt is interpreted as an escalation",
    "the crew member whose skills the party needs most is the one dealing with a crisis",
    "the institutional response to the party's report is slower than the situation",
    "the contact species makes a decision that is logical from their framework and genuinely dangerous from the party's",
  ],
  rewardTypes: [
    "a contact established — fragile, provisional, and genuinely important",
    "data that will reshape the field's understanding of the discovery",
    "the crew's return, which matters to specific people in specific ways",
    "a technological exchange whose value is not immediately obvious",
    "a protocol that makes the next contact attempt more likely to succeed",
  ],
  outcomeTypes: [
    "Contact is established; the relationship will require ongoing investment to maintain",
    "The discovery is brought back; understanding it will take longer than the party was given",
    "The crew is recovered; what changed for them in the field has not yet been fully accounted for",
    "The misunderstanding is resolved; both sides now know something they didn't about the other",
    "The situation is navigated successfully; the party has made something possible that wasn't before",
  ],
  hooks: [
    "A signal the party picked up on a routine survey turns out to be a response to a transmission that was sent before any of them were born.",
    "An expedition checks in, on schedule, and the check-in is word-for-word identical to the previous seventeen.",
    "The party receives a contact request — in their own language, from a species that should not have access to it.",
    "A discovery the party made on a previous mission turns out to have been observed. Someone is asking to talk about it.",
  ],
};
