import type { AdventureGenreTables } from "../genre-types";

export const pirateAdventureTables: AdventureGenreTables = {
  hint: "Focus on prize ships, port politics, naval pursuits, letters of marque running out at the wrong moment, and the economics of keeping a crew together.",
  archetypes: [
    "Heist & Theft",
    "Hunt & Pursuit",
    "Escort & Delivery",
    "Rescue & Recovery",
    "Diplomatic Mission",
    "Survival & Escape",
    "Rebellion & Uprising",
  ],
  tones: [
    "Swashbuckling & High-Energy",
    "Gritty & Nautical",
    "Political & Port-Side Intrigue",
    "Treasure-Hunt & Discovery",
    "Desperate & Crew-Focused",
  ],
  sampleTitles: [
    "The Prize and the Provenance",
    "Last Port Before the Tradewinds",
    "Letters of Marque, Expired",
    "The Cargo That Bought the Ship",
    "What the Wreckers Found",
  ],
  incitingActors: [
    "a merchant who wants a competitor's cargo retrieved without asking how",
    "a naval commander who wants something done that her commission won't cover",
    "a port governor with a problem that officially doesn't exist",
    "a first mate whose captain has gone somewhere the crew was not told",
    "a rogue captain running under a false flag and a grudge",
    "a wreckers' guild leader orchestrating artificial lighthouse blackouts",
    "a rum smuggler whose hidden cove stash was claimed by an East Indies fleet",
    "a marooned quartermaster carrying the key to a legendary buccaneer vault",
  ],
  objectiveTypes: [
    "Take a prize before another ship reaches it",
    "Get through the blockade with the cargo intact",
    "Find the ship that vanished without a distress signal",
    "Recover the chart before it reaches the buyer",
    "Negotiate a truce between two captains on a collision course",
  ],
  locationTypes: [
    "a free port that operates on the principle that everyone's money is equally legal",
    "a naval anchorage whose commander is open to arrangements off the record",
    "a hidden anchorage whose location is the most valuable thing it contains",
    "a merchant vessel whose listed cargo and actual cargo are different weights",
    "a wrecked ship on a reef that nobody has been able to reach and return from",
    "a fortified island sea-fort bristling with captured Spanish cannons",
    "a tidal cavern hideout accessible only during a six-minute window at dead low tide",
    "a smuggler's floating market barge moored in foggy international waters",
  ],
  npcRoles: [
    "the fence whose discretion has a price structure",
    "the naval officer who would prefer the situation resolved quietly",
    "the experienced pilot who knows these waters and what moves in them",
    "the captured merchant captain with information about what was in the hold",
    "the rival captain who is not an enemy but is definitely not an ally",
  ],
  threatTypes: [
    "a naval patrol running a dragnet that is not going away",
    "a rival crew with a faster ship and the same destination",
    "a storm that is neither predictable nor survivable with current rigging",
    "a port that has decided the party's activities are bad for business",
    "a letter of marque that names someone in the party by name",
    "a curse-bound ghost-cutter hunting ships that fly no flag",
    "a mutinous crew seizing control of the gun deck mid-chase",
    "a shore-battery garrison equipped with heavy incendiary mortars",
  ],
  discoveryTypes: [
    "a brass-bound spyglass inscribed with coordinates to a submerged royal galleon",
    "a blood-stained sea chart showing uncharted reef passages",
    "a letter from a naval authority to a pirate captain that predates the current war",
    "a flag in the hold that belongs to a ship that was reported sunk",
    "a sea-chest containing a wax-sealed privateer's commission in a dead king's name",
    "a carved ivory compass whose needle points to living blood rather than north",
    "a sealed barrel of black-market gunpowder stamped with royal navy armory seals",
    "a ship's log recording a sea-serpent encounter off Dead Man's Cay",
  ],
  complicationTypes: [
    "the prize is carrying passengers who were not in the briefing",
    "the port they were counting on is under a different flag than it was last month",
    "the ship they were pursuing is not running - it is herding",
    "the cargo is not what it was described as and the buyer has been told",
    "the crew has a vote and the vote is not going the way the party expected",
  ],
  rewardTypes: [
    "a share of prize money that creates as many enemies as it settles debts",
    "a chart worth more than any cargo on this route",
    "port access in a location that was previously closed to the party",
    "a letter of introduction from someone whose introduction opens doors",
    "the gratitude of a crew that will remember it the next time they are in port together",
  ],
  outcomeTypes: [
    "The prize is taken; holding it creates a problem as large as taking it",
    "The cargo arrives; the party learns what it was for",
    "The naval threat is evaded; it will regroup and return with better intelligence",
    "The negotiation succeeds; one party considers it the opening move in a longer game",
    "The crew makes it out; the ship does not, which creates a new set of immediate problems",
  ],
  hooks: [
    "A ship matching the description of a vessel the party knows to be sunk just sailed into port.",
    "A sealed commission addressed to the party's captain arrives at the dock with a vessel they are invited to take command of, no questions asked.",
    "A rival crew is offering double shares for anyone willing to transfer, effective immediately, for one job, destination undisclosed.",
    "The harbormaster asks to see the party privately and produces a document with their names on it that they never signed.",
  ],
};
