import type { AdventureGenreTables } from "../genre-types";

export const postApocAdventureTables: AdventureGenreTables = {
  hint: "Focus on resource scarcity, the brutal arithmetic of survival, communities built on what was salvaged, and the question of what is worth preserving from before.",
  archetypes: [
    "Survival & Escape",
    "Escort & Delivery",
    "Rescue & Recovery",
    "Hunt & Pursuit",
    "Rebellion & Uprising",
    "Salvage & Scavenging",
  ],
  tones: [
    "Bleak & Survivalist",
    "Desperate & High-Pressure",
    "Grim & Morally Compromising",
    "Quietly Hopeful",
    "Brutal & Unforgiving",
  ],
  sampleTitles: [
    "Eighty Miles to the Next Source",
    "What the Convoy Left Behind",
    "The People Who Stayed",
    "Bone-Dry and Running Out of Days",
    "Signal from the Old Grid",
  ],
  incitingActors: [
    "a raider faction that has organised into something more dangerous than raiders",
    "a settlement council that has started making unannounced decisions",
    "a supply runner who knows where the next cache is but cannot survive the route alone",
    "a survivor carrying something the wasteland has decided it wants",
    "a cult organised around something that actually works — which is the problem",
  ],
  objectiveTypes: [
    "Reach a supply cache before a competing group strips it",
    "Get a convoy through territory that has turned hostile",
    "Find out why a settlement stopped broadcasting",
    "Recover a person or piece of technology another group has decided to keep",
    "Protect a water source long enough for a community to relocate",
  ],
  locationTypes: [
    "a fortified settlement that controls the only clean water for sixty miles",
    "a pre-collapse facility that has been operating on backup power since the event",
    "a trade route chokepoint where three factions have overlapping claims",
    "a dead city that is genuinely uninhabited but rumoured to hold a working generator",
    "a mobile community living in a caravan that has not stopped moving in four years",
  ],
  npcRoles: [
    "the settlement leader whose decisions have kept everyone alive but at a cost",
    "the trader whose neutrality is a business model",
    "the child born after the collapse who has never seen a working toilet",
    "the defector from the raider group with information and no goodwill left",
    "the engineer who knows how to get the old systems running again, for a price",
  ],
  threatTypes: [
    "an organised raider confederation with logistics and a strategic objective",
    "a faction that has decided the settlement is in the wrong location",
    "environmental hazards that have been getting worse with no one to manage them",
    "a disease that the party may already be carrying",
    "scarcity itself — no villain, just arithmetic that doesn't work",
  ],
  discoveryTypes: [
    "a map to a cache that the person who hid it never came back to collect",
    "a log from before the collapse that explains something that was previously unexplained",
    "evidence that the collapse was not entirely accidental",
    "a working piece of technology with no surviving documentation",
    "a list of survivors that includes people everyone thought were dead",
  ],
  complicationTypes: [
    "the route is longer than anticipated and supplies are not",
    "a faction that was neutral has decided the party's success threatens them",
    "the objective is there but getting to it would cut off the escape route",
    "the person they came to help is now leading the opposition",
    "weather, terrain, or radiation makes the timetable impossible",
  ],
  rewardTypes: [
    "fuel, medicine, and clean water — in amounts that actually matter",
    "a safe passage agreement with a faction that enforces it",
    "a location for the next cache, passed on without a price tag",
    "a working tool that was irreplaceable before the collapse and still is",
    "the community's trust — which is redeemable and costs them something real",
  ],
  outcomeTypes: [
    "The immediate threat is removed; the underlying scarcity remains",
    "The convoy makes it through; the settlement it came from does not",
    "The supply is secured; the knowledge of its location makes everyone a target",
    "The community survives this season; next season is already in question",
    "The truth about the collapse comes out; there is no one left to hold accountable",
  ],
  hooks: [
    "A supply runner arrived at the settlement two days late, alone, and refuses to say where the rest of the convoy is.",
    "A settlement that has been broadcasting a steady signal for three years just went quiet.",
    "A cache marker the party left last year has been moved. Whoever moved it left a note: 'Come alone.'",
    "A faction the party has dealt with before is offering double the standard rate for an escort job with unusually vague parameters.",
  ],
};
