import type { AdventureGenreTables } from "../genre-types";

export const sciFiAdventureTables: AdventureGenreTables = {
  hint: "Focus on first contact gone wrong, corporate cover-ups, distress signals from ships that should have arrived months ago, and the ethics of exploration when survival is in the margins.",
  archetypes: [
    "Rescue & Recovery",
    "Investigation & Mystery",
    "Escort & Delivery",
    "Diplomatic Mission",
    "Survival & Escape",
    "Hunt & Pursuit",
    "Heist & Theft",
    "First Contact",
  ],
  tones: [
    "Tense & High Stakes",
    "Bleak & Survivalist",
    "Wonder & Discovery",
    "Political & Faction-Driven",
    "Paranoid & Isolated",
  ],
  sampleTitles: [
    "Signal from the Wrong Coordinates",
    "Salvage Rights",
    "The Gate That Opened Twice",
    "Derelict at System's Edge",
    "A Quiet Name on the Manifest",
  ],
  incitingActors: [
    "a corporation whose liability exposure is measured in star systems",
    "a colonial administration that misread a contact protocol",
    "a crew that made it back from somewhere they shouldn't have",
    "a research team whose last transmission cut out mid-sentence",
    "an AI that stopped responding to its operators three weeks ago",
    "a rogue deep-space mining outfit harvesting forbidden dark-matter ore",
    "a quarantined scientific director refusing to cut power to a singularity coil",
    "a free-trader syndicate smuggling bio-mechanical symbiotes across borders",
  ],
  objectiveTypes: [
    "Reach an installation before the window closes",
    "Recover the flight recorder before the corporation gets there first",
    "Make contact and establish whether the situation is still recoverable",
    "Extract a team before the facility fails completely",
    "Find out what the station was doing that isn't in the official reports",
  ],
  locationTypes: [
    "a generation ship drifting twenty AU off its registered course",
    "a research platform bolted to the underside of a gas giant moon",
    "a relay station whose crew rotation is eight months overdue",
    "a colony that is exactly where it should be but nobody has heard from",
    "a decommissioned vessel being used as something it was never designed for",
    "an orbital elevator station severed from its ground tether",
    "a subterranean alien vault uncovered by automated mining drills",
    "a derelict terraformer spewing un-breathable toxic gas into an enclosed dome",
  ],
  npcRoles: [
    "the lone survivor with a version of events that doesn't fit the evidence",
    "the corporate liaison with authority they haven't finished reading",
    "the indigenous contact who has met humans before and is not impressed",
    "the crew member who volunteered for this shift when no one else would",
    "the administrator who knew what was in the manifest and said nothing",
  ],
  threatTypes: [
    "an organism that found a pressure hull and decided it was home",
    "a security system still running the last protocol it received",
    "a crew whose shared trauma has curdled into something organised",
    "a rival salvage or recovery team with an overlapping objective",
    "a signal that looks like a distress call but functions as a lure",
    "a destabilizing spatial rift altering local time passage by hours",
    "an automated containment lockdown sealing quarters room by room",
    "a parasitic spore colony corrupting environmental life-support scrubbers",
  ],
  discoveryTypes: [
    "a log entry made after the official timestamp of the crew's death",
    "a sealed optical data crystal containing unredacted telemetry",
    "an alien bio-containment vial with a cracked outer seal",
    "a section of the ship that isn't on the manifest or the schematics",
    "a biological sample tagged with a species designation that doesn't exist",
    "an un-severed neural link recording a pilot's final seconds before hyperspace collapse",
    "a hidden cargo pod containing cryogenic stasis pods with unknown occupants",
    "a encrypted jump-gate key pre-programmed for an un-charted sector",
  ],
  complicationTypes: [
    "the extraction window closes sooner than the mission parameters allowed",
    "a faction that wasn't supposed to know about the mission is already on site",
    "the asset they came to recover is not what the briefing described",
    "one of the party's own systems begins behaving unexpectedly",
    "the situation is recoverable, but only if they leave someone behind",
  ],
  rewardTypes: [
    "clearance access to a system the party has needed for three missions",
    "the coordinates of something the corporation has been looking for longer than the party has existed",
    "a full pardon on a charge nobody mentioned when they were hired",
    "a piece of technology whose implications have not been thought through",
    "the truth - which is not worth anything to anyone who can act on it",
  ],
  outcomeTypes: [
    "The immediate situation is resolved; the data recovered will create a larger one",
    "Everyone makes it out; what they brought with them doesn't clear decon",
    "The corporation is satisfied; the actual problem is still out there",
    "First contact is made; the terms are not what either side anticipated",
    "The crew survives; the ship, the records, and the evidence do not",
  ],
  hooks: [
    "A distress beacon has been cycling for eleven days on a frequency reserved for vessels declared lost.",
    "The party's ship picks up a transponder signal from a registry number that belongs to their own vessel.",
    "A cargo manifest lists a container that is not physically present on the ship it was supposedly loaded onto.",
    "Someone filed an emergency salvage claim on a station that was occupied as recently as last week.",
  ],
};
