import type { AdventureGenreTables } from "../genre-types";

export const spaceOperaResistanceAdventureTables: AdventureGenreTables = {
  hint: "Focus on empire and resistance, moral compromises in pursuit of a just cause, supply scarcity, sympathisers behind enemy lines, and the people who get caught in the middle.",
  archetypes: [
    "Rescue & Recovery",
    "Escort & Delivery",
    "Heist & Theft",
    "Sabotage & Disruption",
    "Diplomatic Mission",
    "Survival & Escape",
    "Rebellion & Uprising",
  ],
  tones: [
    "Heroic & High-Stakes",
    "Desperate & Resource-Scarce",
    "Political & Morally Complex",
    "Fast & Action-Driven",
    "Character-Driven & Personal",
  ],
  sampleTitles: [
    "The Contact Who Didn't Arrive",
    "Supply Run to a Dead System",
    "What the Rebellion Knows",
    "Before the Fleet Moves",
    "A Name on the List",
  ],
  incitingActors: [
    "a resistance cell that has gone quiet in a sector where the Empire is consolidating",
    "a defector with critical intelligence and no safe way to deliver it",
    "an imperial officer whose conscience has just started causing operational problems",
    "a civilian population that made a choice about which side to shelter and is paying for it",
    "a resistance leadership that has made a decision the party was not consulted on",
    "a pirate warlord selling stolen imperial shield-generators to the highest bidder",
    "a planetary governor secretly funding underground anti-orbital batteries",
    "an ancient order of mystic guardians emerging from deep-space isolation",
  ],
  objectiveTypes: [
    "Extract the informant before the imperial sweep reaches their location",
    "Deliver the intelligence packet to the analyst before the operation window closes",
    "Disable the communication array without leaving evidence of how",
    "Get the refugees onto a vessel that is not officially there",
    "Verify whether the defector is genuine before the cell decides to trust them",
  ],
  locationTypes: [
    "an occupied system where the occupation is recent and the population is still deciding",
    "a neutral waystation that has been making accommodations for both sides",
    "an imperial facility whose civilian workforce is a problem for both parties",
    "a resistance safe world that is no longer safe",
    "a derelict vessel that is being used as a relay and is not where any chart says it is",
    "a hollowed-out asteroid base hiding a squadron of insurgent starfighters",
    "an imperial prison barge anchored inside a dense nebula cloud",
    "a planetary capital plaza under high-tech curfew martial law",
  ],
  npcRoles: [
    "the cell coordinator who knows exactly who is compromised and cannot share it without burning the network",
    "the sympathiser inside the imperial structure who has limited reach and a very limited window",
    "the civilian leader who has kept their community alive by not picking a side and is running out of time",
    "the imperial officer who is not a villain and whose decisions are making the situation worse",
    "the defector whose information is genuine, whose motives are not entirely clear, and whose former employers are looking for them",
  ],
  threatTypes: [
    "an imperial investigation team that has correctly identified the cell's operating area",
    "a collaborator inside the resistance whose information is out of date in a dangerous way",
    "imperial fleet assets that are not where the resistance's intelligence says they are",
    "the political friction inside the resistance that is affecting operational coordination",
    "time - the window is closing and the party is not yet in position",
    "an elite imperial inquisitor armed with psychological interrogation tech",
    "a blockade fleet deploying planetary interdictor gravity wells",
    "a bounty hunter guild hunting high-value resistance commanders for imperial gold",
  ],
  discoveryTypes: [
    "a communication intercept proving the meeting was observed before the cell knew it was compromised",
    "a name in the imperial records that belongs to someone currently trusted by the resistance",
    "an encrypted imperial holodisk recording target coordinates for an upcoming orbital strike",
    "a sealed comms cylinder containing high-tier imperial officer passcodes",
    "a document that proves the defector's stated reason for defecting is accurate - and that there is a second reason they haven't mentioned",
    "a stolen imperial clearance badge giving access to high-security star-docks",
    "a holocron containing ancient tactical maneuvers against dreadnought hulls",
    "a blueprint showing a critical structural flaw in the orbital garrison base",
  ],
  complicationTypes: [
    "the extraction vessel is delayed and the imperial sweep is not",
    "the intelligence packet contains something that contradicts a resistance operational assumption",
    "a party member is recognised by someone from their previous life",
    "the sympathiser's window closes early and the party must act with less support",
    "completing the mission saves the cell but exposes the network one level up",
  ],
  rewardTypes: [
    "intelligence access one tier above the party's current clearance",
    "a contact in the occupied sector that the party just spent three missions establishing",
    "a vessel the resistance is technically lending and will definitely need back",
    "the survival of people who would otherwise not have survived",
    "the cell's trust - which is operationally valuable and emotionally complicated",
  ],
  outcomeTypes: [
    "The mission succeeds; the intelligence changes the resistance's next move in ways the party will see later",
    "The informant is extracted; what they carry out is not what they were sent in to find",
    "The operation achieves its objective; one member of the cell does not make it to the debrief",
    "The defector is genuine; integrating their information into resistance planning will take time the party does not have",
    "The cell survives; the party is now in a position they will need to maintain",
  ],
  hooks: [
    "A resistance contact sends a two-word authentication and then goes silent: 'Come now.'",
    "The party receives mission parameters for an operation that was briefed to a different cell, whose current status is unknown.",
    "An imperial vessel the party is aware of has made a course correction that puts it on an intercept heading for a resistance asset they know the location of.",
    "A sympathiser inside an imperial facility makes contact with a time-sensitive piece of intelligence and a request the party was not expecting.",
  ],
};
