import type { AdventureGenreTables } from "../genre-types";

export const spaceWesternAdventureTables: AdventureGenreTables = {
  hint: "Focus on crew-scale frontier survival, smuggling runs, unpaid debts, rival salvage outfits, lawless asteroid ports, corrupt marshals, and the cost of keeping a battered ship flying.",
  archetypes: [
    "Smuggling & Contraband Run",
    "Salvage & Derelict Recovery",
    "Bounty Hunt & Extraction",
    "Heist & Station Break",
    "Escort & High-Risk Passage",
    "Sabotage & Claim Dispute",
    "Debt Collection & Shakedown",
  ],
  tones: [
    "Gritty & Pragmatic",
    "High-Stakes & Tense",
    "Rowdy & Desperate",
    "Lived-In & Lyrical",
    "Double-Crossing & Suspicious",
  ],
  sampleTitles: [
    "The Dead-Drop at Asteroid 77",
    "A Full Hold of Trouble",
    "The Marshal's Price",
    "Salvage Rights on the Rust-Barge",
    "Last Call at Dust-Well Station",
  ],
  incitingActors: [
    "a debt-ridden fixer offering a lucrative haul with undisclosed cargo restrictions",
    "a frontier marshal with a sealed warrant and a discreet budget for off-the-books extraction",
    "a rival captain who stole the coordinates to an abandoned ore-freighter and needs a second ship",
    "a runaway passenger willing to trade forged fuel chits for no-questions-asked passage",
    "a syndicate loan shark threatening to seize the crew's ship unless an overdue favour is settled",
    "a desperate mining colony facing an embargo from a corrupt shipping cartel",
    "a bounty hunter guild handler with a dead-or-alive contract on an elusive smuggler",
    "a salvager union rep warning that a corporate recovery crew is about to claim common drift-space",
  ],
  objectiveTypes: [
    "Deliver illicit cargo to a backwater outpost before the system customs patrol tightens the cordon",
    "Extract a wanted specialist from a corporate boomtown before rival hunters claim the bounty",
    "Secure high-value reactor cores from a drifting hulk before its orbit decays into the gas giant",
    "Steal the ledger of an extortionate fuel syndicate from their station vault",
    "Run a blockade of automated defense drones to resupply a besieged frontier settlement",
    "Mediate a violent claim-jumping dispute between wildcat miners and a corporate extraction firm",
  ],
  locationTypes: [
    "a dust-blown frontier colony built around a deep-crater moisture well",
    "a hollowed-out asteroid truck stop with flickering neon and unlicensed docking bays",
    "a lawless moon port where customs checks are decided by whoever holds the biggest cannon",
    "a radiation-scarred derelict freighter drifting in an unpoliced debris ring",
    "a corporate company town where oxygen and water are deducted directly from worker scrip",
    "a scrap-yard orbital station anchored in the upper atmosphere of a toxic gas giant",
    "a hidden smuggler haven carved into the ice fissures of a rogue comet",
    "a remote frontier saloon and refuelling depot at the edge of chartered space",
  ],
  npcRoles: [
    "the cynical captain trying to keep their engine from blowing while ducking creditors",
    "the back-alley fixer who sells immaculate forged transponders with a hidden tracking beacon",
    "the weary frontier marshal who knows the system is crooked but still enforces the peace",
    "the syndicate enforcer sent to remind the crew that interest rates compound daily",
    "the grease-monkey engineer who talks to the ship's reactor like an old friend",
    "the disgraced former pilot who knows every uncharted blind spot in the sector's sensor grid",
    "the ruthless bounty hunter who views collateral damage as an acceptable business expense",
  ],
  threatTypes: [
    "a heavily armed customs interceptor with long-range sensor locks and boarding grapples",
    "a ruthless rival crew that tracked the party from the last refuelling port",
    "a sudden breakdown of the sub-light drive coil midway through a high-gravity slingshot",
    "the cargo: unstable volatile fuel, experimental military fauna, or radioactive raw ore",
    "a syndicate death squad dispatched after a double-crossing broker leaked the flight plan",
    "an environmental failure: station depressurisation, solar flare, or catastrophic coolant leak",
    "a corporate private security firm enforcing an illegal martial curfew",
  ],
  discoveryTypes: [
    "a forged shipping manifest showing the client lied about what is sealed in container four",
    "a transponder log proving the derelict ship was intentionally sabotaged by its owners",
    "a dead man's encrypted datapad containing the access codes to a cartel slush-fund account",
    "a tracker beacon hidden inside the crew's fuel intake valves",
    "evidence that the frontier marshal is on the payroll of the very syndicate hunting the party",
    "a cache of unrefined rare isotope fuel rods tucked beneath the false deck plating",
    "a recorded distress beacon revealing that previous salvage teams were trapped deliberately",
  ],
  complicationTypes: [
    "the landing dock fee has tripled and the harbormaster demands collateral",
    "the ship's engine coughs black smoke and drops to thirty percent thrust at the worst moment",
    "a passenger on board turns out to be carrying a bounty that every scoundrel in the sector wants",
    "the buyer refuses the agreed price and attempts to seize the cargo by force",
    "a local bar brawl draws the attention of station security right before a discreet handoff",
    "the fuel quality at this port is contaminated, risking engine stall during departure",
  ],
  rewardTypes: [
    "enough cold hard bullion or bearer chits to pay off three months of the ship's mortgage",
    "a crate of military-spec replacement drive thrusters that won't show up on any inspection",
    "a permanent berth discount and safe harbour at an independent frontier station",
    "a clean slate and expunged sector warrants courtesy of a grateful magistrate",
    "an untraceable long-range sub-space communication array",
    "the loyalty of a skilled grease-monkey mechanic or sharp-shooting pilot",
  ],
  outcomeTypes: [
    "The crew delivers the haul and collects their pay, but burns their bridge with the local syndicate",
    "The salvage is secured, but the ship took severe hull stress and will need extensive drydock work",
    "The target is extracted cleanly; however, they know an uncomfortable secret about the crew's past",
    "The job goes sideways into a blazing shootout; the crew escapes with the goods and a brand-new bounty on their heads",
    "The crew pays off their debt to the loan shark, only to be offered an even more dangerous contract",
  ],
  hooks: [
    "The crew's ship is impounded for unpaid berthing fees until they agree to do a 'favour' for the station boss.",
    "A drifting distress beacon ping matches the callsign of a freighter that vanished five years ago with a fortune in ore.",
    "A frantic contact bursts into the cantina, throws a locked containment case at the crew, and takes a bolt to the chest.",
    "A frontier colony issues an open salvage bounty on a rogue automated mining rig tearing up their claims.",
    "The crew's favorite fence sends an encrypted distress ping: someone has kicked in the front door of their pawnshop.",
  ],
};
