import type { AdventureGenreTables } from "../genre-types";

export const steampunkAdventureTables: AdventureGenreTables = {
  hint: "Focus on guild monopolies, automaton rights, sabotaged innovations, airship crashes with suspicious passenger lists, and the collision between old money and new invention.",
  archetypes: [
    "Investigation & Mystery",
    "Heist & Theft",
    "Escort & Delivery",
    "Rescue & Recovery",
    "Sabotage & Disruption",
    "Diplomatic Mission",
    "Hunt & Pursuit",
  ],
  tones: [
    "Political & Guild-Intrigue",
    "Pulp & Action-Adventure",
    "Dark & Industrially Gothic",
    "Whimsical & Inventive",
    "Tense & High-Pressure",
  ],
  sampleTitles: [
    "The Patent That Disappeared",
    "Airship Down",
    "What the Guild Refused to Licence",
    "A Demonstration Gone Wrong",
    "The Engine at the Centre of Everything",
  ],
  incitingActors: [
    "a guild that has decided a new invention must not reach the market",
    "an inventor who has made a breakthrough and immediately disappeared",
    "an automaton that has developed opinions about its labour agreement",
    "a dirigible company whose flagship has gone off course in suspicious circumstances",
    "an imperial ministry that needs something recovered before the press finds it",
    "a clockwork syndicate hoarding stolen pressure-valve patents",
    "a secret society of smog-weavers sabotaging municipal ventilation towers",
    "an eccentric coal-baron funding illegal aetheric weapons research",
  ],
  objectiveTypes: [
    "Recover the patent before the guild buries it",
    "Find the inventor before whoever took them finishes what they started",
    "Get the prototype to its demonstration without the saboteurs getting there first",
    "Investigate the crash before the official inquiry closes the case",
    "Expose the labour arrangement that every institution has decided not to notice",
  ],
  locationTypes: [
    "a factory district where the air is a colour that doesn't occur naturally",
    "a guild hall whose library is locked to non-members and occasionally to members",
    "an airship terminus where three competing lines run out of the same hangar",
    "a back-street workshop producing things that require two different licences to sell",
    "a ministry building where the filing system is the actual security measure",
  ],
  npcRoles: [
    "the guild inspector whose jurisdiction is wide and whose patience is narrow",
    "the inventor's assistant who knows where everything is and cannot say so directly",
    "the automaton with a contract dispute and a very specific grievance",
    "the press correspondent who is two steps ahead and needs two steps kept quiet",
    "the ministry clerk who filed something in the wrong drawer intentionally",
  ],
  threatTypes: [
    "a guild enforcer operating under a letter of authority that predates current law",
    "a rival inventor whose methods of suppressing competition have escalated",
    "an automaton workforce that has organised and has specific demands",
    "a press syndicate whose coverage is a financial weapon",
    "a government ministry that has decided the matter should remain classified",
    "a rogue steam-dreadnought crew holding the Grand Aqueduct hostage",
    "an unscrupulous patent attorney backed by private security automatons",
    "a cabal of radical Luddite saboteurs targeting boiler networks",
  ],
  discoveryTypes: [
    "a schematic for something that should not be possible under current physics",
    "a signed transaction record proving the guild purchased the competing patent before publicly discrediting it",
    "a witness statement signed and notarised by someone since reported dead",
    "a contract between the ministry and the guild predating the accident by three months",
    "a piece of evidence that makes sense of three previous incidents nobody connected",
    "a brass-encased cipher cylinder containing illegal aether-refining formulas",
    "a broken pressure gauge showing the boiler explosion was manually triggered from the inside",
    "a pocket-sized analytical engine memory card containing unedited board meeting transcripts",
  ],
  complicationTypes: [
    "the demonstration is moved up; the party has half the time they planned for",
    "the guild applies for an injunction that legally prevents the party's client from operating",
    "a piece of evidence is genuine but its chain of custody is not",
    "an automaton involved in the situation has made its own decision about the outcome",
    "the press publishes something true at the worst possible moment",
  ],
  rewardTypes: [
    "a licence that is technically invalid but will hold up long enough to matter",
    "a stake in the invention - which is worth nothing until it isn't",
    "political favour from a ministry that owes the party a quiet one",
    "access to a guild facility that is usually closed to non-members",
    "the gratitude of a workforce that has long memories and broad reach",
  ],
  outcomeTypes: [
    "The invention reaches its demonstration; the guild files for an injunction",
    "The crash investigation concludes; the official report omits the third party",
    "The saboteur is exposed; the ministry distances itself from the relationship",
    "The automaton dispute is resolved; the terms set a precedent nobody planned for",
    "The patent is recovered; whether it can legally be used is a question for another day",
  ],
  hooks: [
    "A package addressed to the party arrives containing a technical schematic and a note in three words: 'They found me.'",
    "An airship the party travelled on six months ago has just crashed under circumstances the company is calling mechanical failure.",
    "A guild representative approaches with a licensing offer for something the party has never invented.",
    "A known inventor has been publicly discredited on evidence that one party member recognises as fabricated.",
  ],
};
