import type { AdventureGenreTables } from "../genre-types";

export const superheroAdventureTables: AdventureGenreTables = {
  hint: "Focus on secret identities under pressure, public reputation as a resource that can be spent or lost, escalating villain schemes, and the gap between heroic ideals and the messy consequences of using them.",
  archetypes: [
    "Villain Scheme & Interception",
    "Rescue & Disaster Response",
    "Investigation & Cover-Up",
    "Secret Identity Crisis",
    "Team Conflict & Fracture",
    "Public Trial & Reputation",
    "Escort & Protection",
  ],
  tones: [
    "Four-Color Heroic",
    "Street-Level Gritty",
    "Cynical & Cutting",
    "Cosmic & Epic",
    "Pulp Adventure",
  ],
  sampleTitles: [
    "The Villain Had a Point",
    "Nobody Called for Backup",
    "Collateral, Redacted",
    "The Mask Slips at Midnight",
    "Everyone Blames the Hero Who Showed Up",
  ],
  incitingActors: [
    "a rookie hero whose first public save went catastrophically wrong on camera",
    "a retired villain trying to go straight while old enemies won't let them",
    "a black-ops program testing an unregistered power-suppression weapon on civilians",
    "a legacy hero's estranged protege claiming the old identity for their own ends",
    "a city council vote to deputize or ban vigilantes within 48 hours",
    "a rogue predictive AI built to profile villain schemes now generating its own",
    "a corporate sponsor threatening to pull a team's funding unless they take a PR-friendly job",
    "a supervillain who surrendered and now wants the heroes to prove they're better",
  ],
  objectiveTypes: [
    "Stop a scheme before its public reveal moment",
    "Contain a disaster without exposing a secret identity",
    "Extract a target before a rival team or the press gets there",
    "Clear a hero's name after a staged incident",
    "Keep a fragile ceasefire between rival factions from collapsing",
  ],
  locationTypes: [
    "a skyscraper headquarters mid-evacuation during a hostage situation",
    "an abandoned subway line repurposed as a villain's staging ground",
    "a press conference stage rigged with something the reporters don't know about",
    "a research campus where an experiment breached containment",
    "a rooftop network known only to the city's costumed community",
    "a courtroom hearing a case that could unmask a hero on the record",
    "a disaster zone still smoldering from the last team's failed intervention",
    "an orbital platform repurposed as a supervillain's lair",
  ],
  npcRoles: [
    "the veteran hero mentoring someone they're not sure deserves it",
    "the journalist who's close to publishing a secret identity by accident",
    "the police liaison caught between department policy and personal gratitude",
    "the civilian who saw too much and now needs protecting",
    "the rival hero whose methods the party doesn't endorse but can't ignore",
  ],
  threatTypes: [
    "a supervillain executing a scheme with genuine public sympathy behind it",
    "a black-ops strike team authorized to treat heroes as the threat",
    "a rogue former ally who knows every weakness firsthand",
    "a media outlet weaponizing footage to turn public opinion",
    "a cosmic-scale anomaly indifferent to the city beneath it",
    "a corporate security force enforcing a patent on a hero's own powers",
    "an occult cabal harvesting collateral damage for a ritual purpose",
  ],
  discoveryTypes: [
    "security footage proving the 'accident' was staged",
    "a partially-decrypted origin file naming who funded the experiment",
    "a hidden ledger connecting a respected philanthropist to a villain's operation",
    "a warning message recorded by a hero who didn't survive to deliver it",
    "a prototype device that could neutralize a hero's own powers",
    "a witness statement that contradicts the official incident report",
    "an old photograph placing a 'new' villain at a decades-old disaster",
  ],
  complicationTypes: [
    "the villain's demands turn out to have a legitimate grievance underneath",
    "a secret identity nearly slips in front of the wrong witness",
    "the team disagrees publicly about the right call, live on camera",
    "rescuing everyone means letting the actual target escape",
    "a former ally shows up on the opposing side, and won't explain why",
  ],
  rewardTypes: [
    "public trust rebuilt, at least until the next headline",
    "a favor owed by someone with real institutional power",
    "a piece of villain tech too dangerous to sell but too useful to destroy",
    "an ally's loyalty, earned rather than assumed",
    "access to a resource that raises the stakes for the next scheme",
  ],
  outcomeTypes: [
    "The city is safe tonight; the underlying cause is still out there",
    "The villain is stopped, but sympathetic enough that public opinion splits",
    "The team wins, but the cost is a secret identity or a relationship",
    "Nobody died, which the party has learned not to take for granted",
    "The scheme's real mastermind was never in the room",
  ],
  hooks: [
    "A live broadcast cuts to a villain address that names the party by their civilian identities.",
    "An anonymous tip arrives with photographic proof of the last scheme's true architect.",
    "A former mentor's costume is found abandoned at the scene of a disaster no one has claimed.",
    "The city council schedules an emergency vote on hero oversight for tomorrow morning, and someone wants the party's testimony tonight.",
  ],
};
