import type { AdventureGenreTables } from "../genre-types";

export const vampireAdventureTables: AdventureGenreTables = {
  hint: "Focus on hidden courts, political debts called in at the worst moment, mortal pawns who learn too much, and the slow erosion of everything that made someone human.",
  archetypes: [
    "Investigation & Mystery",
    "Diplomatic Mission",
    "Heist & Theft",
    "Survival & Escape",
    "Rescue & Recovery",
    "Blackmail & Leverage",
  ],
  tones: [
    "Political & Intrigue-Heavy",
    "Noir & Morally Compromised",
    "Romantic & Dangerous",
    "Paranoid & Surveilled",
    "Gothic & Atmospheric",
  ],
  sampleTitles: [
    "The Debt the City Owes",
    "An Invitation You Don't Decline",
    "Blood Compact",
    "What the Court Forgot to Erase",
    "A Favour from the Wrong Benefactor",
  ],
  incitingActors: [
    "an ancient noble who has grown bored with subtlety",
    "a newly made vampire who does not understand what they have become",
    "a mortal family that has been serving the court for four generations and wants out",
    "a pretender to a court seat who needs human agents to act where they cannot",
    "a hunter who is hunting the wrong thing for the right reasons",
    "a blood-bank administrator smuggling plasma to an unsanctioned court fledglings' refuge",
    "a vampire elder's ghoul who stole their master's coffin key",
    "a rival city's emissary offering forbidden blood-alchemy secrets",
  ],
  objectiveTypes: [
    "Navigate a court obligation without becoming a permanent asset",
    "Find a missing mortal before the court decides they were the problem",
    "Recover a document that proves a covenant was broken",
    "Survive a gathering where every guest has their own agenda",
    "Expose a rogue actor without implicating the court that made them",
  ],
  locationTypes: [
    "a city that runs on blood money - metaphorically and literally",
    "an estate that belongs to no name on any current registry",
    "a private members' club whose membership list is a state secret",
    "a masquerade event where the masks are the only thing keeping everyone safe",
    "a neighbourhood the court considers its exclusive feeding ground",
    "a subterranean blood vault hidden beneath an operating hospital mortuary",
    "a sun-less penthouse suite equipped with blast-shielded velvet drapes",
    "an abandoned gothic cathedral converted into a night-court tribunal",
  ],
  npcRoles: [
    "the court herald who speaks for a principal they have never seen awake",
    "the mortal liaison who has forgotten what they negotiated in exchange",
    "the survivor of a previous compact who was supposed to be too frightened to talk",
    "the pretender whose evidence is legitimate but whose methods are not",
    "the ancient who remembers the original agreement and both parties who signed it",
  ],
  threatTypes: [
    "a court faction that has decided the players are more useful as leverage than agents",
    "a hunter organisation with accurate intelligence and poor judgment",
    "a rogue element who has been operating outside court sanction for decades",
    "the compact itself - an old agreement whose terms are worse on re-reading",
    "a mortal institution that has started to suspect what it is actually dealing with",
    "an ancient blood-curse manifesting as uncontrollable thirst among city ghouls",
    "a fanatical inquisitor armed with UV-searchlights and holy water grenades",
    "a rival prince's archons executing unannounced domain purges",
  ],
  discoveryTypes: [
    "a name in the court register that belongs to someone the party knows as mortal",
    "a sealed vellum lineage scroll bound in crimson silk",
    "a silver phial containing preserved blood from a sire long thought dead",
    "a contract clause that transfers the obligation to whoever receives the debt",
    "a witness account from 1887 that describes the same individual the party met this morning",
    "a heavy iron key forged with sun-motifs that opens the elder's daylight vault",
    "a mortal coroner's report detailing bodies drained completely of blood with no puncture marks",
    "a hidden portrait showing the city mayor standing beside the vampire prince in 1912",
  ],
  complicationTypes: [
    "the party's handler is recalled mid-mission for reasons the court declines to share",
    "the document they came for has already been read by someone it wasn't meant for",
    "one of the party has been offered a separate deal by the other side",
    "the extraction plan depends on a safe house that is no longer safe",
    "the sun is coming up and one party member has just learned they have an appointment at dawn",
  ],
  rewardTypes: [
    "a letter of patronage worth exactly one future favour from exactly one court",
    "territorial access that will make the next job easier and create a problem three jobs from now",
    "proof of something that cannot be acted upon without revealing how it was obtained",
    "a blood debt called clear - for now, and with conditions",
    "the court's official ignorance of what the party did tonight",
  ],
  outcomeTypes: [
    "The rogue element is removed; the court maintains plausible distance",
    "The compact holds; the terms that made it uncomfortable remain in force",
    "The mortal is safe; the court files this as a debt rather than a rescue",
    "The document is destroyed; the memory of its contents is not",
    "The court is satisfied; the party now owes the court something they haven't agreed to yet",
  ],
  hooks: [
    "An envelope arrives at the party's lodging containing a card with an address, a time, and a single word: 'Come.'",
    "A mortal who works for a court contact is found dead in circumstances that would embarrass the court considerably.",
    "The party is offered work - the brief is to recover a person, but the name on the file belongs to someone who died fourteen years ago.",
    "A note delivered with the party's meal reads: 'The court knows you are here. The court would like to discuss terms.'",
  ],
};
