import type { AdventureGenreTables } from "../genre-types";

export const westernAdventureTables: AdventureGenreTables = {
  hint: "Focus on contested frontier land, boundary disputes, corrupt lawmen, desperate outlaws, silver boomtowns, cattle barons, smuggling rings, and old grudges coming due.",
  archetypes: [
    "Escort & Delivery",
    "Hunt & Pursuit",
    "Rescue & Recovery",
    "Heist & Theft",
    "Rebellion & Uprising",
    "Survival & Escape",
    "Diplomatic Mission",
  ],
  tones: [
    "Gritty & Frontier-Tense",
    "Morally Grey",
    "Action-Heavy & Fast",
    "Political & Land-Rights",
    "Elegiac & Ending-of-an-Era",
  ],
  sampleTitles: [
    "The Last Stage Running",
    "Land That Nobody Owns Twice",
    "What the Sheriff Couldn't Say",
    "The Silver Assay Fraud",
    "One More Town Before the Territory Closes",
  ],
  incitingActors: [
    "a ruthlessly ambitious cattle baron seizing water rights along the ridge",
    "a landowner who has run this county so long they have forgotten what law looks like without them",
    "a marshal whose jurisdiction ends three miles before the problem does",
    "a band of outlaws that has been operating for so long the local economy depends on them",
    "a silver mining concern covering up a deadly vein collapse",
    "a rogue telegraph operator intercepting land deed transfers",
    "a frontier doctor who discovered an illegal poison in the town's water well",
    "a displaced homesteader militia arming themselves for a land war",
  ],
  objectiveTypes: [
    "Get the payroll through without losing it or the people carrying it",
    "Find the missing survey team before whoever took them finishes the job",
    "Stop the land seizure long enough for the legitimate claim to be filed",
    "Bring someone in - or bring them back, alive enough to testify",
    "Keep the peace for forty-eight hours while two sides negotiate something that might hold",
  ],
  locationTypes: [
    "a boom town that has not decided whether it is a town or a camp",
    "a ranch that controls the water rights for everything within fifty miles",
    "a border crossing where three jurisdictions overlap and none of them agree",
    "a mining claim whose deed was rewritten by someone with a better lawyer",
    "a railhead terminus where every faction has a different idea of what comes next",
    "a ghost town saloon where outlaws and lawmen hold unwritten truces",
    "a treacherous canyon pass where ambushes happen twice a week",
    "an isolated assay office sitting atop an un-mapped silver vein",
  ],
  npcRoles: [
    "the local lawman who knows what is right and what he can actually do about it",
    "the homesteader whose claim is legitimate and who has run out of legal options",
    "the hired gun who is good at the work and not particular about the client",
    "the company agent whose authority on paper is considerably larger than his authority in fact",
    "the person with the deed, the information, or the evidence that every faction wants",
  ],
  threatTypes: [
    "a land baron who has been buying judges as long as he has been buying land",
    "a gang operating under the protection of someone with legitimate authority",
    "a company enforcer whose instructions are to resolve the situation before the board meeting",
    "a mob that has decided law is not coming and they are tired of waiting",
    "terrain, weather, and distance - the frontier kills more people than bullets",
    "a corrupt assay clerk who declares rich veins worthless to buy them out",
    "a mercenary posse holding a bridge toll by force of rifle",
    "a bounty hunter collecting fees for dead bounties regardless of innocence",
  ],
  discoveryTypes: [
    "a deed whose chain of title passes through a transaction that was not voluntary",
    "a telegraph message that was sent but not delivered - and its contents explain why",
    "a witness to an event that the official account says no one survived",
    "a map of water sources that makes the disputed land three times as valuable as advertised",
    "a prior claim filed under a different name in a different county, still technically valid",
    "a surveyor's notebook showing official county borders were deliberately falsified",
    "a blood-stained saddlebag containing forged foreclosure notices",
    "a locked iron cashbox key hidden inside a hollowed-out bible",
  ],
  complicationTypes: [
    "the law arrives - on the wrong side",
    "the route is blocked and the only alternative adds two days the party doesn't have",
    "someone who was supposed to be neutral makes a decision",
    "the evidence they came to protect is already in transit to somewhere it cannot be followed",
    "a third party with their own agenda steps into the standoff",
  ],
  rewardTypes: [
    "land - which is valuable and creates obligations",
    "a favour from someone with authority in the next county",
    "a reputation that opens some doors and marks others permanently closed",
    "cash, payable immediately, with no questions about what the party did to earn it",
    "the gratitude of a community that will remember it - and call on it",
  ],
  outcomeTypes: [
    "The immediate threat is removed; the underlying claim is still contested",
    "The delivery is made; what was delivered changes the situation in ways the brief didn't cover",
    "The community holds its ground; the company adjusts its approach",
    "The target is brought in; the testimony creates as many problems as it solves",
    "Everyone makes it out; the territory will not look the same by next year",
  ],
  hooks: [
    "The stagecoach arrived on time. The driver and the guard did not arrive with it.",
    "A reward notice for a specific individual has been posted in every town within a hundred miles - all on the same day.",
    "The party is offered a marshal's commission that covers a jurisdiction nobody else will take.",
    "A land agent appears at the party's camp with paperwork suggesting they own something they have never purchased.",
  ],
};
