// @vitest-environment jsdom
import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { SessionHubStore, SESSION_DRAFTS_KEY } from "./session-hub.svelte.js";

// Mock dependencies
const mockIdGenerator = {
  uuid: vi.fn(),
};

const mockStorage = {
  getItem: vi.fn(),
  setItem: vi.fn(),
  removeItem: vi.fn(),
};

describe("SessionHubStore", () => {
  let store: SessionHubStore;

  beforeEach(() => {
    vi.resetAllMocks();

    // Provide a sequence of unique IDs for tests that create multiple entities
    let idCounter = 1;
    mockIdGenerator.uuid.mockImplementation(() => `mock-id-${idCounter++}`);

    mockStorage.getItem.mockReturnValue(null);

    store = new SessionHubStore(mockIdGenerator, mockStorage);
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("initializes with empty state", () => {
    expect(store.entities).toEqual([]);
    expect(store.provenance).toEqual({});
    expect(store.nextOrder).toBe(1);
  });

  it("adds an entity and updates order", () => {
    const id = store.addEntity({
      type: "character",
      title: "Elara",
      content: "Brave hero",
      labels: [],
      status: "active",
      reuseEnabled: true,
      pinned: false,
    });

    expect(id).toBe("mock-id-1");
    expect(store.entities).toHaveLength(1);
    expect(store.entities[0].id).toBe(id);
    expect(store.entities[0].title).toBe("Elara");
    expect(store.entities[0].createdOrder).toBe(1);
    expect(store.entities[0].selectedForSave).toBe(true);
    expect(store.nextOrder).toBe(2);

    expect(mockStorage.setItem).toHaveBeenCalledWith(SESSION_DRAFTS_KEY, expect.any(String));
  });

  it("updates an entity", () => {
    const id = store.addEntity({
      type: "character",
      title: "Elara",
      content: "Brave hero",
      labels: [],
      status: "active",
      reuseEnabled: true,
      pinned: false,
    });

    store.updateEntity(id, { title: "Elara the Brave", pinned: true });
    expect(store.entities[0].title).toBe("Elara the Brave");
    expect(store.entities[0].pinned).toBe(true);

    expect(mockStorage.setItem).toHaveBeenCalledTimes(2); // Once on add, once on update
  });

  it("removes an entity and its provenance", () => {
    const id = store.addEntity({
      type: "character",
      title: "Elara",
      content: "Brave hero",
      labels: [],
      status: "active",
      reuseEnabled: true,
      pinned: false,
    });

    store.addProvenance({
      resultEntityId: id,
      usedEntityIds: [],
      offeredEntityIds: [],
      trimmed: false,
    });

    store.removeEntity(id);
    expect(store.entities).toHaveLength(0);
    expect(store.provenance[id]).toBeUndefined();

    expect(mockStorage.setItem).toHaveBeenCalledTimes(3); // Add entity, add provenance, remove entity
  });

  it("loads from storage", () => {
    const mockState = {
      version: 2,
      entities: [
        { id: "1", title: "Test", createdOrder: 1, reuseEnabled: true },
      ],
      provenance: {
        "1": {
          resultEntityId: "1",
          usedEntityIds: [],
          offeredEntityIds: [],
          trimmed: false,
        },
      },
      nextOrder: 2,
    };

    mockStorage.getItem.mockReturnValueOnce(JSON.stringify(mockState));

    const newStore = new SessionHubStore(mockIdGenerator, mockStorage);

    expect(newStore.entities).toHaveLength(1);
    expect(newStore.entities[0].title).toBe("Test");
    expect(newStore.entities[0].selectedForSave).toBe(true);
    expect(newStore.provenance["1"]).toBeDefined();
    expect(newStore.nextOrder).toBe(2);
  });

  it("migrates from v1 SessionDraft format", () => {
    const oldFormat = [
      {
        type: "character",
        title: "Old Draft",
        content: "content",
        status: "draft",
      },
    ];

    mockStorage.getItem.mockReturnValueOnce(JSON.stringify(oldFormat));

    const newStore = new SessionHubStore(mockIdGenerator, mockStorage);

    expect(newStore.entities).toHaveLength(1);
    expect(newStore.entities[0].title).toBe("Old Draft");
    expect(newStore.entities[0].id).toBe("mock-id-1"); // Generated by idGenerator
    expect(newStore.entities[0].reuseEnabled).toBe(true);
    expect(newStore.entities[0].selectedForSave).toBe(true);
    expect(newStore.nextOrder).toBe(2);

    // Should have saved the migrated state
    expect(mockStorage.setItem).toHaveBeenCalledWith(SESSION_DRAFTS_KEY, expect.any(String));
  });

  it("clears all state", () => {
    store.addEntity({
      type: "character",
      title: "Elara",
      content: "Brave hero",
      labels: [],
      status: "active",
      reuseEnabled: true,
      pinned: false,
    });

    store.clear();

    expect(store.entities).toHaveLength(0);
    expect(store.nextOrder).toBe(1);

    expect(mockStorage.setItem).toHaveBeenCalledTimes(2); // Add, clear
  });
});
