import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const DEFAULT_PAGES_DIR = path.resolve(
  __dirname,
  "../apps/web/src/lib/content/answers/pages",
);
export const DEFAULT_INDEX_PATH = path.join(DEFAULT_PAGES_DIR, "index.ts");

export interface AnswerExportInfo {
  fileName: string;
  exportName: string;
  slug: string;
}

/**
 * Parses an answer file to extract its export name and slug.
 */
export function parseAnswerExport(
  fileName: string,
  content: string,
): AnswerExportInfo | null {
  const exportMatch = content.match(
    /export\s+const\s+(\w+)\s*(?::\s*AnswerConfigInput)?\s*=/,
  );
  if (!exportMatch) return null;
  const exportName = exportMatch[1];

  const slugMatch = content.match(/slug:\s*["']([^"']+)["']/);
  if (!slugMatch) return null;
  const slug = slugMatch[1];

  return {
    fileName,
    exportName,
    slug,
  };
}

/**
 * Scans the answer pages directory for all answer files.
 */
export function findAnswerFiles(pagesDir: string): string[] {
  if (!fs.existsSync(pagesDir)) return [];
  return fs
    .readdirSync(pagesDir)
    .filter(
      (f) => f.endsWith(".ts") && f !== "index.ts" && !f.endsWith(".test.ts"),
    )
    .sort();
}

/**
 * Generates the TypeScript source for pages/index.ts.
 */
export function generateIndexSource(entries: AnswerExportInfo[]): string {
  // Sort deterministically by slug
  const sorted = [...entries].sort((a, b) => a.slug.localeCompare(b.slug));

  const imports = sorted
    .map((e) => {
      const baseName = e.fileName.replace(/\.ts$/, "");
      return `import { ${e.exportName} } from "./${baseName}";`;
    })
    .join("\n");

  const exportedAnswers = sorted.map((e) => `    ${e.exportName},`).join("\n");

  return `import { AnswerConfigSchema, type AnswerConfig } from "../schema";
${imports}

/**
 * The published answer library.
 *
 * Auto-generated by scripts/sync-answers.ts. Do not edit directly.
 * To add a new answer, create a file in \`pages/<slug>.ts\` and run \`bun sync:answers\`.
 */
export const answers: Record<string, AnswerConfig> = Object.fromEntries(
  [
${exportedAnswers}
  ]
    .map((answer) => AnswerConfigSchema.parse(answer))
    .map((answer) => [answer.slug, answer]),
);
`;
}

/**
 * Validates the documented invariants across all parsed answer entries:
 * the file name must match `<slug>.ts`, and slugs/export names must be
 * unique. Throws with a descriptive message on the first violation found.
 */
export function validateAnswerEntries(entries: AnswerExportInfo[]): void {
  const seenSlugs = new Map<string, string>();
  const seenExportNames = new Map<string, string>();

  for (const entry of entries) {
    const slugOwner = seenSlugs.get(entry.slug);
    if (slugOwner) {
      throw new Error(
        `[sync-answers] Duplicate slug "${entry.slug}" found in ${slugOwner} and ${entry.fileName}.`,
      );
    }
    seenSlugs.set(entry.slug, entry.fileName);

    const exportOwner = seenExportNames.get(entry.exportName);
    if (exportOwner) {
      throw new Error(
        `[sync-answers] Duplicate export name "${entry.exportName}" found in ${exportOwner} and ${entry.fileName}.`,
      );
    }
    seenExportNames.set(entry.exportName, entry.fileName);

    const expectedFileName = `${entry.slug}.ts`;
    if (entry.fileName !== expectedFileName) {
      throw new Error(
        `[sync-answers] ${entry.fileName} declares slug "${entry.slug}" but the file name must be "${expectedFileName}".`,
      );
    }
  }
}

/**
 * Syncs the answer pages index file.
 */
export function syncAnswers(
  pagesDir = DEFAULT_PAGES_DIR,
  indexPath = DEFAULT_INDEX_PATH,
): { changed: boolean; count: number } {
  const files = findAnswerFiles(pagesDir);
  const entries: AnswerExportInfo[] = [];

  for (const file of files) {
    const fullPath = path.join(pagesDir, file);
    const content = fs.readFileSync(fullPath, "utf-8");
    const parsed = parseAnswerExport(file, content);
    if (parsed) {
      entries.push(parsed);
    } else {
      throw new Error(
        `[sync-answers] Could not parse answer export from ${file}.`,
      );
    }
  }

  validateAnswerEntries(entries);

  const generatedSource = generateIndexSource(entries);
  const existingSource = fs.existsSync(indexPath)
    ? fs.readFileSync(indexPath, "utf-8")
    : "";

  if (existingSource === generatedSource) {
    return { changed: false, count: entries.length };
  }

  fs.writeFileSync(indexPath, generatedSource, "utf-8");
  return { changed: true, count: entries.length };
}

// CLI entry point
if (
  process.argv[1] &&
  (process.argv[1] === fileURLToPath(import.meta.url) ||
    process.argv[1].endsWith("sync-answers.ts"))
) {
  const result = syncAnswers();
  if (result.changed) {
    console.log(
      `✓ Synced ${result.count} answer pages to ${path.relative(process.cwd(), DEFAULT_INDEX_PATH)}`,
    );
  } else {
    console.log(`✓ Answer pages index up to date (${result.count} answers)`);
  }
}
