/**
 * Writes the list of generators the help assistant knows about.
 *
 *   bun scripts/sync-help-generators.ts
 *
 * The help package may import only the schema package (an architecture rule),
 * so it cannot read the generator registry itself. This script, which lives
 * with the other repo scripts, copies each generator's id, label and
 * description into a committed module. A web test fails if the module and the
 * registry ever disagree, so the list cannot go stale unnoticed: add, remove
 * or rename a generator, then run this script.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { listGenerators } from "generator-engine";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const output = path.join(
  root,
  "packages/help-engine/src/registry/generators.generated.ts",
);

const generators = listGenerators().map((g) => ({
  id: g.id,
  label: g.label,
  description: g.description,
}));

const body = `/**
 * GENERATED by scripts/sync-help-generators.ts from the generator registry.
 * Do not edit by hand: change a generator, then run the script.
 */
export const GENERATORS = ${JSON.stringify(generators, null, 2)} as const;

export type GeneratorId = (typeof GENERATORS)[number]["id"];

export const GENERATOR_IDS = GENERATORS.map((g) => g.id) as unknown as readonly [
  GeneratorId,
  ...GeneratorId[],
];
`;

fs.writeFileSync(output, body);
execFileSync("bunx", ["prettier", "--write", output], {
  cwd: root,
  stdio: "ignore",
});
console.log(
  `help generators: ${generators.length} written to ${path.relative(root, output)}`,
);
