#!/usr/bin/env bun
/**
 * Update published IP ranges for AI crawlers and fetchers (#2864).
 *
 * Fetches official CIDR lists from:
 * - OpenAI (SearchBot, ChatGPT-User, GPTBot)
 * - Perplexity (PerplexityBot, Perplexity-User)
 * - Google (Common Crawlers)
 * - Microsoft Bing (Bingbot)
 *
 * Validates prefixes and updates apps/web/src/lib/seo/crawler-observability/published-ranges.ts
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface ProviderEndpoint {
  id: string;
  url: string;
  provider: string;
  agentName: string;
}

const ENDPOINTS: ProviderEndpoint[] = [
  {
    id: "openaiSearchbot",
    url: "https://openai.com/searchbot.json",
    provider: "openai",
    agentName: "OAI-SearchBot",
  },
  {
    id: "openaiChatgptUser",
    url: "https://openai.com/chatgpt-user.json",
    provider: "openai",
    agentName: "ChatGPT-User",
  },
  {
    id: "openaiGptbot",
    url: "https://openai.com/gptbot.json",
    provider: "openai",
    agentName: "GPTBot",
  },
  {
    id: "perplexityBot",
    url: "https://www.perplexity.ai/perplexitybot.json",
    provider: "perplexity",
    agentName: "PerplexityBot",
  },
  {
    id: "perplexityUser",
    url: "https://www.perplexity.ai/perplexity-user.json",
    provider: "perplexity",
    agentName: "Perplexity-User",
  },
  {
    id: "googleCrawlers",
    url: "https://developers.google.com/static/crawling/ipranges/common-crawlers.json",
    provider: "google",
    agentName: "Googlebot",
  },
  {
    id: "bingbot",
    url: "https://www.bing.com/toolbox/bingbot.json",
    provider: "microsoft",
    agentName: "bingbot",
  },
];

async function fetchCidrs(url: string): Promise<string[]> {
  const res = await fetch(url, {
    headers: { "User-Agent": "Codex-Cryptica-Observability-Sync/1.0" },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} from ${url}`);
  const data = (await res.json()) as {
    prefixes?: Array<{ ipv4Prefix?: string; ipv6Prefix?: string }>;
  };

  const cidrs: string[] = [];
  for (const item of data.prefixes ?? []) {
    if (item.ipv4Prefix && typeof item.ipv4Prefix === "string") {
      cidrs.push(item.ipv4Prefix.trim());
    }
    if (item.ipv6Prefix && typeof item.ipv6Prefix === "string") {
      cidrs.push(item.ipv6Prefix.trim());
    }
  }

  // Deduplicate and sort
  return [...new Set(cidrs)].sort();
}

export async function generatePublishedRangesFile(): Promise<void> {
  console.log("Fetching official AI crawler IP ranges...");
  const registry: Record<string, string[]> = {};

  for (const ep of ENDPOINTS) {
    try {
      const cidrs = await fetchCidrs(ep.url);
      registry[ep.id] = cidrs;
      console.log(
        `  ✓ ${ep.agentName} (${ep.provider}): ${cidrs.length} CIDRs`,
      );
    } catch (err) {
      console.error(`  ✗ ${ep.agentName} (${ep.url}):`, err);
      throw err;
    }
  }

  const generatedAt = new Date().toISOString();
  const fileContent = `/**
 * Official Published IP Ranges for AI Crawlers & Fetchers (#2864).
 * Auto-generated by scripts/update-crawler-ip-ranges.ts
 * Last synced: ${generatedAt}
 *
 * DO NOT EDIT DIRECTLY. Run \`bun scripts/update-crawler-ip-ranges.ts\` to update.
 */

export interface ProviderIpRangeGroup {
  readonly provider: string;
  readonly agentName: string;
  readonly sourceUrl: string;
  readonly cidrs: readonly string[];
}

export const PUBLISHED_AI_IP_RANGES: Record<string, ProviderIpRangeGroup> = {
  openaiSearchbot: {
    provider: "openai",
    agentName: "OAI-SearchBot",
    sourceUrl: "https://openai.com/searchbot.json",
    cidrs: ${JSON.stringify(registry.openaiSearchbot, null, 2)} as const,
  },
  openaiChatgptUser: {
    provider: "openai",
    agentName: "ChatGPT-User",
    sourceUrl: "https://openai.com/chatgpt-user.json",
    cidrs: ${JSON.stringify(registry.openaiChatgptUser, null, 2)} as const,
  },
  openaiGptbot: {
    provider: "openai",
    agentName: "GPTBot",
    sourceUrl: "https://openai.com/gptbot.json",
    cidrs: ${JSON.stringify(registry.openaiGptbot, null, 2)} as const,
  },
  perplexityBot: {
    provider: "perplexity",
    agentName: "PerplexityBot",
    sourceUrl: "https://www.perplexity.ai/perplexitybot.json",
    cidrs: ${JSON.stringify(registry.perplexityBot, null, 2)} as const,
  },
  perplexityUser: {
    provider: "perplexity",
    agentName: "Perplexity-User",
    sourceUrl: "https://www.perplexity.ai/perplexity-user.json",
    cidrs: ${JSON.stringify(registry.perplexityUser, null, 2)} as const,
  },
  googleCrawlers: {
    provider: "google",
    agentName: "Googlebot",
    sourceUrl: "https://developers.google.com/static/crawling/ipranges/common-crawlers.json",
    cidrs: ${JSON.stringify(registry.googleCrawlers, null, 2)} as const,
  },
  bingbot: {
    provider: "microsoft",
    agentName: "bingbot",
    sourceUrl: "https://www.bing.com/toolbox/bingbot.json",
    cidrs: ${JSON.stringify(registry.bingbot, null, 2)} as const,
  },
} as const;

/**
 * Get published CIDRs for a recognised agent name.
 */
export function getPublishedCidrsForAgent(agentName: string): readonly string[] {
  const norm = agentName.toLowerCase();
  for (const group of Object.values(PUBLISHED_AI_IP_RANGES)) {
    if (group.agentName.toLowerCase() === norm) {
      return group.cidrs;
    }
  }
  return [];
}
`;

  const targetPath = resolve(
    import.meta.dir,
    "../apps/web/src/lib/seo/crawler-observability/published-ranges.ts",
  );
  writeFileSync(targetPath, fileContent, "utf-8");
  console.log(`\nSuccessfully updated ${targetPath}`);
}

if (import.meta.main) {
  generatePublishedRangesFile().catch((err) => {
    console.error("Fatal error updating IP ranges:", err);
    process.exit(1);
  });
}
