/** Shared social-hub content pools (#3184).
 *
 * Leaf module: pure data with no imports, so both the generator service
 * (public-social-hub.ts) and the schema builder
 * (public-social-hub-schema.ts) can depend on it without a cycle.
 */
export const socialHubConfig = {
  genres: [
    "Fantasy",
    "Dark Fantasy",
    "Pirate",
    "Cyberpunk",
    "Sci-Fi",
    "Modern",
    "Horror",
    "Cosmic Horror",
    "Post-Apocalyptic",
    "Western",
    "Steampunk",
    "Lancer",
    "Space Opera Resistance",
    "Optimistic Exploration Sci-Fi",
    "Space Western",
    "Superhero / Comic Book",
  ],
  venueTypesByGenre: {
    Fantasy: [
      "Tavern / Inn",
      "Mead Hall",
      "Roadside Alehouse",
      "Adventurer Lodge",
      "Guildhall",
    ],
    "Dark Fantasy": [
      "Cursed Alehouse",
      "Witch's Den",
      "Underground Fighting Pit",
      "Plague Hospice",
      "Smuggler's Hollow",
    ],
    Pirate: [
      "Dockside Tavern",
      "Rum House",
      "Sailor's Inn",
      "Gambling Den",
      "Freeport Alehouse",
    ],
    Cyberpunk: [
      "Noodle Bar",
      "Dive Bar",
      "Nightclub",
      "Hacker Café",
      "Braindance Lounge",
    ],
    "Sci-Fi": [
      "Spaceport Cantina",
      "Station Bar",
      "Mess Hall",
      "Orbital Lounge",
      "Asteroid Miner Pub",
    ],
    Modern: ["Pub", "Café / Diner", "Hotel Bar", "Nightclub", "Truck Stop"],
    Horror: [
      "Goth Club",
      "Occult Café",
      "Speakeasy",
      "Blood Bar",
      "Private Lounge",
    ],
    "Cosmic Horror": [
      "Expedition Mess Hall",
      "Restricted Reading Room",
      "Weather Station Canteen",
      "Diving Bell Lounge",
      "Museum Staff Common Room",
    ],
    "Post-Apocalyptic": [
      "Trade Shack",
      "Bunker Canteen",
      "Water Bar",
      "Settlement Mess",
      "Caravanserai",
    ],
    Western: [
      "Saloon",
      "Boarding House",
      "Trading Post",
      "Roadhouse",
      "Gambling Parlour",
    ],
    Steampunk: [
      "Aetheric Lounge",
      "Artificers' Club",
      "Engine-District Pub",
      "Sky-Dock Canteen",
      "Guild Factor's Parlour",
    ],
    Lancer: [
      "Mech Bay Canteen",
      "Outpost Transit Bar",
      "Union Admin Mess Hall",
      "Pilot's Debrief Lounge",
      "Colonial Settlement Common Room",
    ],
    "Space Opera Resistance": [
      "Smuggler's Cantina",
      "Underground Resistance Hub",
      "Imperial Officers' Club",
      "Scrap-Town Bar",
      "Spaceport Transit Lounge",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Starship Observation Lounge",
      "Space Station Promenade",
      "Embassy Reception Hall",
      "Planetary Academy Campus",
      "Frontier Research Outpost Canteen",
    ],
    "Space Western": [
      "Frontier Cantina",
      "Dust-Well Saloon",
      "Asteroid Refuelling Lounge",
      "Smuggler's Speakeasy",
      "Scrappers' Gambling Den",
      "Hydroponic Distillery",
    ],
    "Superhero / Comic Book": [
      "Hero-Team HQ Commissary",
      "Superhuman Dive Bar",
      "Press-Corps Hangout",
      "Rooftop Vigilante Lookout",
      "Underground Villain Speakeasy",
    ],
  } as Record<string, string[]>,
  atmospheres: [
    "Rowdy and welcoming",
    "Tense and suspicious",
    "Quiet and melancholic",
    "Festive and chaotic",
    "Cold and professional",
    "Warm but secretive",
  ],
  wealthLevels: [
    "Destitute (dirt floors, watered-down drinks)",
    "Poor (cheap but honest)",
    "Modest (reliable, no frills)",
    "Comfortable (decent food and beds)",
    "Prosperous (good drink, private rooms)",
    "Wealthy (exclusive clientele)",
  ],
  clientelesByGenre: {
    Fantasy: [
      "Adventurers and wanderers",
      "Merchants and traders",
      "Soldiers and mercenaries",
      "Pilgrims and clergy",
      "Criminals and fence-seekers",
      "Mixed locals",
    ],
    "Dark Fantasy": [
      "Mercenaries and cultists",
      "Outlaws and desperate souls",
      "Corrupt clergy",
      "Cursed travellers",
      "Black-market traders",
    ],
    Pirate: [
      "Pirates and privateers",
      "Sailors and dockworkers",
      "Smugglers and fences",
      "Bounty hunters",
      "Stranded merchants",
    ],
    Cyberpunk: [
      "Hackers and netrunners",
      "Off-duty security",
      "Smugglers and fixers",
      "Street gang members",
      "Corporate burnouts",
    ],
    "Sci-Fi": [
      "Spacers and pilots",
      "Colonial marines",
      "Free traders",
      "Scientists and researchers",
      "Station workers",
    ],
    Modern: [
      "Office workers",
      "Local regulars",
      "Tourists and travellers",
      "Journalists and students",
      "Off-duty police",
    ],
    Horror: [
      "Occultists and hunters",
      "Lost souls and drifters",
      "Curious investigators",
      "Predators in disguise",
      "Frightened locals",
    ],
    "Cosmic Horror": [
      "Field researchers and survey crews",
      "Anxious locals with half-told stories",
      "Archive staff and visiting scholars",
      "Divers, sailors, and salvage teams",
      "Investigators following an unsettling lead",
    ],
    "Post-Apocalyptic": [
      "Scavengers and traders",
      "Wasteland survivors",
      "Cult members",
      "Mercenaries",
      "Settlers and refugees",
    ],
    Steampunk: [
      "Artificers and engine-wrights",
      "Guild factors and patent brokers",
      "Sky-dock workers and airship crew",
      "Off-duty imperial constables",
      "Underclass agitators in disguise",
    ],
    Lancer: [
      "Off-duty mech pilots and crew chiefs",
      "Union administrators and logistics staff",
      "Colonial settlers and outpost workers",
      "Mercenary contractors between jobs",
      "NHP handlers on downtime protocols",
    ],
    Western: [
      "Cowboys and drifters",
      "Miners and prospectors",
      "Outlaws and bounty hunters",
      "Townsfolk",
      "Railroad workers",
    ],
    "Space Opera Resistance": [
      "Rebel spies and informants",
      "Off-duty imperial officers and stormtroopers",
      "Smugglers and bounty hunters",
      "Mystic order exiles in hiding",
      "Scrap workers and frontier traders",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Off-duty officers",
      "Visiting alien diplomats",
      "Research scientists",
      "Civilian colonists",
      "Exchange students",
      "Stellar cartographers",
    ],
    "Space Western": [
      "Scoundrels, smugglers, and debt-dodgers",
      "Grease-stained salvage scrappers and belters",
      "Frontier marshals and bounty hunters",
      "Wildcat prospectors and ore drillers",
      "Displaced drifters and runaway nobles",
    ],
    "Superhero / Comic Book": [
      "Off-duty heroes and sidekicks",
      "Journalists and photographers chasing a scoop",
      "Costumed vigilantes keeping a low profile",
      "Government agents watching the regulars",
      "Reformed villains and parolees",
    ],
  } as Record<string, string[]>,
  troubles: [
    "The owner owes a dangerous debt that is coming due",
    "A recent violent incident was quietly buried — the responsible party may still be inside",
    "A protected criminal is hiding among the staff",
    "A back room connects to something the owner refuses to discuss",
    "A faction is using the venue as a dead-drop without the owner's knowledge",
    "The place is being squeezed out by a rival backed by local power",
  ],
  settlementTypes: [
    "Capital city",
    "Market town",
    "Frontier outpost",
    "Coastal port",
    "Remote village",
    "Crossroads hamlet",
  ],
};
