import { type Rng, defaultRng, pickFrom } from "./random-utils";
import { NAME_BAN_PROMPT } from "./public-npc";

export const factionConfig = {
  themes: [
    "Classic Fantasy",
    "Pirate",
    "Cyberpunk / Corporate",
    "Vampire / Gothic Noir",
    "Sci-Fi / Space Opera",
    "Modern Conspiracy",
    "Post-Apocalyptic",
    "Western / Frontier",
    "Steampunk",
    "Lancer",
    "Space Opera Resistance",
    "Optimistic Exploration Sci-Fi",
  ],
  typesByTheme: {
    "Classic Fantasy": [
      "Merchant Guild",
      "Secret Society",
      "Mercenary Company",
      "Temple Order",
      "Criminal Syndicate",
      "Rebel Cell",
      "Arcane Circle",
      "Guild Cartel",
      "Mystic Order",
      "Thieves' Guild",
      "Noble House",
      "Knightly Order",
    ],
    Pirate: [
      "Pirate Crew",
      "Privateer Fleet",
      "Pirate Smuggling Ring",
      "Merchant Guild",
      "Port Authority",
      "Sea Cult",
      "Salvager Guild",
      "Mutineer Enclave",
    ],
    "Cyberpunk / Corporate": [
      "Secret Society",
      "Criminal Syndicate",
      "Rebel Cell",
      "Corporate Division",
      "Hacker Collective",
      "Street Gang",
      "Black Market Network",
      "Underclass Rebel Cell",
      "Smuggler Syndicate",
      "Megacorp Subsidiary",
      "Intelligence Bureau",
    ],
    "Sci-Fi / Space Opera": [
      "Secret Society",
      "Rebel Cell",
      "Imperial Intelligence Bureau",
      "Smuggler Syndicate",
      "Resistance Cell",
      "Planetary Guild",
      "Federated Science Directorate",
      "Planetary Council",
      "Border System Power",
      "Splinter Ideological Movement",
      "Corporate Extraction Crew",
      "Imperial Fleet",
    ],
    "Modern Conspiracy": [
      "Secret Society",
      "Criminal Syndicate",
      "Rebel Cell",
      "Intelligence Bureau",
      "Smuggler Syndicate",
      "Underground Network",
      "Corporate Lobby",
      "Militia Cell",
      "Doomsday Cult",
      "Activist Cell",
      "Shadow Government",
    ],
    "Post-Apocalyptic": [
      "Mercenary Company",
      "Criminal Syndicate",
      "Rebel Cell",
      "Smuggler Syndicate",
      "Resistance Cell",
      "Scavenger Clan",
      "Raider Warband",
      "Survivor Collective",
      "Wasteland Cartel",
      "Cult Commune",
      "Trade Caravan",
    ],
    "Western / Frontier": [
      "Mercenary Company",
      "Criminal Syndicate",
      "Outlaw Gang",
      "Frontier Trading Company",
      "Land Barons' Syndicate",
      "Railroad Trust",
      "Vigilante Committee",
      "Settler Militia",
      "Indigenous Resistance",
      "Smuggler Ring",
      "Lawmen's Association",
    ],
    Steampunk: [
      "Merchant Guild",
      "Secret Society",
      "Mercenary Company",
      "Criminal Syndicate",
      "Rebel Cell",
      "Guild Cartel",
      "Airship Consortium",
      "Aetheric Research Order",
      "Imperial Intelligence Bureau",
      "Underclass Rebel Cell",
      "Inventors' League",
      "Labor Union",
    ],
    Lancer: [
      "Union Rapid Response Unit",
      "Heterodox Mech Corps",
      "NHP Research Consortium",
      "Colonial Liberation Front",
      "Corporate Extraction Crew",
      "Imperial Authority",
      "Smuggler Syndicate",
      "Imperial Fleet",
      "Resistance Cell",
      "Border System Power",
      "Splinter Ideological Movement",
    ],
    "Space Opera Resistance": [
      "Rebel Cell",
      "Resistance Cell",
      "Border System Power",
      "Splinter Ideological Movement",
      "Imperial Fleet",
      "Colonial Liberation Front",
      "Smuggler Syndicate",
      "Underground Network",
      "Planetary Council",
      "Guerrilla Warband",
      "Defector Cell",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Federated Science Directorate",
      "Planetary Council",
      "Border System Power",
      "Diplomatic Corps",
      "Research Consortium",
      "Explorer's Union",
      "Medical Aid Network",
      "Cultural Exchange Program",
      "Peacekeeping Force",
      "Trade Alliance",
    ],
  } as Record<string, string[]>,
  scopesByTheme: {
    "Classic Fantasy": [
      "Local district",
      "Single city",
      "Border region",
      "Trade route",
      "Hidden stronghold",
      "Kingdom-wide network",
    ],
    Pirate: [
      "Single ship or port",
      "Island chain",
      "Trade route",
      "Coastal region",
      "Privateer theatre",
      "Open-sea confederacy",
    ],
    "Cyberpunk / Corporate": [
      "Single arcology block",
      "City megaplex",
      "Corporate sector",
      "Black market network",
      "Cross-city underground",
      "Multi-city corporate reach",
    ],
    "Vampire / Gothic Noir": [
      "Single city underbelly",
      "Hidden manor & surrounds",
      "Shadow trade network",
      "Metropolitan high society",
      "Regional shadow court",
      "Continental blood compact",
    ],
    "Sci-Fi / Space Opera": [
      "Single station or colony",
      "Planetary surface",
      "Star system",
      "Trade lane corridor",
      "Sector-wide network",
      "Galactic fringe territory",
    ],
    "Modern Conspiracy": [
      "City borough",
      "Metropolitan area",
      "National network",
      "Cross-border operation",
      "Dark web presence",
      "Global shadow reach",
    ],
    "Post-Apocalyptic": [
      "Single settlement",
      "Wasteland outpost cluster",
      "Trade road corridor",
      "Regional scavenger territory",
      "Fortified stronghold zone",
      "Multi-region survivor network",
    ],
    "Western / Frontier": [
      "Single town",
      "County territory",
      "Trail corridor",
      "River basin",
      "Territorial expanse",
      "Cross-territory railroad reach",
    ],
    Steampunk: [
      "Single borough",
      "Industrial district",
      "City-wide guild network",
      "Trade route airway",
      "Empire-wide consortium",
      "Cross-empire aetheric reach",
    ],
    Lancer: [
      "Single colony",
      "Planetary surface",
      "System jurisdiction",
      "Long Rim corridor",
      "Bleed border zone",
      "Union-wide theatre",
    ],
    "Space Opera Resistance": [
      "Single occupied world",
      "System cell network",
      "Sector resistance front",
      "Supply corridor",
      "Cross-sector underground",
      "Galaxy-wide insurgency",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Single outpost",
      "Colony world",
      "Star system",
      "Exploration corridor",
      "Federation region",
      "Multi-species alliance space",
    ],
  } as Record<string, string[]>,
  goalsByTheme: {
    "Classic Fantasy": [
      "Control a contested trade route before a rival power does.",
      "Recover a forbidden relic buried beneath a civic landmark.",
      "Replace corrupt officials with loyal agents.",
      "Protect a hidden sanctuary from outside discovery.",
      "Break an old treaty that limits their expansion.",
      "Expose a rival faction's crimes without revealing their own.",
    ],
    Pirate: [
      "Claim a hidden harbour before a naval patrol discovers it.",
      "Recover a fragmented chart to a lost prize and decide who deserves it.",
      "Break a blockade without abandoning the vessels trapped behind it.",
      "Unite rival crews against a privateer fleet that has voided its charter.",
      "Control the only safe passage through a storm-wracked strait.",
      "Expose a port authority selling crew manifests to press gangs.",
    ],
    "Cyberpunk / Corporate": [
      "Seize majority stake in a rival megacorp before the hostile takeover closes.",
      "Wipe a damning data trail from every server before the audit drops.",
      "Install a puppet candidate in the upcoming corporate board election.",
      "Monopolize the only clean water distribution network in the district.",
      "Acquire the encryption keys to the city's surveillance backbone.",
      "Undercut a competitor's street supply chain and absorb their territory.",
    ],
    "Vampire / Gothic Noir": [
      "Blood-bind the city council before the rival clan gains a foothold.",
      "Recover the shattered tome that names every hidden bloodline in the region.",
      "Monopolize the underground blood supply before winter cuts off deliveries.",
      "Eliminate the inquisitor cell closing in on their primary haven.",
      "Awaken a dormant elder whose knowledge could shift the balance of power.",
      "Rewrite the Masquerade record to erase a recent, very public incident.",
    ],
    "Sci-Fi / Space Opera": [
      "Claim the mining rights to an uncharted asteroid belt before the empire does.",
      "Recover a derelict warship drifting in contested space.",
      "Bribe a planetary governor into breaking their imperial trade agreement.",
      "Establish a fuel depot in neutral space before the rival fleet arrives.",
      "Decrypt a distress beacon that may hold coordinates to a lost colony.",
      "Expose a rival corporation's illegal weapons testing on an inhabited moon.",
    ],
    "Modern Conspiracy": [
      "Suppress leaked documents before they reach a major news outlet.",
      "Place a sleeper agent inside the counterintelligence unit hunting them.",
      "Seize control of a city's financial clearing network.",
      "Eliminate a whistleblower without triggering a federal investigation.",
      "Acquire a foreign biotech patent through a shell company acquisition.",
      "Rig an election result in three swing districts simultaneously.",
    ],
    "Post-Apocalyptic": [
      "Secure the only functioning water purifier in the region.",
      "Claim a pre-war cache of medicine before a raider warband reaches it.",
      "Bring a salvageable power plant online before winter.",
      "Eliminate a rival settlement leader and absorb their followers.",
      "Recover an encrypted pre-war map that shows every buried supply depot.",
      "Control the only functioning radio tower and its broadcast range.",
    ],
    "Western / Frontier": [
      "Secure the land deed before the railroad company forecloses on it.",
      "Drive a rival rancher off contested grazing territory.",
      "Control the only safe river crossing in the territory.",
      "Bribe the territorial marshal before the next circuit court session.",
      "Find the outlaw who robbed their payroll shipment and make an example.",
      "Establish a trading post monopoly before a competing outfit arrives.",
    ],
    Steampunk: [
      "Acquire the patent on a revolutionary aetheric engine before a rival guild does.",
      "Sabotage a competitor's airship fleet before the imperial contract is awarded.",
      "Install a loyal factory foreman and suppress the rising labor uprising.",
      "Recover stolen schematics from a foreign intelligence bureau.",
      "Corner the coal and aether supply chain across three industrial cities.",
      "Expose a rival guild's illegal automaton conscription program.",
    ],
    Lancer: [
      "Secure blink gate access rights before the corporate extraction crew arrives.",
      "Recover a rogue NHP before Union Central authorizes a CASKET wipe.",
      "Establish a forward operating base in contested Long Rim territory.",
      "Expose a corebook violation in a rival contractor's operational record.",
      "Break a colonial extraction agreement before the next supply convoy lands.",
      "Recruit a heterodox mech corps before a rival Union faction absorbs them.",
    ],
    "Space Opera Resistance": [
      "Destroy an imperial listening post before the next fleet coordination cycle.",
      "Smuggle a resistance leader off an occupied world before extraction windows close.",
      "Sabotage the imperial shipyard's next capital-class launch.",
      "Forge supply manifests to funnel weapons to a besieged cell.",
      "Turn an imperial officer into a double agent before their loyalty review.",
      "Establish a hidden base in an asteroid field outside patrol range.",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Establish first contact protocols with a newly discovered species before military vessels arrive.",
      "Recover a damaged probe carrying irreplaceable xenobiological survey data.",
      "Mediate a resource dispute between two colony worlds before it turns violent.",
      "Chart a safe passage through an unstable nebula for the next exploration wave.",
      "Secure a diplomatic treaty with a reclusive civilization before rivals do.",
      "Restore a failing terraforming station before the colony's survival window closes.",
    ],
  } as Record<string, string[]>,
  alignments: [
    "Publicly lawful, privately ruthless",
    "Idealistic but compromised",
    "Pragmatic and profit-driven",
    "Fanatical and secretive",
    "Protective of common folk",
    "Opportunistic and divided",
  ],
  goals: [
    "Control a contested trade route before a rival power does.",
    "Recover a forbidden relic buried beneath a civic landmark.",
    "Replace corrupt officials with loyal agents.",
    "Protect a hidden sanctuary from outside discovery.",
    "Break an old treaty that limits their expansion.",
    "Expose a rival faction's crimes without revealing their own.",
  ],
  conflicts: [
    "A splinter leader is selling secrets to an enemy.",
    "Their public mission conflicts with the methods they use at night.",
    "A recent victory created debts they cannot repay.",
    "Their patron has vanished, leaving rival lieutenants in charge.",
    "A hostage, ledger, or relic could unravel their legitimacy.",
    "Their members disagree over whether the party is useful or dangerous.",
  ],
  hooks: [
    "They hire the party for a simple delivery that is actually a loyalty test.",
    "They ask for protection during a meeting with a bitter rival.",
    "They offer information about a villain in exchange for public help.",
    "They frame the party to force them into negotiation.",
    "They need outsiders to enter a place their members are forbidden to visit.",
    "They ask the party to choose between two bad successors.",
  ],
};

export const themeIdToLabel: Record<string, string> = {
  fantasy: "Classic Fantasy",
  fantasy_dark: "Classic Fantasy",
  pirate: "Pirate",
  pirate_dark: "Pirate",
  cyberpunk: "Cyberpunk / Corporate",
  cyberpunk_light: "Cyberpunk / Corporate",
  horror: "Vampire / Gothic Noir",
  horror_light: "Vampire / Gothic Noir",
  scifi: "Sci-Fi / Space Opera",
  scifi_light: "Sci-Fi / Space Opera",
  modern: "Modern Conspiracy",
  modern_dark: "Modern Conspiracy",
  apocalyptic: "Post-Apocalyptic",
  apocalyptic_light: "Post-Apocalyptic",
  western: "Western / Frontier",
  western_dark: "Western / Frontier",
  steampunk: "Steampunk",
  steampunk_dark: "Steampunk",
  lancer: "Lancer",
  lancer_light: "Lancer",
  startrek: "Optimistic Exploration Sci-Fi",
  startrek_light: "Optimistic Exploration Sci-Fi",
  "optimistic-exploration-sci-fi": "Optimistic Exploration Sci-Fi",
  "optimistic-exploration-sci-fi_dark": "Optimistic Exploration Sci-Fi",
};

export const vampireConfig = {
  archetypes: [
    "Aristocratic Court",
    "Occult Coven",
    "Predatory Brood",
    "Conspiring Syndicate",
    "Rebel Anarchs",
  ],
  bloodlines: [
    "Sanguine Nobles (Charismatic Mind-Benders)",
    "Shadow Stalkers (Nightmare Weavers)",
    "Blood Sorcerers (Occult Ritualists)",
    "Bestial Ravagers (Feral Predator Shapeshifters)",
    "Melancholic Artists (Aesthetes of Decay)",
  ],
  feedingHabits: [
    "High-Society Salons (Elite & Consent-based)",
    "Street Predation (Slums & Forgotten Alleys)",
    "Blood Trafficking (Black Market & Clinics)",
    "Occult Sacraments (Ritualistic & Sacrificial)",
    "Wild Wilderness Hunts (Deep Forests & Ruins)",
  ],
  weaknesses: [
    "Severe Sun Sensitivity (Burns instantly)",
    "Consecrated Ground Aversion (Cannot cross thresholds)",
    "Mirror & Reflection Absence (Exposes their nature)",
    "Decaying Physical Form (Needs fresh blood to look human)",
    "Silver & Wooden Vulnerability (Prevents regeneration)",
  ],
  scopes: [
    "Single city underbelly",
    "Hidden castle & border valley",
    "Trade route shadow network",
    "Metropolitan high society",
    "Continental shadow court",
  ],
  alignments: [
    "Strictly lawful, highly predatory",
    "Pragmatic and power-driven",
    "Feral, chaotic, and blood-fueled",
    "Secretive and ritual-obsessed",
    "Rebellious, seeking freedom from elders",
  ],
  goals: [
    "Infiltrate the city council and blood-bind key mortal leaders.",
    "Exhume the sarcophagus of their dormant Progenitor.",
    "Monopolize the local blood bank distribution network.",
    "Wipe out a rival werewolf pack or vampire hunters' cell.",
    "Reconstruct a shattered ancient chronicle of blood magic.",
  ],
  conflicts: [
    "The younger brood is planning a rebellion against the ancient elder.",
    "A feeding gone wrong has drawn the attention of mortal authorities.",
    "A rogue member has stolen a ledger detailing the clan's human farms.",
    "The blood supply is tainted by a mystical pathogen.",
    "An inquisitor has successfully tracked their primary haven.",
  ],
  hooks: [
    "A mysterious patron hires the party to deliver a sealed urn, which is a vampire ashes decoy.",
    "Locals ask the party to investigate a series of bloodless bodies found in the canal.",
    "A member of the clan offers to sell a list of high-profile vampire thralls in the city council.",
    "The clan captures the party and offers freedom in exchange for retrieving a relic from a sunlit temple.",
    "A dying vampire begs the party to protect their mortal family from their own sire.",
  ],
};

export const FACTION_THEME_VOICE: Record<string, string> = {
  "Classic Fantasy":
    "medieval fantasy — guilds, nobles, arcane orders, political intrigue in a world of swords and sorcery",
  Pirate:
    "system-neutral pirate adventure — crews, privateers, merchant companies, port authorities, island communities, sea cults, and contested trade routes",
  "Cyberpunk / Corporate":
    "near-future cyberpunk — megacorporations, street gangs, hackers, corporate espionage, neon-lit dystopia",
  "Vampire / Gothic Noir":
    "gothic horror — vampire covens, inquisitions, decadent aristocracy, forbidden rites, candlelit conspiracies",
  "Sci-Fi / Space Opera":
    "science fiction space opera — stellar federations, alien factions, interstellar trade, colony politics, advanced technology",
  "Modern Conspiracy":
    "modern-day thriller — intelligence agencies, secret societies, corporate conspiracies, hidden influence networks",
  "Post-Apocalyptic":
    "post-apocalyptic survival — scavenger tribes, wasteland cults, resource wars, collapsed civilisation, desperate factions",
  "Western / Frontier":
    "weird west or classic frontier — outlaws, lawmen, boomtowns, gold rushes, and harsh survival on the edge of civilization",
  Steampunk:
    "Victorian-era steampunk — guild cartels, airship consortiums, aetheric research orders, press-gang syndicates, imperial intelligence bureaux, and underclass rebel cells",
  Lancer:
    "Lancer RPG — Union rapid-response units, heterodox mech corps, NHP research consortiums, colonial liberation fronts, and corporate extraction crews operating across the Long Rim",
  "Space Opera Resistance":
    "pulpy galactic rebellion — rebel cells, imperial authorities, smuggler syndicates, ancient mystic orders, frontier guilds, and imperial fleets operating across desert worlds and occupied systems",
  "Optimistic Exploration Sci-Fi":
    "optimistic exploration sci-fi — federated councils, scientific directorates, peaceful integration, and complex diplomatic tension over ethical principles",
};

export const FACTION_NAMING_STYLES = [
  "Name this faction after a material, substance, or natural phenomenon twisted to their purpose.",
  "Name this faction after an abstract concept, virtue, or doctrine — not a person or place.",
  "Use a short stark one-word name or a tight two-word compound (e.g. 'The Writ', 'Iron Accord').",
  "Base the faction name on a specific local landmark, street, district, or geographic feature.",
  "Name the faction after their founding secret, hidden method, or signature act.",
  "Use a name that sounds like a legitimate civic institution but carries a sinister undertone.",
  "Name the faction after a historical event, failed uprising, or forgotten figure from the setting.",
  "Give the faction a name derived from an unusual profession, trade, or craft.",
  "Use an archaic or invented word that evokes the faction's cultural roots.",
  "Name the faction after a symbol, emblem, or recurring motif associated with their work.",
];

export const FACTION_NPC_NAMING_STYLES = [
  "Give each NPC a name that sounds distinctly local — not generic fantasy.",
  `Each NPC name should have an unusual phonetic texture. ${NAME_BAN_PROMPT}`,
  "Give each NPC a short street name or title that hints at their role — invent an original one, do not reuse common examples.",
  "Use names that suggest a specific cultural or ethnic origin consistent with the setting.",
  "Each NPC should have a name that is easy to say aloud at a gaming table.",
];

export function factionBase(type: string, rng: Rng = defaultRng): string {
  const map: Record<string, string[]> = {
    "Pirate Crew": [
      "A crew-owned ship anchored in a neutral cove",
      "A floating camp that moves between safe harbours",
      "A hidden dockyard protected by shared articles",
    ],
    "Pirate Smuggling Ring": [
      "A chain of chandlers, warehouses, and discreet coves connected by coded manifests",
      "A portside network that moves people and cargo around customs patrols",
      "A rotating set of safe houses whose owners only know one link in the route",
    ],
    "Merchant Guild": [
      "A bonded counting house whose ledgers are sealed by city charter",
      "A licensed exchange hall at the centre of the trade district",
      "A warehouse compound that no sheriff may enter without a writ",
    ],
    "Secret Society": [
      "A private dining club whose membership list is never committed to paper",
      "A decommissioned observatory reached through a hidden press in the library stacks",
      "Rotating safe houses connected by messenger-drop protocols",
    ],
    "Mercenary Company": [
      "A fortified barracks compound outside the city walls",
      "A charted garrison holding neutral ground between two rival lords",
      "A licensed inn that doubles as a staging ground for contract work",
    ],
    "Temple Order": [
      "A sanctified compound built above the sealed catacombs",
      "A pilgrimage waystation that doubles as an intelligence hub",
      "A charitable hospice whose basement holds restricted archives",
    ],
    "Criminal Syndicate": [
      "A legitimate bathhouse with soundproofed rooms below street level",
      "A moneylender's office whose public ledgers contain a second set of books",
      "A district of connected properties linked by sealed passages",
    ],
    "Rebel Cell": [
      "A print-house running two sets of accounts",
      "A disused chapel in a contested neighbourhood where records are rarely checked",
      "A network of sympathiser homes linked by a rotating code phrase",
    ],
    "Arcane Circle": [
      "A registered scholar's hall with warded inner chambers",
      "A cartographer's guild whose maps contain hidden notation systems",
      "A canal barge anchored in a dock district where manifests go uninspected",
    ],
    "Megacorporation Megagroup": [
      "A sealed corporate tower whose lower floors are open to the public and upper floors are not on any map",
      "A campus of linked facilities connected by private transit lines that bypass city checkpoints",
      "A data-centre compound in a legally ambiguous special economic zone",
    ],
    "Corporate Syndicate": [
      "A registered LLC with rotating directors and no fixed address",
      "A licensed private security firm that maintains offices in three jurisdictions simultaneously",
      "A shell company whose registered seat is a post-box in a compliant offshore district",
    ],
    "Hacker Collective": [
      "A distributed mesh of rented server nodes and anonymous relay points",
      "A legitimate ISP whose routing infrastructure doubles as a covert comms layer",
      "Rotating physical dead-drops in public infrastructure — lockers, charging stations, transit hubs",
    ],
    "Street Gang Alliance": [
      "A block of contested commercial units enforced by informal tax agreements",
      "A series of interconnected basement spaces beneath a market district",
      "A community centre operating with city permits while the basement handles other business",
    ],
    "Vampire Coven": [
      "A sealed private estate whose deed has not changed hands in three centuries",
      "A licensed sanatorium whose patient records are never released to outside authorities",
      "A labyrinthine wine cellar beneath a respectable merchant's townhouse",
    ],
    "Inquisition Watch": [
      "A fortified chapter-house adjacent to the civil courthouse",
      "A mobile tribunal that establishes temporary jurisdiction wherever the investigation leads",
      "A warded archive annexed to the city's oldest cathedral",
    ],
    "Stellar Federation Alliance": [
      "A neutral space station positioned at a strategically contested transit point",
      "A diplomatic compound on a contested colony world with extraterritorial status",
      "A fleet of registered humanitarian vessels that doubles as a mobile command structure",
    ],
    "Intelligence Agency": [
      "A nondescript government office building whose basement floors are not on the building plan",
      "A chain of legitimate consulting firms that share encrypted back-office infrastructure",
      "An embassy annex operating under diplomatic immunity",
    ],
    "Scavenger Tribe": [
      "A fortified salvage yard at the edge of a collapsed industrial zone",
      "A mobile convoy that claims no fixed territory but controls key supply corridors",
      "A series of hidden caches spread across a hundred kilometres of dead highway",
    ],
    "Wasteland Cult": [
      "A sealed compound built inside a pre-collapse water treatment facility",
      "A fortified hilltop site with sightlines across three days of travel in every direction",
      "A network of underground bunkers connected by service tunnels from before the collapse",
    ],
    "Guild Cartel": [
      "A chartered Guildhall whose brass-plated doors are sealed by imperial writ",
      "A foundry complex whose steam vents obscure the entrances to private meeting chambers",
      "A bonded patent office whose archive vaults hold the licensing papers for half the city's industry",
    ],
    "Airship Consortium": [
      "A mooring tower compound above the cloud line, accessible only by scheduled dirigible",
      "A registered sky-dock with private bays where manifests are submitted only to consortium ledgers",
      "A floating platform anchored above international waters where no city ordinance applies",
    ],
    "Aetheric Research Order": [
      "A sealed laboratory annexe beneath the Imperial Institute of Applied Sciences",
      "A decommissioned clocktower whose upper floors have been warded against surveillance",
      "A private scholarly estate whose library holds restricted aetheric formulae under charter lock",
    ],
    "Imperial Intelligence Bureau": [
      "A nondescript government building whose sub-basement floors appear on no architectural plan",
      "A chain of post offices operating under Crown warrant with encrypted dispatch infrastructure",
      "An embassy anteroom operating under diplomatic immunity with unrestricted cipher access",
    ],
    "Underclass Rebel Cell": [
      "A print shop running two sets of accounts behind a false boiler room wall",
      "A disused engine hall in the smog district where census officers rarely venture",
      "A network of tenement rooftops connected by signal lantern protocols",
    ],
    "Union Rapid Response Unit": [
      "A hardened forward operating base embedded in a contested colonial settlement",
      "A Union frigate holding geosynchronous orbit as a mobile command platform",
      "A decommissioned administrative compound repurposed under emergency Union charter",
    ],
    "Heterodox Mech Corps": [
      "An unregistered hangar on the Long Rim operating under a shell licensing agreement",
      "A salvage yard whose mech repair bays double as an unofficial tactical staging ground",
      "A mobile barge convoy that keeps no fixed port and answers no flag",
    ],
    "NHP Research Consortium": [
      "A shielded research station in a low-traffic transit corridor with restricted docking access",
      "A distributed server architecture spread across three systems under academic charter",
      "A sealed laboratory embedded within a Union university campus under dual-key access protocols",
    ],
    "Colonial Liberation Front": [
      "A network of sympathiser safe houses spread across a colonial outpost's residential district",
      "A fortified position in a contested bleed zone where Union authority is ambiguous",
      "A mobile cell structure with no fixed base and rotating comms encryption",
    ],
    "Corporate Extraction Crew": [
      "A legitimately registered subsidiary operating under a Union commercial licence",
      "A contracted security compound adjacent to a resource extraction site",
      "A private orbital platform registered to a shell entity in a non-Union jurisdiction",
    ],
    "Imperial Authority": [
      "A gleaming sector-command spire projecting force across the capital city",
      "A fortified garrison built on the ruins of the planet's previous democratic parliament",
      "A mobile orbital command station enforcing blockades and custom checks",
    ],
    "Mystic Order": [
      "An ancient, hidden temple carved into the cliffs of a remote desert world",
      "A meditation chamber disguised as a humble merchant's quarters",
      "The ruins of a once-great academy now swallowed by the jungle",
    ],
    "Smuggler Syndicate": [
      "A crowded, lawless cantina built into a hollowed-out asteroid",
      "A modular docking bay that constantly changes configuration to confuse inspectors",
      "A rusted freighter graveyard that hides a fully operational black market",
    ],
    "Imperial Fleet": [
      "A massive dreadnought hanging ominously in the sky above the colony",
      "A sprawling orbital shipyard strictly off-limits to civilian traffic",
      "A blockade flotilla enforcing a quarantine over a restive system",
    ],
    "Resistance Cell": [
      "A subterranean bunker beneath a bustling starport",
      "A repurposed deep-space communications relay hiding in plain sight",
      "A makeshift camp hidden within the wreckage of an old capital ship",
    ],
    "Planetary Guild": [
      "A massive industrial processing plant where laborers toil under heavy surveillance",
      "The polished halls of a merchant consortium that dictates planetary trade laws",
      "A tightly guarded mining colony built into the ice of a frozen moon",
    ],
  };
  return pickFrom(
    map[type] ?? [
      "A neutral facility whose access is controlled and whose records are not shared",
      "A licensed premises that provides cover for activities conducted elsewhere",
      "A distributed network of locations with no single point of failure",
    ],
    rng,
  );
}

export function factionResource(type: string, rng: Rng = defaultRng): string {
  const map: Record<string, string[]> = {
    "Pirate Crew": [
      "A crew-owned vessel, shared articles, and trusted anchorages along the coast",
      "Prize cargo, tide charts, and intelligence traded by dockworkers and sailors",
      "A reputation that can open a free port or trigger a naval manhunt",
    ],
    "Pirate Smuggling Ring": [
      "Forged cargo manifests, hidden berths, and trusted contacts inside customs offices",
      "Access to routes that bypass blockades and move people without exposing their identities",
      "A debt ledger binding captains, dockworkers, and merchants to mutual silence",
    ],
    "Merchant Guild": [
      "Exclusive trade licences, bonded debts, and letters of introduction that open every city gate",
      "Commodity price information days before it reaches the open market",
      "Certified seals of provenance that determine what goods may legally change hands",
    ],
    "Secret Society": [
      "Compromising knowledge distributed in sealed fragments held by separate members",
      "A curated register of favours owed by officials, merchants, and clergy",
      "Access to a network of false identities and safe-passage routes",
    ],
    "Mercenary Company": [
      "Contractual access to trained soldiers who ask no political questions",
      "Neutral enforcement services hired by every side of every dispute",
      "An archive of battlefield contracts that constitute decades of political leverage",
    ],
    "Temple Order": [
      "Exclusive rights over burial rites, confessions, and civic oaths",
      "A pharmaceutical supply chain running through the charitable district",
      "Institutional immunity protecting their premises from search or seizure",
    ],
    "Criminal Syndicate": [
      "Control over the city's informal credit markets and enforcement ecosystem",
      "Detailed knowledge of every patrol route, informant, and magistrate's price",
      "A distribution network for restricted goods running through legitimate storefronts",
    ],
    "Rebel Cell": [
      "A verified printing and distribution network for prohibited materials",
      "Contacts embedded in the guard, the census office, and the merchant registry",
      "Secure courier routes that move people, messages, and contraband past checkpoints",
    ],
    "Arcane Circle": [
      "Proprietary ritual techniques licensed to no outside practitioner",
      "A sealed archive of magical precedents that defines what is legally permitted",
      "Controlled access to rare components that no other supplier will touch",
    ],
    "Megacorporation Megagroup": [
      "Patent portfolios, regulatory capture, and the ability to rewrite local law through lobbying",
      "A private security force larger than the city police and legally permitted to operate with fewer constraints",
      "Exclusive contracts with critical infrastructure — power, water, data, transit",
    ],
    "Corporate Syndicate": [
      "Shell-company ownership of key residential and commercial properties across the district",
      "Leveraged debt held against every small business in the target sector",
      "Proprietary logistics infrastructure that competitors cannot access without their permission",
    ],
    "Hacker Collective": [
      "Zero-day exploits, surveillance backdoors, and access to every networked system in the city",
      "A distributed archive of intercepted communications from every major institution",
      "The ability to make anyone's digital identity disappear — or reappear differently",
    ],
    "Street Gang Alliance": [
      "Control of informal economies: protection, distribution, and dispute resolution in three districts",
      "Detailed knowledge of every surveillance blind spot, patrol schedule, and officer price",
      "Loyalty networks that extend into city maintenance, transit, and low-level civil service",
    ],
    "Vampire Coven": [
      "Centuries of accumulated wealth, property, and blackmail material on every notable family",
      "The ability to alter memory, compel testimony, and move unseen through any social tier",
      "A network of thralls embedded in the city's legal, medical, and religious institutions",
    ],
    "Inquisition Watch": [
      "Legal authority to detain, interrogate, and seize assets without civil court oversight",
      "An archive of confessions, heresies, and crimes dating back three generations",
      "Jurisdiction that supersedes local law in matters defined — broadly — as spiritual threat",
    ],
    "Stellar Federation Alliance": [
      "Trade route licensing, customs authority, and the right to impose blockades under federation charter",
      "A shared military asset pool that member states cannot individually match",
      "Diplomatic recognition that determines which colonies and stations are treated as sovereign",
    ],
    "Intelligence Agency": [
      "Surveillance infrastructure covering communications, financial transactions, and physical movement",
      "Classified leverage on every significant political, corporate, and criminal actor in the region",
      "The legal authority to classify, redact, and deny — which is effectively the power to erase events",
    ],
    "Scavenger Tribe": [
      "Access to pre-collapse technology caches and the knowledge to operate what others cannot",
      "Control of the only reliable route through a stretch of dead territory",
      "A repair and fabrication capability that no other group in the region can match",
    ],
    "Wasteland Cult": [
      "Clean water, food stockpiles, and medical supplies — distributed exclusively to the faithful",
      "A coherent ideology that provides meaning in a world without institutions",
      "Armed enforcers who believe completely in what they are protecting",
    ],
    "Guild Cartel": [
      "Imperial patent licences and the legal authority to shut down any non-licensed operation in the city",
      "Exclusive access to aetheric components that no independent artificer can source elsewhere",
      "A bonded ledger of guild debts and performance bonds that constitute leverage over every major manufacturer",
    ],
    "Airship Consortium": [
      "Control over the only viable air-freight routes connecting the major industrial cities",
      "A fleet of armed courier vessels whose cargo manifests are never opened by customs officers",
      "Exclusive mooring rights at key aetheric refuelling stations across the continent",
    ],
    "Aetheric Research Order": [
      "Proprietary aetheric formulae that determine what weapons, engines, and medicines the Empire can produce",
      "A sealed research archive whose contents the Imperial Ministry does not fully understand but cannot afford to lose",
      "Controlled access to refined aetheric ore — the fuel for every advanced engine in the known world",
    ],
    "Imperial Intelligence Bureau": [
      "Surveillance infrastructure covering telegram traffic, financial ledgers, and courier routes across the Empire",
      "Classified leverage on every significant guild factor, colonial administrator, and opposition figure",
      "The legal authority to classify, seal, and deny — which is effectively the power to erase inconvenient events",
    ],
    "Underclass Rebel Cell": [
      "A verified pamphlet and broadsheet distribution network that reaches every engine-district tenement",
      "Contacts embedded in the factory floor, the census office, and the guild apprentice registry",
      "Secure courier routes through the smog tunnels that move people, messages, and contraband past company checkpoints",
    ],
    "Union Rapid Response Unit": [
      "Union-backed supply chains, medical infrastructure, and legal authority that no colonial faction can legally refuse",
      "Rapid deployment assets — carriers, mechs, and specialist personnel — that can be on-site within hours of authorisation",
      "The legal standing to classify, commandeer, and redefine the operational context of any contested situation",
    ],
    "Heterodox Mech Corps": [
      "Unlicensed mech frames jury-rigged from salvage, running subsystems that Union doesn't officially recognise",
      "A roster of pilots with bleed tolerance above standard clearance and no intention of disclosing it",
      "Supply contracts with three different factions, none of whom know about the other two",
    ],
    "NHP Research Consortium": [
      "Cascaded NHP assets operating at the legal edge of Union containment protocols",
      "Proprietary data on non-human cognition that no other institution in the sector has replicated",
      "Leverage over every organisation that has ever quietly used their NHP consultation services",
    ],
    "Colonial Liberation Front": [
      "Deep roots in the local population — every safe house, every supply cache, every sympathiser is a local",
      "Firsthand knowledge of Union administrative failures that make for devastating public documentation",
      "Enough field-stripped and improvised hardware to make any contested zone expensive to hold",
    ],
    "Corporate Extraction Crew": [
      "Proprietary extraction technology and the contracts that legally entitle them to use it",
      "A Union-adjacent legal team whose job is to ensure every operation remains just inside the line",
      "Leverage over the colonial administrator who approved the contract in the first place",
    ],
    "Imperial Authority": [
      "Absolute legal authority and the overwhelming military force required to back it up",
      "An expansive network of informants, spies, and surveillance drones",
      "Control over the planetary defense grid and all orbital traffic",
    ],
    "Mystic Order": [
      "Ancient texts, relics, and lost techniques of an energy-manipulating discipline",
      "A hidden network of sympathizers who revere the old ways",
      "Deeply honed intuition and combat skills that defy modern weaponry",
    ],
    "Smuggler Syndicate": [
      "Secret hyper-routes and hyperdrive modifications that bypass imperial checkpoints",
      "Counterfeit clearance codes and bribed imperial customs officials",
      "A vast fleet of unregistered, heavily modified blockade runners",
    ],
    "Imperial Fleet": [
      "Capital ships capable of glassing a continent from orbit",
      "Endless waves of disciplined troopers and standardized fighter squadrons",
      "Complete control over interstellar communications relays",
    ],
    "Resistance Cell": [
      "Stolen imperial codes, intercepted transmissions, and encrypted frequencies",
      "The fierce loyalty of the oppressed populace who provide safe harbor",
      "Sabotage equipment, stolen ordnance, and a willingness to die for the cause",
    ],
    "Planetary Guild": [
      "Exclusive control over the extraction and refinement of a rare hyper-fuel",
      "Deep pockets and the ability to lobby or bribe imperial governors",
      "A monopoly on off-world transport for civilian goods",
    ],
  };
  return pickFrom(
    map[type] ?? [
      "Specialised knowledge or access that no other group in the region controls",
      "A network of obligations, debts, and dependencies too entangled to cut cleanly",
      "Control of a single critical resource that everyone else needs to function",
    ],
    rng,
  );
}

// ---------------------------------------------------------------------------
// Faction public API
// ---------------------------------------------------------------------------

export const nomadClanConfig = {
  roles: [
    "Family Convoy",
    "Smuggler Band",
    "Tech Scavengers",
    "Wasteland Traders",
    "Mercenary Riders",
    "Ex-Corporate Refugees",
    "Courier Network",
    "Raider-Adjacent",
    "Spiritual Road Cult",
  ],
  tones: [
    "Grounded, gritty survival",
    "Neon-punk, chrome and dust",
    "Weird and desperate",
    "Hopeful, tight-knit community",
    "Violent, road-law rules",
  ],
  territories: [
    "Highway corridors and fuel stops",
    "Badlands and desert routes",
    "Arcology outskirts and perimeter roads",
    "Flooded lowland transit zones",
    "Orbital scrapyards and drop-points",
    "Ruined suburbs and ring-roads",
    "Borderland checkpoints and no-man's-land",
  ],
  conflicts: [
    "Rival clan encroaching on their primary route",
    "Corporate pressure to surrender a cargo or a person",
    "Fuel scarcity forcing dangerous detours",
    "Internal succession fracturing clan loyalty",
    "Lost cargo that someone will kill to recover",
    "Cursed or experimental tech hidden in the convoy",
    "Law enforcement crackdown closing key corridors",
    "Betrayal by a former ally who sold their route",
  ],
  hooks: [
    "The clan needs an outsider to carry something across a checkpoint their faces are known at.",
    "A clan member has gone missing at a waystation known for disappearances.",
    "The clan's lead mechanic has decoded something hidden in recovered corporate salvage.",
    "A dying rider names the party as witnesses to a debt the clan will honour — or dispute.",
    "The clan offers a safe convoy route in exchange for dealing with what is blocking it.",
    "A corporate fixer is paying for intel on the clan's schedule — and they know it.",
  ],
  goals: [
    "Secure the fuel depot before a rival clan claims squatter's rights.",
    "Recover a clan member sold to a corporate labour farm.",
    "Establish a new safe corridor after their primary route was compromised.",
    "Prove the clan's code was broken by an insider and find the traitor.",
    "Acquire a vehicle capable of reaching the next settlement before the season closes.",
    "Negotiate a truce with a rival clan before the corporate pressure destroys them both.",
  ],
};
