const COSMIC_HORROR_SETTLEMENT = {
  sizes: [
    { name: "Survey Camp", range: "12–60 residents", pointsOfInterestCount: 3 },
    {
      name: "Remote Village",
      range: "60–500 residents",
      pointsOfInterestCount: 4,
    },
    {
      name: "Coastal Town",
      range: "500–4,000 residents",
      pointsOfInterestCount: 5,
    },
    {
      name: "University District",
      range: "4,000–18,000 residents",
      pointsOfInterestCount: 6,
    },
  ],
  environments: [
    "Fog-bound coastline",
    "Highland observatory plateau",
    "Flooded river valley",
    "Windswept island",
    "Forest around an old excavation",
    "Industrial university quarter",
  ],
  primaryFunctions: [
    "Astronomical observation post",
    "Expedition supply town",
    "University research district",
    "Quarantine checkpoint",
    "Archive and rare-book centre",
    "Deep-water fishing community",
  ],
  tones: [
    "Methodical but uneasy",
    "Outwardly ordinary, quietly strained",
    "Fog-muted and watchful",
    "Scholarly and secretive",
    "Remote and underprepared",
  ],
  mainTensions: [
    "A survey team returned with one member missing from every photograph",
    "The town's tide tables now predict events on land",
    "A sealed archive has begun issuing requests for materials",
    "Residents disagree about whether last week's eclipse happened",
    "A quarantine order is hiding an anomaly rather than an illness",
  ],
  authorityTypes: [
    "University field director",
    "Harbour and quarantine board",
    "Inherited town council",
    "Expedition sponsor's representative",
    "Archive custodian with emergency powers",
  ],
  notableLocations: [
    "The tidal observatory with its lenses covered at noon",
    "A reading room whose catalogue omits one entire floor",
    "The weather station that no longer records wind",
    "A boarding house used by every expedition since the first survey",
    "The sealed pier where unregistered boats arrive at dawn",
    "A civic hall built over an excavation nobody discusses",
  ],
  factions: [
    "The Miskatonic field office",
    "The harbour quarantine committee",
    "A discreet antiquarian society",
    "The families who financed the first expedition",
    "The volunteer coast-watch service",
  ],
  namePrefixes: ["Dun", "Inn", "Lorn", "Morrow", "Nant", "Orra", "Pel", "Rill"],
  nameSuffixes: [
    "mouth",
    "reach",
    "field",
    "haven",
    "point",
    "mere",
    "watch",
    "cairn",
  ],
};

export const settlementConfig = {
  genres: [
    "Fantasy",
    "Pirate",
    "Dark Fantasy",
    "Cyberpunk",
    "Sci-Fi",
    "Post-Apocalyptic",
    "Modern",
    "Horror",
    "Cosmic Horror",
    "Western",
    "Steampunk",
    "Space Opera Resistance",
    "Optimistic Exploration Sci-Fi",
  ],

  sizesByGenre: {
    Fantasy: [
      { name: "Hamlet", range: "50–100 inhabitants", pointsOfInterestCount: 3 },
      {
        name: "Village",
        range: "100–500 inhabitants",
        pointsOfInterestCount: 4,
      },
      {
        name: "Town",
        range: "500–5,000 inhabitants",
        pointsOfInterestCount: 5,
      },
      {
        name: "City",
        range: "5,000–20,000 inhabitants",
        pointsOfInterestCount: 6,
      },
    ],
    Pirate: [
      {
        name: "Hidden Cove",
        range: "20–100 residents",
        pointsOfInterestCount: 3,
      },
      {
        name: "Free Port",
        range: "100–1,000 residents",
        pointsOfInterestCount: 4,
      },
      {
        name: "Harbour Town",
        range: "1,000–8,000 residents",
        pointsOfInterestCount: 5,
      },
      {
        name: "Island Capital",
        range: "8,000+ residents",
        pointsOfInterestCount: 6,
      },
    ],
    "Dark Fantasy": [
      {
        name: "Forsaken Village",
        range: "50–300 survivors",
        pointsOfInterestCount: 3,
      },
      {
        name: "Blighted Town",
        range: "300–2,000 inhabitants",
        pointsOfInterestCount: 4,
      },
      {
        name: "Corrupted City",
        range: "2,000–10,000 inhabitants",
        pointsOfInterestCount: 5,
      },
      {
        name: "Ruined Stronghold",
        range: "10,000+ inhabitants",
        pointsOfInterestCount: 6,
      },
    ],
    Cyberpunk: [
      { name: "Block", range: "200–1,000 residents", pointsOfInterestCount: 3 },
      {
        name: "District",
        range: "1,000–10,000 residents",
        pointsOfInterestCount: 4,
      },
      {
        name: "Borough",
        range: "10,000–50,000 residents",
        pointsOfInterestCount: 5,
      },
      { name: "Sector", range: "50,000+ residents", pointsOfInterestCount: 6 },
    ],
    "Sci-Fi": [
      { name: "Outpost", range: "20–200 personnel", pointsOfInterestCount: 3 },
      {
        name: "Station",
        range: "200–2,000 personnel",
        pointsOfInterestCount: 4,
      },
      {
        name: "Colony",
        range: "2,000–20,000 inhabitants",
        pointsOfInterestCount: 5,
      },
      {
        name: "Habitat",
        range: "20,000+ inhabitants",
        pointsOfInterestCount: 6,
      },
    ],
    "Post-Apocalyptic": [
      { name: "Camp", range: "20–100 survivors", pointsOfInterestCount: 3 },
      { name: "Outpost", range: "100–500 survivors", pointsOfInterestCount: 4 },
      {
        name: "Settlement",
        range: "500–3,000 survivors",
        pointsOfInterestCount: 5,
      },
      {
        name: "Stronghold",
        range: "3,000+ survivors",
        pointsOfInterestCount: 6,
      },
    ],
    Modern: [
      { name: "Hamlet", range: "50–200 residents", pointsOfInterestCount: 3 },
      {
        name: "Village",
        range: "200–2,000 residents",
        pointsOfInterestCount: 4,
      },
      {
        name: "Town",
        range: "2,000–20,000 residents",
        pointsOfInterestCount: 5,
      },
      { name: "City", range: "20,000+ residents", pointsOfInterestCount: 6 },
    ],
    Horror: [
      {
        name: "Isolated Community",
        range: "50–300 inhabitants",
        pointsOfInterestCount: 3,
      },
      {
        name: "Village",
        range: "300–1,000 inhabitants",
        pointsOfInterestCount: 4,
      },
      {
        name: "Town",
        range: "1,000–5,000 inhabitants",
        pointsOfInterestCount: 5,
      },
      {
        name: "City Quarter",
        range: "5,000–15,000 inhabitants",
        pointsOfInterestCount: 6,
      },
    ],
    "Cosmic Horror": COSMIC_HORROR_SETTLEMENT.sizes,
    Western: [
      { name: "Homestead", range: "10–50 residents", pointsOfInterestCount: 3 },
      {
        name: "Settlement",
        range: "50–500 residents",
        pointsOfInterestCount: 4,
      },
      { name: "Town", range: "500–3,000 residents", pointsOfInterestCount: 5 },
      {
        name: "Boom Town",
        range: "3,000+ residents",
        pointsOfInterestCount: 6,
      },
    ],
    Steampunk: [
      {
        name: "Village",
        range: "100–500 inhabitants",
        pointsOfInterestCount: 3,
      },
      {
        name: "Mill Town",
        range: "500–5,000 inhabitants",
        pointsOfInterestCount: 4,
      },
      {
        name: "Industrial City",
        range: "5,000–50,000 inhabitants",
        pointsOfInterestCount: 5,
      },
      {
        name: "Metropolis",
        range: "50,000+ inhabitants",
        pointsOfInterestCount: 6,
      },
    ],
    "Space Opera Resistance": [
      { name: "Hidden Base", range: "50–500 rebels", pointsOfInterestCount: 3 },
      {
        name: "Colony",
        range: "500–5,000 inhabitants",
        pointsOfInterestCount: 4,
      },
      {
        name: "Spaceport City",
        range: "5,000–50,000 inhabitants",
        pointsOfInterestCount: 5,
      },
      {
        name: "Imperial Capital",
        range: "50,000+ inhabitants",
        pointsOfInterestCount: 6,
      },
    ],
    "Optimistic Exploration Sci-Fi": [
      { name: "Outpost", range: "20–200 personnel", pointsOfInterestCount: 3 },
      {
        name: "Station",
        range: "200–2,000 personnel",
        pointsOfInterestCount: 4,
      },
      {
        name: "Colony",
        range: "2,000–20,000 inhabitants",
        pointsOfInterestCount: 5,
      },
      {
        name: "Core World City",
        range: "50,000+ inhabitants",
        pointsOfInterestCount: 6,
      },
    ],
  } as Record<
    string,
    { name: string; range: string; pointsOfInterestCount: number }[]
  >,

  environmentsByGenre: {
    Fantasy: [
      "Forest edge",
      "Coastal harbour",
      "River crossing",
      "Mountain pass",
      "Open plains",
      "Desert oasis",
      "Underground cavern",
      "Marshland",
    ],
    Pirate: [
      "Sheltered island cove",
      "Storm-exposed harbour",
      "Coral atoll",
      "Mangrove coast",
      "Volcanic island",
      "Reef passage",
    ],
    "Dark Fantasy": [
      "Blighted forest",
      "Corrupted river valley",
      "Cursed ruins",
      "Ash wastes",
      "Plague-touched coast",
      "Shadowmere swamp",
    ],
    Cyberpunk: [
      "Dense urban sprawl",
      "Corporate arcology district",
      "Underground tunnel network",
      "Rooftop colony",
      "Industrial wasteland",
      "Flooded lower city",
    ],
    "Sci-Fi": [
      "Orbital station",
      "Asteroid mining colony",
      "Terraformed moon surface",
      "Deep space waystation",
      "Generation ship district",
      "Subterranean habitat",
    ],
    "Post-Apocalyptic": [
      "Ruined city centre",
      "Fortified hilltop",
      "Underground bunker complex",
      "Irradiated zone border",
      "Salvage fields",
      "River delta refuge",
    ],
    Modern: [
      "Coastal town",
      "Rural countryside",
      "Urban suburb",
      "Mountain community",
      "Island village",
      "Desert border town",
    ],
    Horror: [
      "Remote valley",
      "Misty moorland",
      "Ancient forest",
      "Coastal cliffs",
      "Underground catacombs",
      "Decaying city district",
    ],
    "Cosmic Horror": COSMIC_HORROR_SETTLEMENT.environments,
    Western: [
      "Desert plains",
      "Canyon river crossing",
      "Mountain mining territory",
      "Railroad junction",
      "Frontier grassland",
      "Border river town",
    ],
    Steampunk: [
      "Industrial river city",
      "Sky platform",
      "Underground rail hub",
      "Coastal smog district",
      "Mountain factory town",
      "Imperial canal port",
    ],
    "Space Opera Resistance": [
      "Desert wasteland",
      "Ice planet",
      "Jungle moon",
      "Gas giant orbit",
      "Asteroid belt",
      "Volcanic world",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Class M Planet",
      "Asteroid Belt",
      "Gas Giant Atmosphere",
      "Binary Star System",
      "Nebula Edge",
    ],
  } as Record<string, string[]>,

  primaryFunctionsByGenre: {
    Fantasy: [
      "Trade hub",
      "Military fortress",
      "Religious shrine",
      "Mining settlement",
      "Noble seat",
      "Farming community",
      "Border checkpoint",
      "Pilgrimage town",
      "Academic city",
    ],
    Pirate: [
      "Free-trade harbour",
      "Pirate haven",
      "Ship repair and provisioning",
      "Smuggling exchange",
      "Naval resupply station",
      "Fishing and salvage community",
    ],
    "Dark Fantasy": [
      "Cursed stronghold",
      "Plague quarantine zone",
      "Necromancer's base",
      "Warlord garrison",
      "Desperate refuge",
      "Fallen temple settlement",
    ],
    Cyberpunk: [
      "Corporate logistics hub",
      "Black market district",
      "Data brokerage centre",
      "Manufacturing zone",
      "Entertainment district",
      "Gang headquarters",
      "Refugee enclave",
    ],
    "Sci-Fi": [
      "Resource extraction colony",
      "Research station",
      "Military outpost",
      "Trade waystation",
      "Quarantine zone",
      "Administrative hub",
      "Prison colony",
    ],
    "Post-Apocalyptic": [
      "Survivor refuge",
      "Salvage base",
      "Agricultural commune",
      "Trading post",
      "Fortified stronghold",
      "Hidden sanctuary",
      "Cult community",
    ],
    Modern: [
      "Tourist destination",
      "Administrative centre",
      "Industrial town",
      "Fishing community",
      "University town",
      "Border checkpoint",
      "Farming community",
    ],
    Horror: [
      "Isolated village",
      "Hidden blood court",
      "Cult commune",
      "Quarantine zone",
      "Ancient pilgrimage site",
      "Research facility",
      "Crumbling estate settlement",
    ],
    "Cosmic Horror": COSMIC_HORROR_SETTLEMENT.primaryFunctions,
    Western: [
      "Railroad depot",
      "Mining claim town",
      "Cattle drive waystation",
      "Border sheriff outpost",
      "Trading post",
      "Outlaw hideout",
    ],
    Steampunk: [
      "Factory and works district",
      "Airship port",
      "Rail junction hub",
      "Inventor's enclave",
      "Imperial administration post",
      "Smuggling harbour",
    ],
    "Space Opera Resistance": [
      "Smuggler haven",
      "Imperial garrison",
      "Moisture farm",
      "Rebel listening post",
      "Scrap yard and salvage",
      "Spice mining facility",
      "Ancient temple ruins",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Scientific Research",
      "Diplomatic Hub",
      "Fleet Resupply",
      "Agricultural Breadbasket",
      "First Contact Staging Area",
    ],
  } as Record<string, string[]>,

  tonesByGenre: {
    Fantasy: [
      "Cosy and welcoming",
      "Grim and weathered",
      "Mysterious and secretive",
      "Heroic and proud",
      "Decadent and corrupt",
      "Frontier and rough",
    ],
    Pirate: [
      "Salt-worn and defiant",
      "Rowdy but watchful",
      "Storm-dark and superstitious",
      "Prosperous and lawless",
      "Heroic and free-spirited",
    ],
    "Dark Fantasy": [
      "Oppressive and doomed",
      "Grimdark and hopeless",
      "Eerie and cursed",
      "Desperate and violent",
      "Cold and ruthless",
    ],
    Cyberpunk: [
      "Oppressive and surveilled",
      "Chaotic and vibrant",
      "Desperate and hungry",
      "Neon-soaked and decadent",
      "Underground and defiant",
    ],
    "Sci-Fi": [
      "Sterile and efficient",
      "Isolated and claustrophobic",
      "Frontier and optimistic",
      "Corporate and controlled",
      "Decaying and neglected",
    ],
    "Post-Apocalyptic": [
      "Grim and survivalist",
      "Hopeful but fragile",
      "Paranoid and militarised",
      "Desperate and fractured",
      "Eerily peaceful",
    ],
    Modern: [
      "Quiet and overlooked",
      "Tense and divided",
      "Prosperous and complacent",
      "Declining and nostalgic",
      "Vibrant and contested",
    ],
    Horror: [
      "Gothic and oppressive",
      "Eerily quiet",
      "Outwardly normal but deeply wrong",
      "Desperate and hunted",
      "Ancient and unknowable",
    ],
    "Cosmic Horror": COSMIC_HORROR_SETTLEMENT.tones,
    Western: [
      "Lawless and dangerous",
      "Dusty and hardscrabble",
      "Tense standoff",
      "Boom-and-bust optimistic",
      "Frontier lonely",
    ],
    Steampunk: [
      "Industrial and ambitious",
      "Class-divided and smoggy",
      "Clockwork and eccentric",
      "Imperial and bureaucratic",
      "Rebellious and inventive",
    ],
    "Space Opera Resistance": [
      "Oppressive and militarised",
      "Scrappy and defiant",
      "Desolate and lonely",
      "Ancient and mystical",
      "Lawless and chaotic",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Utopian",
      "Curious",
      "Bureaucratic",
      "Pioneering",
      "Tense",
    ],
  } as Record<string, string[]>,

  mainTensionsByGenre: {
    Fantasy: [
      "Succession crisis",
      "Religious schism",
      "Monster threat on the border",
      "Corrupt leadership",
      "Famine or drought",
      "Trade route cut off",
      "Ancient curse awakening",
    ],
    Pirate: [
      "Naval blockade tightening",
      "Rival crews contesting the harbour",
      "A mutiny spreading through anchored ships",
      "A cursed wreck washing ashore",
      "Trade monopoly strangling local families",
      "Storm season arriving before repairs are finished",
    ],
    "Dark Fantasy": [
      "Spreading corruption",
      "Warlord conquest",
      "Plague outbreak",
      "Undead rising",
      "Dark pact unravelling",
      "Chosen champion gone wrong",
    ],
    Cyberpunk: [
      "Labour unrest",
      "Corporate hostile takeover",
      "Gang war",
      "Data breach",
      "AI malfunction",
      "Blackout threat",
      "Underground resistance rising",
    ],
    "Sci-Fi": [
      "Life support failure",
      "Communication blackout",
      "Resource depletion",
      "Mutiny",
      "First contact situation",
      "Quarantine breach",
      "Corporate exploitation",
    ],
    "Post-Apocalyptic": [
      "Raider siege incoming",
      "Resource scarcity",
      "Leadership collapse",
      "Contamination spreading",
      "Faction civil war",
      "Hidden betrayal",
      "Cult infiltration",
    ],
    Modern: [
      "Political scandal",
      "Economic collapse",
      "Environmental threat",
      "Crime wave",
      "Cultural conflict",
      "Corporate exploitation",
      "Hidden crime network",
    ],
    Horror: [
      "Supernatural haunting",
      "Cult infiltration",
      "Vampire feeding ring",
      "Ancient entity awakening",
      "Mass disappearances",
      "Forbidden ritual",
      "Hidden monster in plain sight",
    ],
    "Cosmic Horror": COSMIC_HORROR_SETTLEMENT.mainTensions,
    Western: [
      "Range war",
      "Railroad company pressure",
      "Outlaw gang threat",
      "Sheriff corruption",
      "Water rights dispute",
      "Mining claim fraud",
    ],
    Steampunk: [
      "Labour strike turning violent",
      "Imperial annexation",
      "Saboteur in the works",
      "Inventor's experiment gone wrong",
      "Guild power struggle",
      "Airship piracy",
    ],
    "Space Opera Resistance": [
      "Imperial crackdown imminent",
      "Syndicate gang war",
      "Rebel cell compromised",
      "Ancient weapon discovered",
      "Blockade causing starvation",
      "Bounty hunters searching the streets",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Threat of a border skirmish",
      "A failing planetary life support system",
      "A diplomatic breakdown between two alien delegations",
      "A mysterious viral outbreak in the medical bay",
      "Sabotage of the main warp reactor",
    ],
  } as Record<string, string[]>,

  authorityTypesByGenre: {
    Fantasy: [
      "Feudal lord",
      "Elected council",
      "Merchant guild",
      "Military commander",
      "High priest / priestess",
      "Arcane council",
      "Tribal elders",
    ],
    Pirate: [
      "An elected harbour council",
      "A pirate captain under shared articles",
      "A merchant syndicate",
      "A naval governor",
      "A loose coalition of ship crews",
    ],
    "Dark Fantasy": [
      "Warlord",
      "Dark sorcerer",
      "Iron council",
      "Despot",
      "Cult master",
      "Undead overlord",
    ],
    Cyberpunk: [
      "Corporate overseer",
      "Gang boss",
      "Elected council",
      "AI system",
      "Military commander",
      "Criminal syndicate",
    ],
    "Sci-Fi": [
      "Station director",
      "Colonial authority",
      "AI administrator",
      "Military command",
      "Corporate board",
      "Elected council",
    ],
    "Post-Apocalyptic": [
      "Warlord",
      "Council of survivors",
      "Cult leader",
      "Military commander",
      "Elected council",
      "AI remnant",
    ],
    Modern: [
      "Elected mayor",
      "Corporate management",
      "Military governor",
      "Criminal boss",
      "Traditional chief",
      "Religious leader",
    ],
    Horror: [
      "Ancient vampire lord",
      "Cult master",
      "Old family council",
      "Hidden entity's puppet",
      "Corrupt official",
      "Religious authority",
    ],
    "Cosmic Horror": COSMIC_HORROR_SETTLEMENT.authorityTypes,
    Western: [
      "Sheriff",
      "Railroad company agent",
      "Cattle baron",
      "Outlaw boss",
      "Town council",
      "Military fort commander",
    ],
    Steampunk: [
      "Guild master",
      "Imperial administrator",
      "Factory owner",
      "Elected alderman",
      "Criminal boss",
      "Inventor-patriarch",
    ],
    "Space Opera Resistance": [
      "Imperial Governor",
      "Syndicate Boss",
      "Rebel General",
      "Corrupt Prefect",
      "Mystic Elder",
      "Frontier Mayor",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Station Commander",
      "Planetary Governor",
      "Science Director",
      "Fleet Admiral",
      "Ambassador",
    ],
  } as Record<string, string[]>,

  notableLocationsByGenre: {
    Fantasy: [
      "The Rusty Anchor Tavern",
      "Temple of the Sun",
      "Grand Archive",
      "Whispering Woods Gate",
      "Vault of Secrets",
      "Alchemist's Greenhouse",
      "Market Bazaar",
      "Ruined Watchtower",
    ],
    Pirate: [
      "A tide-clock tower with a hidden signal room",
      "A ropewalk and shipwright's yard",
      "A neutral tavern where crews negotiate shares",
      "A wreck market selling recovered cargo",
      "A sea cave used as a prison and safe berth",
      "A lighthouse whose keeper records every passing flag",
    ],
    "Dark Fantasy": [
      "The Charnel House",
      "Cursed Temple Ruins",
      "Warlord's Palisade",
      "The Black Well",
      "Plague Hospice",
      "Forbidden Library",
    ],
    Cyberpunk: [
      "Neon Noodle Bar",
      "Data Vault",
      "Black Market Alley",
      "Corporate Security Office",
      "Underground Fight Club",
      "Hacker Den",
      "Medtech Clinic",
      "Abandoned Factory Floor",
    ],
    "Sci-Fi": [
      "Docking Bay Alpha",
      "Research Lab",
      "Life Support Centre",
      "Quartermaster's Store",
      "Communications Array",
      "Hydroponics Bay",
      "Armoury",
      "Observation Deck",
    ],
    "Post-Apocalyptic": [
      "The Scrap Yard",
      "Water Purification Plant",
      "Wall Command Post",
      "Underground Cache",
      "Old Hospital",
      "Radio Tower",
      "Fuel Depot",
      "Trade Tent",
    ],
    Modern: [
      "The Local Diner",
      "Town Hall",
      "Police Station",
      "Community Centre",
      "Old Church",
      "Industrial Warehouse",
      "Marina",
      "Local School",
    ],
    Horror: [
      "The Old Manor House",
      "Abandoned Church",
      "Locked Cemetery",
      "Crooked Inn",
      "Forgotten Archive",
      "Hidden Catacombs",
      "Witchwood Gate",
      "Ruined Mill",
    ],
    "Cosmic Horror": COSMIC_HORROR_SETTLEMENT.notableLocations,
    Western: [
      "The Saloon",
      "Sheriff's Office",
      "General Store",
      "Livery Stable",
      "Bank",
      "The Undertaker's",
      "Railroad Depot",
      "Church",
    ],
    Steampunk: [
      "The Gear and Piston Inn",
      "Factory Floor",
      "Airship Mooring",
      "Guild Hall",
      "Steam Baths",
      "Automaton Repair Shop",
      "Imperial Tax Office",
      "Underground Press",
    ],
    "Space Opera Resistance": [
      "The Cantina",
      "Imperial Garrison Headquarters",
      "Smuggler's Docking Bay",
      "Hidden Mystic Shrine",
      "Jawa-style Scrap Market",
      "Planetary Shield Generator",
      "Rebel Command Center",
      "Bounty Hunter Guildhouse",
    ],
    "Optimistic Exploration Sci-Fi": [
      "The Promenade",
      "Main Engineering",
      "Astrophysics Lab",
      "Diplomatic Quarters",
      "The Arboretum",
      "Shuttlebay",
    ],
  } as Record<string, string[]>,

  factionsByGenre: {
    Fantasy: [
      "The Iron Shield Guard",
      "The Shadow Thieves Guild",
      "The Whispering Monks",
      "The Gilded Merchants",
      "The Arcane Assembly",
    ],
    Pirate: [
      "A crew-bound pirate council",
      "A privateer office with disputed letters of marque",
      "A merchant family controlling the warehouses",
      "A dockworkers' mutual-aid society",
      "A sea cult guarding an offshore shrine",
      "A naval intelligence cell embedded in the port",
    ],
    "Dark Fantasy": [
      "The Iron Legion",
      "The Carrion Cult",
      "The Last Survivors' Council",
      "The Dark Patrons",
      "The Resistance Cell",
    ],
    Cyberpunk: [
      "The Chrome Wolves",
      "Axiom Corporation",
      "The Underground Wire",
      "The Street Docs Collective",
      "Data Liberation Front",
    ],
    "Sci-Fi": [
      "Colonial Authority",
      "The Freighter's Union",
      "Systems Research Division",
      "The Separatist Cell",
      "Station Security Corps",
    ],
    "Post-Apocalyptic": [
      "The Ironclad Raiders",
      "The Water Keepers",
      "The Old World Faithful",
      "The Scavenger Collective",
      "The Wall Guard",
    ],
    Modern: [
      "The Town Council",
      "Local Crime Family",
      "Environmental Activists",
      "The Business Association",
      "Underground Resistance",
    ],
    Horror: [
      "The Old Bloodline",
      "The Hollow Cult",
      "The Watchmen",
      "The Whispering Circle",
      "The Fallen Church",
    ],
    "Cosmic Horror": COSMIC_HORROR_SETTLEMENT.factions,
    Western: [
      "The Railroad Company",
      "The Cattle Baron's Men",
      "The Outlaw Gang",
      "The Townsfolk's Posse",
      "The Native Nation",
    ],
    Steampunk: [
      "The Gearworkers' Union",
      "The Imperial Oversight Bureau",
      "The Inventor's Guild",
      "The Smoke Brotherhood",
      "The Underground Press",
    ],
    "Space Opera Resistance": [
      "The Imperial Legion",
      "The Rebel Alliance Cell",
      "The Crimson Syndicate",
      "The Mystic Order Vanguard",
      "The Bounty Hunter Guild",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Starfleet equivalent",
      "Romulan equivalent",
      "Klingon equivalent",
      "Maquis equivalent",
      "Section 31 equivalent",
      "Orion Syndicate equivalent",
    ],
  } as Record<string, string[]>,

  namePrefixesByGenre: {
    Fantasy: [
      "Cinderwall",
      "Stonebridge",
      "Coppergate",
      "Ashveil",
      "Saltmarsh",
      "Redthorn",
      "Greywarden",
      "Deepwell",
    ],
    Pirate: ["Salt", "Free", "Tide", "Blackwater", "Storm", "Lantern"],
    "Dark Fantasy": [
      "Grimfall",
      "Ashmore",
      "Blightwick",
      "Corpsewall",
      "Duskgate",
      "Wraithfen",
      "Blackthorn",
      "Deadmere",
    ],
    Cyberpunk: ["Neo", "Syn", "Grid", "Nex", "Core", "Flux", "Arc", "Vex"],
    "Sci-Fi": [
      "Alpha",
      "Kepler",
      "Proxima",
      "Zeta",
      "Orion",
      "Cygnus",
      "Nova",
      "Delta",
    ],
    "Post-Apocalyptic": [
      "Dustwall",
      "Ashgate",
      "Rusted",
      "Ember",
      "Grim",
      "Lastfall",
      "Broken",
      "Salvage",
    ],
    Modern: [
      "Port",
      "Cedar",
      "Millbrook",
      "Riverside",
      "Clearwater",
      "Ashton",
      "Westfield",
      "Mapleton",
    ],
    Horror: [
      "Blackwood",
      "Grimhaven",
      "Ravensmoor",
      "Duskfall",
      "Ashcroft",
      "Hollowmere",
      "Dunmere",
      "Wraithgate",
    ],
    "Cosmic Horror": COSMIC_HORROR_SETTLEMENT.namePrefixes,
    Western: [
      "Dusty",
      "Rattler",
      "Copper",
      "Red Rock",
      "Dry Gulch",
      "Silver",
      "Broken",
      "Rim",
    ],
    Steampunk: [
      "Coppervale",
      "Ironbridge",
      "Ashport",
      "Gearwick",
      "Coalgate",
      "Brassfall",
      "Sootmere",
      "Forgegate",
    ],
    "Space Opera Resistance": [
      "Mos",
      "Tatoo",
      "Aldera",
      "Kash",
      "Coru",
      "Manda",
      "Danto",
      "Yav",
    ],
    "Optimistic Exploration Sci-Fi": [
      "Astra",
      "Nova",
      "Celestia",
      "Sirius",
      "Orion",
      "Vega",
    ],
  } as Record<string, string[]>,

  nameSuffixesByGenre: {
    Fantasy: [
      " Crossing",
      " Keep",
      " Village",
      " Town",
      " Harbour",
      " Hollow",
      " Falls",
      " Ridge",
    ],
    Pirate: ["haven", "reach", "quay", "cove", "watch", "port"],
    "Dark Fantasy": [
      " Rot",
      " Fen",
      " Mire",
      " Hollow",
      " Ruin",
      " Pit",
      " Grave",
      " Watch",
    ],
    Cyberpunk: [
      " Zone",
      "-7",
      " Hub",
      " Grid",
      " Node",
      " Quarter",
      " Block",
      " Core",
    ],
    "Sci-Fi": [
      " Station",
      " Prime",
      " Base",
      "-3",
      " Colony",
      " Outpost",
      " Hub",
      " Point",
    ],
    "Post-Apocalyptic": [
      " Refuge",
      " Ruins",
      " Hold",
      " Waste",
      " Haven",
      " Camp",
      " Pit",
      " Base",
    ],
    Modern: [
      " Heights",
      " Park",
      " Creek",
      " Cove",
      " Bay",
      " Falls",
      " Crossing",
      " Glen",
    ],
    Horror: [
      " Hollow",
      " Manor",
      " Court",
      " Gate",
      " Moor",
      " Fen",
      " Falls",
      " Vale",
    ],
    "Cosmic Horror": COSMIC_HORROR_SETTLEMENT.nameSuffixes,
    Western: [
      " Creek",
      " Flats",
      " Junction",
      " Gulch",
      " Pass",
      " Bend",
      " Springs",
      " Bluff",
    ],
    Steampunk: [
      " Works",
      " Furnace",
      " Viaduct",
      " Port",
      " Engine",
      " Yard",
      " Forge",
      " Quay",
    ],
    "Space Opera Resistance": [
      " Eisley",
      " Prime",
      " Base",
      " Outpost",
      " Station",
      " Enclave",
      " City",
      " Port",
    ],
    "Optimistic Exploration Sci-Fi": [
      " Station",
      " Base",
      " Prime",
      " Outpost",
      " Colony",
      " Hub",
    ],
  } as Record<string, string[]>,

  // Legacy flat arrays — kept for backwards compatibility; map to Fantasy genre defaults.
  get sizes() {
    return this.sizesByGenre["Fantasy"];
  },
  economies: [
    "Agriculture",
    "Mining",
    "Trade Hub",
    "Fishing",
    "Black Market",
    "Arcane Study",
  ],
  governments: [
    "Council of Elders",
    "Feudal Lord",
    "Merchant Oligarchy",
    "Military Dictatorship",
    "Democracy",
    "Magocracy",
  ],
  notableLocations: [
    "The Rusty Anchor Tavern",
    "Temple of the Sun",
    "Grand Archive",
    "Whispering Woods Gate",
    "Vault of Secrets",
    "Alchemist's Greenhouse",
    "Market Bazaar",
    "Ruined Watchtower",
  ],
  factions: [
    "The Iron Shield Guard",
    "The Shadow Thieves Guild",
    "The Whispering Monks",
    "The Gilded Merchants",
    "The Arcane Assembly",
  ],
};
