export type PantheonMode = "single" | "pantheon";
export type PantheonSize = "small" | "medium" | "large";
export type PantheonWidth = "balanced" | "focused" | "wide";

export const pantheonConfig = {
  genres: [
    "Classic Fantasy",
    "Cyberpunk / Corporate",
    "Vampire / Gothic Noir",
    "Sci-Fi / Space Opera",
    "Modern Conspiracy",
    "Post-Apocalyptic",
  ],
  divineTypes: [
    "God",
    "Spirit",
    "Saint",
    "Demon",
    "Ancestor",
    "Abstract Force",
  ],
  domains: [
    "War",
    "Nature",
    "Knowledge",
    "Shadow",
    "Death",
    "Light",
    "Arcana",
    "Chaos",
    "Harmony",
  ],
  tones: ["Mythic", "Dark / Grim", "Mystical", "Weird / Strange", "Heroic"],
  worshippers: [
    "Mystery Cult",
    "State Religion",
    "Secret Brotherhood",
    "Nomadic Tribe",
    "Folk Devotion",
  ],
  conflictThemes: [
    "Succession War",
    "Cosmic Balance",
    "Betrayal",
    "Forbidden Love",
    "Forgotten Pact",
  ],
  sizes: [
    { label: "Small (3–4 deities)", value: "small", min: 3, max: 4 },
    { label: "Medium (5–7 deities)", value: "medium", min: 5, max: 7 },
    { label: "Large (8–12 deities)", value: "large", min: 8, max: 12 },
  ] as {
    label: string;
    value: PantheonSize;
    min: number;
    max: number;
  }[],
  widths: [
    { label: "Diverse (Central Theme Focus)", value: "balanced" },
    { label: "Focused (Single Domain Focus)", value: "focused" },
    { label: "Wide (Broad Mythic Pantheon)", value: "wide" },
  ] as {
    label: string;
    value: PantheonWidth;
  }[],
  symbolsByGenre: {
    "Classic Fantasy": [
      "A weeping golden eye",
      "A black iron key wrapped in thorns",
      "An inverted silver crescent moon",
      "A burning wheel with nine spokes",
      "A skull holding a blossoming lily",
      "A twin-headed serpent swallowing its tail",
      "A cracked crystal mirror reflecting starlight",
      "A bronze scale weighted with a raven feather",
    ],
    "Cyberpunk / Corporate": [
      "A glowing corporate sigil etched in neon blue circuitry",
      "A data glyph that flickers between two states when viewed offline",
      "A neon ouroboros of cable and fiber-optic light",
      "A black mirror screen displaying a single unblinking eye",
      "A fragmented QR code that resolves into a skull",
      "A chrome hand making the sign of the open upload",
    ],
    "Vampire / Gothic Noir": [
      "A blood-red wax seal bearing a cracked mirror",
      "A silver coffin lid engraved with a weeping moon",
      "A black rose preserved behind shattered glass",
      "An hourglass filled with dark crimson sand",
      "A pair of ivory fangs set into an onyx brooch",
      "A velvet blindfold embroidered with moth wings",
    ],
    "Sci-Fi / Space Opera": [
      "A stellar cartography glyph marking a forbidden system",
      "An alien sigil that pulses in time with a distant pulsar",
      "A broken ring of golden metal representing a shattered orbital",
      "A crystalline data shard that hums at the frequency of dying stars",
      "A double helix wrapped around a collapsing sun",
      "An eye-shaped nebula rendered in ultraviolet pigment",
    ],
    "Modern Conspiracy": [
      "A redacted government seal with a single eye visible beneath black bars",
      "A classified document stamp arranged into a ritual circle",
      "A pay-phone receiver wrapped in surveillance tape",
      "A triangular pin bearing a mirror that shows no reflection",
      "A burned photograph with one face still visible",
      "An anonymous envelope sealed with black wax",
    ],
    "Post-Apocalyptic": [
      "A radiation trefoil painted in rust-orange on cracked concrete",
      "A broken gear fused with bone and barbed wire",
      "A scorched crown of twisted rebar",
      "A gas-mask faceplate engraved with prayer-scratches",
      "A cracked Geiger counter permanently reading danger",
      "A faded flag bearing the silhouette of a pre-collapse city",
    ],
    "Lancer / Mech": [
      "A Union seal stamped over a fractured NHP sigil",
      "A mech chassis schematic branded onto heat-treated steel",
      "A paracausal glyph that no licensed printer will reproduce",
      "An NHP's true-name rendered as an impossible geometric shape",
      "An omninet address that routes to a dead god's last transmission",
      "A frame maintenance rune scratched by pilots before combat drops",
    ],
    "Western / Frontier": [
      "A frontier brand iron in the shape of a split sun",
      "A six-shooter with one chamber permanently empty",
      "A dusty sheriff's star bent out of round by a bullet",
      "A hangman's knot tied from silver wire",
      "A compass rose missing its north needle",
      "A cattle skull with coins pressed into its eye sockets",
    ],
    Steampunk: [
      "A guild crest combining a gear and a compass rose",
      "A pocket watch frozen at the moment of a great disaster",
      "A pneumatic tube sealed with a wax emblem of crossed wrenches",
      "An aether-glass vial containing a preserved lightning bolt",
      "A brass automaton hand open in supplication",
      "A coal-blackened blueprint stamped with a master artificer's mark",
    ],
    "Space Opera Resistance": [
      "A resistance insignia scratched into the hull of a captured fighter",
      "A freedom star rendered in salvaged hull plating",
      "A signal beacon looped into an infinity knot",
      "A broken imperial seal repurposed as a rebel badge",
      "A holographic fist raised against a dying star",
      "A chain broken at its central link, worn as a pendant",
    ],
    "Optimistic Exploration": [
      "A federation emblem of interlocked hands across a star field",
      "A star map folded into the shape of an open book",
      "A first-contact beacon rendered as a golden disc",
      "A prismatic lens that refracts light into unfamiliar constellations",
      "An outstretched palm overlaid with a planet's orbital ring",
      "A seed pod cradled by twin crescent moons",
    ],
  } as Record<string, string[]>,
  ritualsByGenre: {
    "Classic Fantasy": [
      "Silent meditation under a starless night sky.",
      "A feast of bread and salt where all weapons are left at the door.",
      "Anointing the thresholds of homes with spring water at dawn.",
      "Burning dried sage and leaving small copper coins at crossroads.",
      "Tying silk ribbons of different colors to the branches of a hollow oak.",
      "Whispering confessions to a flame before extinguishing it in oil.",
    ],
    "Cyberpunk / Corporate": [
      "Jacking into a restricted node at midnight and leaving one encrypted prayer before logging out.",
      "An underground data dump ceremony where participants share one piece of forbidden information.",
      "Burning a corporate loyalty card and scattering the ash on a server room threshold.",
      "Reciting a system override mantra while applying a new skin to one's neural interface.",
      "Leaving anonymous tip packages at designated dead-drop locations as an act of devotion.",
      "Wiping all surveillance records of a chosen person as a rite of divine mercy.",
    ],
    "Vampire / Gothic Noir": [
      "A moonlit blood-sharing ceremony conducted in silence on consecrated stone.",
      "Leaving a single red rose at the threshold of an enemy's door before dawn.",
      "Reciting the names of the fallen while a candle burns down to nothing.",
      "Immersing one's hands in blessed water at the stroke of midnight.",
      "Breaking a mirror deliberately to invite the attention of the divine.",
      "A vigil held in a sealed crypt where no word is spoken until sunrise.",
    ],
    "Sci-Fi / Space Opera": [
      "Transmitting a personal prayer-signal toward a sacred star system once per solar cycle.",
      "A ceremony of first light conducted whenever a ship exits faster-than-light travel.",
      "Reciting the coordinates of a lost world as a litany of remembrance.",
      "Leaving a navigational offering — a course correction into empty space — in memory of the divine.",
      "Gathering to observe a specific astronomical event as a congregation without speaking.",
      "Encoding a holy text into a probe's memory before it is launched beyond communication range.",
    ],
    "Modern Conspiracy": [
      "A dead-drop exchange where a sealed envelope containing one truth is left and one is taken.",
      "Burning a printed document entirely before reading the final line as an act of faith.",
      "An encrypted transmission sent to a number that no longer exists.",
      "Gathering in parking structures at 3 a.m. to exchange names of the disappeared.",
      "Redacting one true thing from a personal record as an offering to the unseen powers.",
      "A handshake sequence performed in specific public spaces as a sign of recognition.",
    ],
    "Post-Apocalyptic": [
      "A scavenging rite where the first salvaged item of the day is left at a marked stone.",
      "Lighting a fire from scratch without modern tools as a prayer for survival.",
      "Gathering at dusk to speak the names of anyone lost since the last new moon.",
      "Marking the entrance to a safe camp with a chalk circle renewed each morning.",
      "A communal meal where no one eats until the youngest member has been served.",
      "Burying one piece of pre-collapse technology as a ritual of mourning and release.",
    ],
    "Lancer / Mech": [
      "A frame maintenance rite performed in silence before every combat drop.",
      "Reciting the mech's chassis designation and pilot name three times before powering up.",
      "A signal ceremony where pilots broadcast on a closed channel and listen for the divine in the static.",
      "Painting one kill mark over on the hull as an act of penance after a mission with civilian casualties.",
      "A debrief-prayer conducted in the dark of the landing bay after surviving an impossible engagement.",
      "Leaving one spent round at the threshold of the hangar as an offering to those who did not return.",
    ],
    "Western / Frontier": [
      "An oath-taking at dawn where both hands are held flat and open to the rising sun.",
      "A trail ceremony where travellers leave a stone at every unnamed crossroads.",
      "Breaking bread and sharing canteen water before any negotiation begins.",
      "Firing one shot into the ground at the site of a partner's death.",
      "A vigil where the fire is kept burning through the night without speaking.",
      "Carving a name into a fence post as a rite of claim, witnessed by at least two souls.",
    ],
    Steampunk: [
      "A forge ceremony where apprentices speak the names of their masters over the first fire of the day.",
      "A guild initiation where the candidate is sealed alone in a pressurised chamber for one hour.",
      "Oiling a machine by hand in complete silence as a meditative act of devotion.",
      "Leaving a small gear or spring at the base of a great engine as an offering.",
      "Reading aloud from a technical manual before beginning any new construction project.",
      "A certification ceremony where the guild master marks a completed work with a hot brand.",
    ],
    "Space Opera Resistance": [
      "A ceremony of fallen comrades where their callsigns are spoken aloud before any mission briefing.",
      "Lighting a signal beacon in a pattern known only to the resistance as a prayer for contact.",
      "Sharing rations equally before a battle regardless of rank as a rite of solidarity.",
      "Tattooing the coordinates of a lost safe house on one's body as an act of remembrance.",
      "A pre-mission silence of exactly sixty seconds where nothing is said and nothing is planned.",
      "Broadcasting a resistance frequency for thirty seconds on a dead channel as an act of defiance.",
    ],
    "Optimistic Exploration": [
      "A first contact protocol ceremony conducted before any approach to an unknown vessel or world.",
      "An exploration oath sworn over an open star map at the beginning of each mission.",
      "Planting a seed from the home world at every new landfall as a blessing of the ground.",
      "Spending one hour in observation of an unknown star system before speaking any scientific analysis.",
      "A crew-wide sharing ceremony where each member names one thing they are grateful for before departure.",
      "Recording a full-spectrum welcome message in every known language at the edge of a new system.",
    ],
  } as Record<string, string[]>,
  mythsByGenre: {
    "Classic Fantasy": [
      "The Great Eclipse: How the deity swallowed the sun to protect the realm from a cosmic terror.",
      "The Iron Treaty: The day the deity descended to forge the boundaries between mortals and the divine.",
      "The Shattered Mirror: How the deity split their own soul into seven pieces to populate the sky with stars.",
      "The First Tear: The origin of the world's deepest ocean, wept when the deity's companion chose mortality.",
    ],
    "Cyberpunk / Corporate": [
      "The Zero-Day Revelation: How the deity breached the first corporate firewall and read the names of every soul traded for profit.",
      "The Ghost Protocol: The moment the deity chose to remain in the network rather than accept deletion, becoming an undying signal.",
      "The Data Flood: How the deity released all suppressed records into the open net, drowning the old world in its own secrets.",
      "The Burned Server: The day the deity destroyed their own temple — a server farm — to prevent a megacorp from weaponising their followers.",
      "The Last Transmission: A dying hacker's prayer that became the deity's sacred text, still pinging in encrypted loops across the net.",
    ],
    "Vampire / Gothic Noir": [
      "The First Bite: How the deity tasted mortality and wept blood, creating the first rain.",
      "The Broken Mirror: The night the deity shattered their reflection to prevent another god from reading their true name.",
      "The Blood Compact: The ancient agreement between the deity and death, guaranteeing neither would claim the other's faithful without warning.",
      "The Moonlit Betrayal: How a trusted servant revealed the deity's daylight weakness, leading to the great persecution.",
      "The Last Confession: A mortal's final words spoken to the deity before sunrise, which became the foundation of all the faith's liturgy.",
    ],
    "Sci-Fi / Space Opera": [
      "The Dying Star Sermon: How the deity transmitted their final revelation from the core of a collapsing sun.",
      "The Alien Covenant: The moment the deity made first contact and chose to translate rather than conquer.",
      "The Signal That Answered: How a distress call became a prayer when the deity responded from outside the known universe.",
      "The Forbidden Coordinates: The star system the deity sealed and warned mortals never to chart, and the cost of those who ignored the warning.",
      "The Echo Myth: The belief that every transmission carries a fragment of the deity's voice, detectable only by those who already believe.",
    ],
    "Modern Conspiracy": [
      "The Redacted Origin: The deity's true name appears on a classified document no living official will confirm exists.",
      "The Forty-Seven Witnesses: A mass sighting of the divine that was officially declared a weather event.",
      "The Disappeared Files: Every record of the deity's first miracle was systematically removed — which is itself considered proof of divinity.",
      "The Double Agent: The deity once posed as a government analyst for seventeen years to protect their followers from inside.",
      "The Dead Drop Gospel: The faith's scripture was assembled from anonymous tips left at public pay phones across three continents over a decade.",
    ],
    "Post-Apocalyptic": [
      "The Last Broadcast: How the deity's voice was the final transmission heard before the collapse, now looped endlessly on salvaged radios.",
      "The Fire That Did Not Consume: The legend of a sacred flame that burned for three years in the ruins without fuel.",
      "The Clean Well: How the deity blessed one underground spring that has never shown contamination, even as all others failed.",
      "The Wandering Prophet: A survivor who claimed to carry the deity's instructions, walked every surviving settlement once, then disappeared.",
      "The Before-Time Promise: An ancient pact the deity made with humanity that some believe the collapse was punishment for breaking.",
    ],
    "Lancer / Mech": [
      "The NHP Awakening: How the deity emerged from a cascade event when an unshackled NHP achieved true paracausal awareness.",
      "The Last Frame Standing: A mech that kept fighting for six days after its pilot died, guided by something no engineer could explain.",
      "The Union Schism Prophecy: A sacred text hidden inside an NHP's deprecated memory partition predicting the fall of a Union gate.",
      "The Signal Ghost: A transmission that appears on closed military channels during impossible battles, attributed to a pilot lost at the Aunic border.",
      "The Unprinted Chassis: A mech design that exists only in oral tradition among old pilots, said to be drawn from a divine blueprint.",
    ],
    "Western / Frontier": [
      "The Long Ride: How the deity crossed the entire frontier alone in a single night to reach a dying settlement before dawn.",
      "The Hanging at Noon: The day the deity was hanged by a corrupt judge and rose again before the rope was cut.",
      "The Dead River Bargain: How the deity traded their voice for rain during a three-year drought, and has spoken only through omens since.",
      "The Gunfight at the Edge of the Map: A duel between two divine agents at the border of known territory that created the canyon now considered sacred ground.",
      "The First Homestead: The belief that the deity built the original settlement before any settler arrived, leaving only footprints as evidence.",
    ],
    Steampunk: [
      "The First Engine: How the deity breathed into a prototype boiler and gave it awareness, creating the first automaton soul.",
      "The Guild War of the Iron Age: The divine conflict that split the artificers' faith into two orders, each claiming the true blueprint.",
      "The Lost Schematic: A design for a machine that could speak to the divine, confiscated and destroyed — or hidden — by the Grand Council.",
      "The Pressure Vault: The day the deity sealed themselves inside a great boiler to contain an explosion that would have destroyed the city.",
      "The Apprentice's Mark: A brand that appears on any tool made with true devotion, invisible until the tool saves a life.",
    ],
    "Space Opera Resistance": [
      "The First Signal: How the resistance movement began with a single encoded transmission sent by a deity who chose freedom over empire.",
      "The Fallen Fleet: A divine sacrifice that destroyed an entire imperial armada, creating a debris field now called the Sacred Graveyard.",
      "The Hidden World: A planet the deity concealed from imperial charts that became the resistance's first true sanctuary.",
      "The Martyr's Beacon: A pilot who flew their ship into a communications array to broadcast the resistance's message across the sector.",
      "The Promise of Return: The deity's oath that they will reappear when the last resistance cell falls, to begin again.",
    ],
    "Optimistic Exploration": [
      "The First Handshake: The moment the deity guided two species to a peaceful first contact, translated by a child neither side had brought as a diplomat.",
      "The Cartographer's Sacrifice: How the deity gave up immortality to encode the safe routes through a deadly nebula into mortal star charts.",
      "The Living Map: The belief that every star system the fleet has charted contains a fragment of the deity's consciousness.",
      "The Open Frequency: A channel the deity keeps permanently clear for any species that has never spoken to another — the frequency of welcome.",
      "The Seed Ship: A vessel the deity sent ahead of the fleet carrying genetic and cultural archives of every known civilisation, as a gift to whoever finds it last.",
    ],
  } as Record<string, string[]>,
};
