/**
 * First names for a settlement's notable inhabitants (#2536).
 *
 * Deliberately separate from `namePrefixesByGenre`/`nameSuffixesByGenre` in
 * `public-settlement-constants.ts`: those are built to combine into place
 * names ("Ashveil" + " Village"), and reusing them for a person produced
 * NPCs named things like "Deepwell Village". A person needs a pool built to
 * read as a person.
 *
 * One flat name per entry rather than prefix/suffix combinatorics, since a
 * settlement only ever needs up to six at once and a flat pool of ten per
 * genre is plenty of headroom for `makeName`'s uniqueness retries.
 */

export const INHABITANT_NAMES_BY_GENRE: Record<string, readonly string[]> = {
  Fantasy: [
    "Bram",
    "Sable",
    "Orin",
    "Wren",
    "Cass",
    "Idris",
    "Marigold",
    "Tobin",
    "Yselle",
    "Hendrik",
  ],
  Pirate: [
    "Solvei",
    "Rask",
    "Marta",
    "Coen",
    "Isobel",
    "Fenn",
    "Grett",
    "Talia",
    "Odger",
    "Junie",
  ],
  "Dark Fantasy": [
    "Merek",
    "Ilse",
    "Corvin",
    "Sela",
    "Bastian",
    "Ravenna",
    "Ulric",
    "Petra",
    "Dorin",
    "Aveline",
  ],
  Cyberpunk: [
    "Nyx",
    "Dex",
    "Cass",
    "Rho",
    "Jax",
    "Mira",
    "Kade",
    "Sable",
    "Ozzy",
    "Vela",
  ],
  "Sci-Fi": [
    "Aster",
    "Voss",
    "Nadia",
    "Rylan",
    "Priya",
    "Denz",
    "Solene",
    "Marcus",
    "Yuki",
    "Idris",
  ],
  "Post-Apocalyptic": [
    "Ash",
    "Birdie",
    "Coot",
    "Doe",
    "Grit",
    "Mercy",
    "Ruck",
    "Salt",
    "Tam",
    "Wick",
  ],
  Modern: [
    "Alex",
    "Priya",
    "Marcus",
    "Elena",
    "Sam",
    "Devon",
    "Nora",
    "Theo",
    "Amara",
    "Jonah",
  ],
  Horror: [
    "Agatha",
    "Silas",
    "Iris",
    "Wendell",
    "Marisol",
    "Cormac",
    "Delia",
    "Osric",
    "Faye",
    "Barnaby",
  ],
  "Cosmic Horror": [
    "Eldon",
    "Prudence",
    "Ambrose",
    "Winnifred",
    "Cornelius",
    "Beatrix",
    "Ezra",
    "Millicent",
    "Absalom",
    "Cressida",
  ],
  Western: [
    "Jed",
    "Dolores",
    "Cole",
    "Birdie",
    "Amos",
    "Sadie",
    "Loyd",
    "Ruth",
    "Cyrus",
    "Nell",
  ],
  Steampunk: [
    "Percival",
    "Odalys",
    "Barnaby",
    "Fenwick",
    "Cordelia",
    "Ambrose",
    "Henrietta",
    "Reginald",
    "Isadora",
    "Thaddeus",
  ],
  "Space Opera Resistance": [
    "Rho",
    "Talon",
    "Vesa",
    "Corin",
    "Ilsa",
    "Bram",
    "Sirin",
    "Dax",
    "Amria",
    "Voss",
  ],
  "Optimistic Exploration Sci-Fi": [
    "Kaia",
    "Bennett",
    "Sora",
    "Idris",
    "Nadia",
    "Callum",
    "Priya",
    "Marek",
    "Elin",
    "Osei",
  ],
};
