import type { ParamMatcher } from "@sveltejs/kit";

const validSlugs = new Set([
  "npc",
  "settlement",
  "magic-item",
  "faction",
  "quest",
  "item",
  "tavern",
  "social-hub",
  "kingdom",
  "nation",
  "vampire-clan",
  "nomad-clan",
  "names",
  "fantasy-names",
  "dnd-npc",
  "pantheon-generator",
  "god-generator",
  "ship-generator",
  "language-generator",
  "news-sheet-generator",
  "dungeon-generator",
  "adventure-generator",
  "adventure-idea-generator",
  "world",
  "council-vote",
  "secret-society",
  "star-system",
  "alien-race",
  "random",
]);

export const match: ParamMatcher = (param) => validSlugs.has(param);
